### ISSUE TITLE
[Bug] Bundle size is too big

### ISSUE THREAD

**Issue by devrsi0n** [Saul-Mirone/milkdown#100]
**Describe the bug**
The bundle size of `@milkdown/core` is too big.
![image](https://user-images.githubusercontent.com/7880675/129840105-0ff777bd-3c17-4562-b1bb-540c21b0cd49.png)
We can reduce a huge bundle size by lib import with `lodash-es`.

**To Reproduce**
https://bundlephobia.com/package/@milkdown/core@4.9.6

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by devrsi0n** [comment]
@Saul-Mirone I can create a PR to address it.

**Comment by Saul-Mirone** [comment]
The lodash-es modules is a pure es module so it can be tree shaked. The package is not bundled for now, users should bundle it themsevles.

**Comment by Saul-Mirone** [comment]
But I think we can remove lodash-es for now because we only use one method in it, we can write one instead of import the whole lib

**Comment by Saul-Mirone** [comment]
Lodash has been remove from the project, bundle size will drop for next release.

**Comment by devrsi0n** [comment]
@Saul-Mirone Wow, that is mind blowing and insane. Thanks you so much.

**Comment by Saul-Mirone** [comment]
https://bundlephobia.com/package/@milkdown/core@4.10.1

I think this's the best we can do, the prosemirror-view package holds most spaces of it now.
https://bundlephobia.com/package/prosemirror-view@1.19.1
