### ISSUE TITLE
[Feature] Add support for HTML tag in markdown string.

### ISSUE THREAD

**Issue by Saul-Mirone** [Saul-Mirone/milkdown#105]
**Is your feature request related to a problem? Please describe.**
Currently a lot of people use html tag in their markdown files.

**Describe the solution you'd like**
Add a HTML node.

Ref:
https://github.com/Saul-Mirone/milkdown-vscode/issues/1

**Comment by mig8447** [comment]
Hello, was this implemented, is there an example that we could use?

**Comment by Saul-Mirone** [comment]
> Hello, was this implemented?, is there an example that we could use?

Hi, I decided not to support this because following 3 reasons:

1. HTML tags has both inline and block types, which cannot be supported by prosemirror schema.
2. HTML tags make the system dangerous for XSS attack
3. Since we support custom syntax, I believe most feature can be implemented though this feature.

**Comment by mig8447** [comment]
It may be too much to ask, but could you expand your first point? I get the XSS part and the syntax extensibility, but my use case requires the preservation of at least the HTML comments supported natively by markdown in both input and output, I think prosemirror supports HTML but I haven´t done any exhaustive research on the matter.

**Comment by Saul-Mirone** [comment]
Prosemirror supports HTML output, but as for the input:
1. It needs user to define the type of the node to be inline or block.
2. It needs user to define the content schema of node, which means, for example: `div` can wrap almost everything as content but `input` can wrap nothing.
3. How to make a friendly html input UX? Should we display HTML source or just display as it is? If we show HTML source, it would be ugly, but if we display as it is, then something like `div`, `main` and `span` would just like disappear and impossible to be edit after they created.

**Comment by mig8447** [comment]
I see, true, what some editors do is give you access to the code in a "code" view alternating between a RTE and a Code Editor.

If I wanted to create a plug-in to do that, where would you suggest to start?

I reviewed most of the core code and I know I can expose the remarkCtx variable to extend the parser with something like rehype or rehype-raw but I haven't dealt with the prosemirror part of it. Do you have any suggestions?

**Comment by Saul-Mirone** [comment]
> I see, true, what some editors do is give you access to the code in a "code" view alternating between a RTE and a Code Editor.
> 
> If I wanted to create a plug-in to do that, where would you suggest to start?
> 
> I reviewed most of the core code and I know I can expose the remarkCtx variable to extend the parser with something like rehype or rehype-raw but I haven't dealt with the prosemirror part of it. Do you have any suggestions?

I think you can take a look at the math plugin, it implements something like `source code editor` that might help you. As for the parser, you can use remark plugin to extend it.

**Comment by langsz** [comment]
> > Hello, was this implemented?, is there an example that we could use?
> 
> Hi, I decided not to support this because following 3 reasons:
> 
> 1. HTML tags has both inline and block types, which cannot be supported by prosemirror schema.
> 2. HTML tags make the system dangerous for XSS attack
> 3. Since we support custom syntax, I believe most feature can be implemented though this feature.

How to implement a table have rowspan or colspan ?
