### ISSUE TITLE
[Bug] 不支持超链接语法

### ISSUE THREAD

**Issue by musistudio** [Saul-Mirone/milkdown#111]
**Describe the bug**
不支持超链接语法\[\]\(\)

**To Reproduce**
直接输入\[百度\]\(https://www.baidu.com\)不解析

**Expected behavior**
能正确解析超链接

**Screenshots**
![image](https://user-images.githubusercontent.com/21162426/130699053-98ebb89c-233c-4a67-8dbe-67e004555406.png)

**Desktop (please complete the following information):**

-   OS: MacOS
-   Browser chrome
-   Version 4.10.0

**Comment by Saul-Mirone** [comment]
因为你先输入了 `[]()`，你需要至少输入`[a]()`，这是prosemirror的框架限制决定的。

**Comment by Saul-Mirone** [comment]
做了一个优化，现在如果你先输入`[]()`，会生成一个empty link，你可以在这里体验 https://milkdown.dev/#/online-demo

会跟着下个版本发布。
