### ISSUE TITLE
[Feature] Plain HTML/JS support

### ISSUE THREAD

**Issue by Throvn** [Saul-Mirone/milkdown#119]
I really love the design and everything about the editor, but I don't use React or Vue in any of my projects.
Is there any plan or way to just implement it via a script tag into an existing framework independent project?

Thanks in advance and best regards,
Louis

**Comment by Saul-Mirone** [comment]
You can just use the vanilla version like this:
https://codesandbox.io/s/milkdown-vanilla-setup-8xobc

**Comment by Throvn** [comment]
Thank you so much!
