### ISSUE TITLE
[Bug] Tab key changes focus instead of inserting `\t`

### ISSUE THREAD

**Issue by ashawkey** [Saul-Mirone/milkdown#123]
**Describe the bug**
Tab key changes focus in the editor and the code-fences.
It seems only in the math block will Tab insert `\t`.

**To Reproduce**
Just press Tab in the online demo (https://milkdown.dev/#/online-demo)

**Expected behavior**
Insert `\t` in the editor and the code-fences as in the math block.

**Desktop (please complete the following information):**

-   OS: Win10
-   Browser chrome

**Comment by Saul-Mirone** [comment]
That's designed to make the editor a11y friendly, you can add a simple [keymap](https://prosemirror.net/docs/ref/#keymap) if you need that.

**Comment by ashawkey** [comment]
Thanks for the quick reply! I will have a look.

**Comment by Saul-Mirone** [comment]
There's no unindent behavior for text, as for list item, you can use `Cmd/Ctrl - ]` and `Cmd/Ctrl - [` to indent and unindent them.
You can find all keymap here: https://milkdown.dev/#/keyboard-shortcuts. Also, you can remap them to the key you want.

**Comment by ashawkey** [comment]
Got it. Looking forward to furthur updates!
