### ISSUE TITLE
change defaultValue programmatically

### ISSUE THREAD

**Issue by sytolk** [Saul-Mirone/milkdown#127]
**Is your feature request related to a problem? Please describe.**
I'm use Rect impl: https://milkdown.dev/#/react and needs to set value to ReactEditor component programmatically ( after set defaultValue)

**Describe the solution you'd like**

```javascript
const MilkdownEditor: React.FC = () => {
  const [isContentLoaded, setContentLoaded] = useState<boolean>(false);

const editor = useEditor(
      (root) => {
        return new Editor()
            .config((ctx) => {
                ctx.set(rootCtx, root);
                ctx.set(defaultValueCtx, "Default value");
            })
            .use(commonmark)
            .use(clipboard)
            .use(listener)
            .use(history);
      },
      [],
  );

useEffect(() => {
    // someting like this miss me
    editor.ctx.set(value,"valueChanged")
},[isContentLoaded])

  return <ReactEditor editor={editor} />;
};

export default MilkdownEditor;
```

**Comment by Saul-Mirone** [comment]
You can use the [action](https://milkdown.dev/#/interacting-with-editor) feature, you can find example [here](https://github.com/Saul-Mirone/milkdown/blob/main/gh-pages/component/MilkdownEditor/MilkdownEditor.tsx#L26), and [here](https://codesandbox.io/s/milkdown-vue-update-ti4zb) for a very simple vue example.

**Comment by sytolk** [comment]
Works for React like that. Thanks @Saul-Mirone but this example miss me in docs
```javascript
import { Slice } from "prosemirror-model";

const MilkdownEditor: React.FC = () => {
  const editorRef = useRef<EditorRef | null>(null);
  const [isContentLoaded, setContentLoaded] = useState<boolean>(false);

const editor = useEditor(
      (root) => {
        return new Editor()
            .config((ctx) => {
                ctx.set(rootCtx, root);
                ctx.set(defaultValueCtx, "Default value");
            })
            .use(commonmark)
            .use(clipboard)
            .use(listener)
            .use(history);
      },
      [],
  );

useEffect(() => {
   if (editorRef.current) {
      const editor = editorRef.current.get();
      if (editor) {
        editor.action((ctx: Ctx) => {
          const view = ctx.get(editorViewCtx);
          const parser = ctx.get(parserCtx);
          const doc = parser('Content changed !!!');
          if (!doc) return;
          const state = view.state;
          view.dispatch(
            state.tr.replace(
              0,
              state.doc.content.size,
              new Slice(doc.content, 0, 0)
            )
          );
        });
      }
    }
},[isContentLoaded])

  return <ReactEditor ref={editorRef} editor={editor} />;
};

export default MilkdownEditor;
```

**Comment by Saul-Mirone** [comment]
Let me add this in doc.

**Comment by danieldaeschle** [comment]
I found a problem with this method. It doesn't preserve new lines like `\n\n\n\n\n`. I think remark removes them.

Is there a known solution?

**Comment by Saul-Mirone** [comment]
> I found a problem with this method. It doesn't preserve new lines like `\n\n\n\n\n`. I think remark removes them.
> 
> Is there a known solution?

That's how markdown syntax works and handled by remark, if you want to change this behavior, you need to write a remark plugin to do this.

**Comment by sytolk** [comment]
@danieldaeschle its not a perfect solution (extra <div> is added) but you can try to create custom component for node: https://github.com/Saul-Mirone/milkdown/blob/main/gh-pages/pages/integrations/react/index.md#custom-component-for-node

with plugin is more complicated.. I have try to change onClick in link with a plugin without success: https://github.com/tagspaces/tagspaces-extensions/blob/Migrate-to-md-editor-extension-to-use-react/md-editor/src/App.tsx#L289

The problem is that plugin receive prosemirror nodes param and dont have access to DOM

**Comment by DogeVenci** [comment]
Is there an example of vue？

**Comment by Saul-Mirone** [comment]
> Is there an example of vue？

Sure, here it is

https://codesandbox.io/s/milkdown-vue-update-ti4zb

**Comment by duhaime** [comment]
@sytolk in your example above where are `editorViewCtx` and `parserCtx` defined?

**Comment by Saul-Mirone** [comment]
#288 Link for track

**Comment by solos** [comment]
Is there an example of angular？

**Comment by abhinandshibu** [comment]
> You can use the [action](https://milkdown.dev/#/interacting-with-editor) feature, you can find example [here](https://github.com/Saul-Mirone/milkdown/blob/main/gh-pages/component/MilkdownEditor/MilkdownEditor.tsx#L26), and [here](https://codesandbox.io/s/milkdown-vue-update-ti4zb) for a very simple vue example.

Unfortunately these links don't work anymore, is it possible for them to be updated?

**Comment by liulangdelimao** [comment]
> > 有vue的例子吗？
> 
> 当然，在这儿
> 
> https://codesandbox.io/s/milkdown-vue-update-ti4zb

no permission
