### ISSUE TITLE
[Feature] Other languages in code-blocks

### ISSUE THREAD

**Issue by xeor** [Saul-Mirone/milkdown#128]
**Is your feature request related to a problem? Please describe.**
I want to render mermaid graphs and do http queries in the code-block sections

**Describe the solution you'd like**
I'm not sure how much is possible, but a generic killer feature would be to support other languages inside the code-blocks.
Example support for mermaid-extensios, like https://shd101wyy.github.io/markdown-preview-enhanced/#/diagrams?id=mermaid, or even a rest client like https://marketplace.visualstudio.com/items?itemName=humao.rest-client. The latter have it's own `http` language.

I think many extensions does it like this, they add their own language. Would it be possible to embed them somehow?

**Describe alternatives you've considered**
There are many plugins that extends markdown. So it feels like the only alternative here is to not use milkdown :(

I wasnt sure where to put this issue, in this repo or the milkdown-vscode. Please let me now if I should move it.

**Comment by xeor** [comment]
Looks like https://github.com/Microsoft/vscode/issues/1751 is a WIP for such a feature.. I found vetur doing something like this, see; https://github.com/Microsoft/vscode/issues/1751#issuecomment-919497777

**Comment by Saul-Mirone** [comment]
https://github.com/Saul-Mirone/milkdown/tree/diagrams
It's in progress and still there are some work need to be done.
![image](https://user-images.githubusercontent.com/10047788/133347579-84147fe8-472a-4d6c-b72d-27260aa495fe.png)

**Comment by xeor** [comment]
Looks like https://code.visualstudio.com/api/language-extensions/embedded-languages might be useful

**Comment by Saul-Mirone** [comment]
This has been finished, you can try it in online demo, npm package will be shipped within this week.

**Comment by xeor** [comment]
Awesome! Looks good!

For future self, this was fixed in - https://github.com/Saul-Mirone/milkdown/commit/16b983899ff8f070db9e93c0f00d29facf4bf580

For miscellaneous languages, like the https://marketplace.visualstudio.com/items?itemName=humao.rest-client, is that something that is feasible? If so, I will create a new issue for it.. What do you think?
