### ISSUE TITLE
[Bug] Update from 4.9.6 to 4.11.2 build error

### ISSUE THREAD

**Issue by sytolk** [Saul-Mirone/milkdown#132]
**Describe the bug**
```
$ react-scripts build
Creating an optimized production build...
Failed to compile.

./node_modules/@milkdown/plugin-tooltip/lib/index.js
Attempted import error: 'createProsePlugin' is not exported from '@milkdown/utils'.
```

with milkdown v.4.9.6 buid succeeded

**To Reproduce**

"build": "react-scripts build"

**Desktop (please complete the following information):**

macOS

**Comment by sytolk** [comment]
maybe the problem is in version 4.11.2 build I see that in github createProsePlugin exist in utils and its exported
https://github.com/Saul-Mirone/milkdown/blob/main/packages/utils/src/atom/base-prose-plugin.ts
https://github.com/Saul-Mirone/milkdown/blob/main/packages/utils/src/index.ts#L2

**Comment by Saul-Mirone** [comment]
What's your local version of @milkdown/utils in node modules?

**Comment by sytolk** [comment]
Its have extra "declare" in my node_modules/@milkdown/utils/lib/atom/base-prose-plugin.d.ts
`export declare const createProsePlugin:`

**Comment by Saul-Mirone** [comment]
Can you paste your package.json here? I need to confirm which package you're using having this problem.

**Comment by Saul-Mirone** [comment]
I update all dependencies versions into v4.11.2 in this [code sand box](https://codesandbox.io/s/milkdown-react-setup-ngkiq) and everything works fine, I think removing node_modules and yarn.lock then try `yarn install` agian maybe helpful.

**Comment by sytolk** [comment]
my bad.. After update it I have not remove yarn.lock (maybe the issue is with yarn). 
Its work now thanks!
https://github.com/tagspaces/tagspaces-extensions/commit/c1de072ba2eb4600484a292f4f1c384ab529ea56#diff-0854bac2ae3884effc67a6052d96ab4021f1ec28bbc4f696df2e5487f6306ff5R31
