### ISSUE TITLE
昨天 star 了此项目并且关注了发版动态，然后今天邮箱...

### ISSUE THREAD

**Issue by ifu25** [Saul-Mirone/milkdown#136]
这是什么情况，不懂就要问，哈哈。

![20210917_170707](https://user-images.githubusercontent.com/5575008/133756730-193b4627-0fb5-4aef-a112-3f3c06474650.png)

**Comment by Saul-Mirone** [comment]
你好，这是发布版本的通知，今天发布了一个版本，共21个包，因此你收到这些通知
