### ISSUE TITLE
Code block style problem

### ISSUE THREAD

**Issue by JinMing6** [Saul-Mirone/milkdown#138]
**Describe the bug**
No highlights. 

**To Reproduce**

1. import { prism } from "@milkdown/plugin-prism";
2. use(prism)

**Expected behavior**
![image](https://user-images.githubusercontent.com/57794614/133871404-787d9f7f-a379-4179-a7d7-e10811b78a1e.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/57794614/133871420-c54697b3-cf9b-4bf1-80e9-c09a06c43267.png)

**Desktop (please complete the following information):**

-   OS: win10
-   Browser chrome
-   Version 93

**Comment by Saul-Mirone** [comment]
When using nord theme, you should import material icon, and when using prism plugin, you need to choose a code theme and import it. For example:
```html
<!-- add material icon -->
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined" />
<!-- add prism theme -->
<link rel="stylesheet" href="https://unpkg.com/prism-themes/themes/prism-material-light.css" />
```
