### ISSUE TITLE
code-fence bugs

### ISSUE THREAD

**Issue by xiadd** [Saul-Mirone/milkdown#14]
1、when `Shift-Enter` leave code-fence node，other nodes dont work properly
2、tab key in code-fence

**Comment by Saul-Mirone** [comment]
I think `Mod-Enter` is the default way to leave the code fence node. It seems that `Shift-Enter` will add an additional empty line.
Tab key in code-fence seems like a bug need to fix.

**Comment by Saul-Mirone** [comment]
Fixed, now we can use same keymap for different nodes and marks.
