### ISSUE TITLE
[Bug] 粘贴过来的md语法不被解析

### ISSUE THREAD

**Issue by musistudio** [Saul-Mirone/milkdown#142]
**Describe the bug**
ProseMirror默认不会解析粘贴过来的markdown，但是如果不做解析的话很影响书写体验，就没办法所见即所得了。

**To Reproduce**

1. 在纯文本中任意复制一段md(我发现从源代码模式粘贴的md语法能被正确解析)

**Expected behavior**
能解析粘贴过来的md语法

**Screenshots**
![image](https://user-images.githubusercontent.com/21162426/134752367-e6ed4371-f1c5-4fb1-b5c5-84b23cf7801a.png)

**Desktop (please complete the following information):**

-   OS: [MacOS]
-   Browser [chrome]

**Comment by Saul-Mirone** [comment]
你说的纯文本具体是指哪里

**Comment by musistudio** [comment]
> 你说的纯文本具体是指哪里

纯文本编辑器，比如vscode

**Comment by Saul-Mirone** [comment]
Fixed in main branch
