### ISSUE TITLE
我看过文档，发现创建react组件案例写的相当简陋，能写一个完整可用的么？

### ISSUE THREAD

**Issue by windf17** [Saul-Mirone/milkdown#143]
我看了官方案例里面功能相当简陋，还有许多插件需要另外集成。

请能不能提供一个类似csdn的markdown编辑器的react组件，默认配置集成了完整功能的markdown组件。

另外需要组件提供将md文本转成自带格式的html文本的api。

万分感谢，已点Star！

**Comment by Saul-Mirone** [comment]
1. 插件化是框架设计原则，就像vscode也不会将自己改造成webstorm，也方便二次封装
2. prosemirror有导出html的API可以直接使用
