### ISSUE TITLE
Shift + Enter creates an entirely new block on mobile

### ISSUE THREAD

**Issue by DonkeyKong21** [Saul-Mirone/milkdown#144]
Hi there, love what you guys are doing with the editor. I really wanted to thank you for all of your hardwork.  One issue I have is Shift + Enter on mobile goes into a directly new block (the one where you get a double space and a new slash command). This doesn't seem like the case for desktop. So I'm thinking this is a bug?

Also by any chance, are draggable checkboxes possible and is that something you guys are planning to incorporate in the future?

**Comment by Saul-Mirone** [comment]
Hi, I'm wondering how can I input Shift + Enter on mobile?

As for the draggable checkboxes, all blocks are draggable for now on desktop, what you need is use `Cmd/Ctrl` + left click on the block you want to drag, then you can drag it where you want.

**Comment by DonkeyKong21** [comment]
Sorry I meant to say Shift + Return, On iOS it would be the Arrow Up + Return.

And I didn't know that in regards to the draggable. Can't wait to see it on mobile :)

**Comment by DonkeyKong21** [comment]
I see, is there a way to fix and register the shift + return on mobile to behave the same way on desktop?

**Comment by Saul-Mirone** [comment]
I think it depends on the native mobile keyboard, as far as I know, it doesn't support compose key bindings like `Ctrl/Cmd + V`, so I think for mobile, you may need an additional toolbar or some input rules to make it works.
