### ISSUE TITLE
[Bug] Math plugin - katex.css missing

### ISSUE THREAD

**Issue by sytolk** [Saul-Mirone/milkdown#148]
**Describe the bug**
I have try math plugin but its not look like in Demo and I see that katex.css is missing why this exist:
 https://github.com/Saul-Mirone/milkdown/blob/8e004ce59cabd650b022390460e4a77c12936e8d/gh-pages/index.html#L21

I see that katex.css is imported in node_modules why not loaded from here?
![547A8D2E-828B-4FF7-AEAC-CF7EDE35FD4F](https://user-images.githubusercontent.com/1415463/135413856-93b9b568-c65b-4ec8-80ca-f8988131e19b.png)

**Comment by sytolk** [comment]
I have fix it like this:
```
import 'katex/dist/katex.css';
const MilkdownEditor = ...
```
but its missing in math plugin README: 
https://github.com/Saul-Mirone/milkdown/blob/main/packages/plugin-math/README.md

**Comment by Saul-Mirone** [comment]
I should add this to readme, users need to import the katex style files. What you do is right.

**Comment by Saul-Mirone** [comment]
Readme updated here:
https://github.com/Saul-Mirone/milkdown/tree/main/packages/plugin-math
