### ISSUE TITLE
[Bug] Sourcemap cannot find original files

### ISSUE THREAD

**Issue by mig8447** [Saul-Mirone/milkdown#151]
**Describe the bug**
Sourcemaps point to src instead to lib (Which is the directory shipped on the npm package) which makes the library un-debuggable

**To Reproduce**

1. Use your base example in the doc
2. npm run start
3. Open the browser
4. Open DevTools
5. Open Sources Panel
6. Open Right Panel
7. Try to open node_modules/@milkdown/core/src/editor/editor.ts

This results on

```
Could not load content for http://localhost:3000/node_modules/@milkdown/core/src/editor/editor.ts (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)
```

**Expected behavior**
Be able to debug the js files shipped in the package

**Screenshots**

![chrome_lmOp7GB20X](https://user-images.githubusercontent.com/11009660/135727776-fef474b1-cdb1-4535-bb3c-3fa9faf31b4f.png)

**Desktop (please complete the following information):**

-   OS: Windows
-   Browser: Chrome
-   Version: 94.0.4606.61

**Additional context**
I'm trying to follow the execution step-by-step

**Comment by Saul-Mirone** [comment]
Should be fixed in v4.13.1, feel free to reopen this if you have further questions.
