### ISSUE TITLE
[Bug] InsertImage causes error when inserted after an inline block

### ISSUE THREAD

**Issue by mig8447** [Saul-Mirone/milkdown#153]
**Describe the bug**
When an image is inserted programmatically via editor.action immediately after an inline block, the following error is thrown:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'add')
    at TextViewDesc2.selectNode
    at syncNodeSelection
    at selectionToDOM
    at EditorView2.updateStateInner
    at EditorView2.updateState 
    at EditorView2.dispatch
    at updateHandle
    at handleMouseMove
    at Plugin2.mousemove
    at 
```

**To Reproduce**

1. Setup a button to execute the InsertImage command
2. Add inline text and leave the cursor at the end of the inline text
3. Click the button

**Expected behavior**
No error generated, image block should be inserted as a "next" block

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Browser Chrome
-   Version 94

**Comment by Saul-Mirone** [comment]
Should be fixed in 4.13.2
