### ISSUE TITLE
[Feature] Does the parser support markdown-it

### ISSUE THREAD

**Issue by pinghe** [Saul-Mirone/milkdown#156]
https://github.com/markdown-it/markdown-it

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Saul-Mirone** [comment]
No, it only supports remark.

**Comment by Saul-Mirone** [comment]
> remark vs  micromark?
> 
> https://github.com/micromark/micromark  

They are the same thing. Remark is based on micromark.

**Comment by echarles** [comment]
@Saul-Mirone Since 4.4, Markdown-it is replaced with Remark.

What if I need features provided by Markdown-it plugins that are not available in the Remark ecosystem?

Is there a way to add those plugins easily in the current Remark world, or do I rather need to reimplement them in Remark?

**Comment by Saul-Mirone** [comment]
> @Saul-Mirone Since 4.4, Markdown-it is replaced with Remark.
> 
> 
> 
> What if I need features provided by Markdown-it plugins that are not available in the Remark ecosystem?
> 
> 
> 
> Is there a way to add those plugins easily in the current Remark world, or do I rather need to reimplement them in Remark?

I think it have to be reimplement, they are built on totally different structures

**Comment by echarles** [comment]
> I think it have to be reimplement, they are built on totally different structures

Makes sense. This is also what I was thinking but wanted to double check. Thx.
