### ISSUE TITLE
[Feature] Is there a way to conver it to docx or pdf?

### ISSUE THREAD

**Issue by leon-kfd** [Saul-Mirone/milkdown#162]
I want to conver the markdown to a docx or pdf file. And it is better to keep the css style. Some one have any idea?

**Comment by langsz** [comment]
> There's no direct API to do this. However, you can [get the html output](https://codesandbox.io/s/milkdown-html-listener-ol8b7), then use some tools like [this](https://github.com/eKoopmans/html2pdf.js) to convert html to pdf.

@Saul-Mirone  I found that the html tree is different as the editor html dom tree. how to keep the display as same as the editor display?

**Comment by Saul-Mirone** [comment]
> > There's no direct API to do this. However, you can [get the html output](https://codesandbox.io/s/milkdown-html-listener-ol8b7), then use some tools like [this](https://github.com/eKoopmans/html2pdf.js) to convert html to pdf.
> 
> @Saul-Mirone I found that the html tree is different as the editor html dom tree. how to keep the display as same as the editor display? ![image](https://user-images.githubusercontent.com/31126835/167814071-12f01d9e-a5bf-464d-8b71-9a35b9b08efc.png)
> 
> you can see my demo. the list and the image are different.

Because some of the plugins are rendered by [nodeviews in prosemirror](https://prosemirror.net/docs/ref/#view.EditorProps.nodeViews). And when DOM seriailizer parse them, they'll rendered by `toDOM` instead of `nodeViews`. I'm still thinking a good solution about this.

**Comment by Card007** [comment]
> 

This Codesandbox link has expired, is have a new one?

**Comment by sensiblearts** [comment]
If anyone is still interested, I got [Prosemirror-docx](https://github.com/curvenote/prosemirror-docx) basically working with Milkdown.

It's basically this:

```TypeScript
    import { editorStateCtx } from '@milkdown/core';
    import { defaultDocxSerializer, writeDocx } from 'prosemirror-docx';    
    import { fileSave } from 'browser-fs-access';  
     // See: https://github.com/GoogleChromeLabs/browser-fs-access
                    

 theEditor.saveDocx = async () => {

                // prepare all image Buffers in advance so that we do not need async:
                let imgBufferMap : Map<string, Buffer> = await noteAttachments.getAllImageBuffersMap(); 
               
                editor.action((ctx) => {
                    const state = ctx.get(editorStateCtx)
                    const opts: any = {
                        getImageBuffer(src: string)  {   // this MUST return a Buffer, synchronously
                            return imgBufferMap.get(src);
                        },
                    };
                    const wordDocument = defaultDocxSerializer.serialize(state.doc, opts);
               
                    writeDocx(wordDocument, (buffer: any) => {
                        const blob = new Blob([buffer]);
                        
                         fileSave(blob, {
                            fileName: "Nature_Journal_Export.docx",
                            extensions: ['.docx'],
                        }).then(() => {
                            console.log("saved docx.");
                        });
            
                    });
            
                });



            };
```
