### ISSUE TITLE
[Feature] Tooltip: can set position fixed mode optional?

### ISSUE THREAD

**Issue by leon-kfd** [Saul-Mirone/milkdown#163]
![image](https://user-images.githubusercontent.com/30256102/138231912-dcb277fa-eba4-4008-a270-3bdb38c75909.png)

I think it can add a option to set the tooltip toggle as position:fixed and append it to body.

![image](https://user-images.githubusercontent.com/30256102/138232166-4d6f5571-e91a-4173-9df6-8921c3cc66e1.png)

But it need a new way to calc the button position.

**Comment by leon-kfd** [comment]
![image](https://user-images.githubusercontent.com/30256102/138234252-943f74e0-640c-46cb-9290-63570a1c95cc.png)
I think user can add a custom option in here. And the option will inject to `createTooltip`  function.

**Comment by Saul-Mirone** [comment]
I think it's better to calculate the toolbar's position like the `slash` plugin, if there's no enough space on top, we can just render it below the block. Something like this:
![image](https://user-images.githubusercontent.com/10047788/138316712-befc81be-cc3f-4c04-9e89-49ba507ba72b.png)
