### ISSUE TITLE
[Feature] Getting the current block style

### ISSUE THREAD

**Issue by danieldaeschle** [Saul-Mirone/milkdown#166]
Maybe it should be document well kr implemented. I need a functionality to receive the current block style as well as formatting like bold, italic etc.

If there is already a solution I would highly appreciate an example.

**Comment by Saul-Mirone** [comment]
In milkdown, something like bold, italic are prosemirror marks. You can get current node's marks through:

```typescript
const currentNode = state.selection.$from.node();
const marks = currentNode.marks;
```

That's part of prosemirror ability, you can check the [reference manual](https://prosemirror.net/docs/ref/#model.Mark) of it.
