### ISSUE TITLE
Necessary properties, toJSON, fromJSON, toHTML, fromHTML, editable

### ISSUE THREAD

**Issue by xiadd** [Saul-Mirone/milkdown#18]
Programally set editor's content

**Comment by Saul-Mirone** [comment]
- [x] toJSON -- support through listener
- [x] toHTML -- support throught listener
- [x] editable
- [ ] fromHTML
- [ ] fromJSON

**Comment by Saul-Mirone** [comment]
All feature supported! Please check the latest doc https://saul-mirone.github.io/milkdown/#/interacting-with-editor to learn the feature!
