### ISSUE TITLE
[Bug] Build failed when lock package version.

### ISSUE THREAD

**Issue by leon-kfd** [Saul-Mirone/milkdown#182]
I lock the mikdown version in v4.14.1, then CI build failed.

![image](https://user-images.githubusercontent.com/30256102/140770093-45dede24-c85e-4d23-b468-9506bf295639.png)

![image](https://user-images.githubusercontent.com/30256102/140769898-2ce8669d-7c15-425d-b596-4ca04330f41b.png)

I wonder if I can't do this. Is the `utils` package always request the latest?

**Comment by leon-kfd** [comment]
![image](https://user-images.githubusercontent.com/30256102/140771361-45d09885-9ce1-42cc-a0de-cd4168826067.png)
I saw the dependencies of `@milkdown/utils` is require a `*` version.

**Comment by Saul-Mirone** [comment]
It's a known bug and I'll fix it soon.

**Comment by Saul-Mirone** [comment]
It seems that pnpm need `"workspace:*"`, but I provide `"workspace: *"`. It's fixed by this: https://github.com/Saul-Mirone/milkdown/commit/2677a3dafcb3cbb18f196978b9c5ed6917995fd6 and will be released soon.
