### ISSUE TITLE
Question for Vue3

### ISSUE THREAD

**Issue by ZzzzzzzSkyward** [Saul-Mirone/milkdown#192]
When using Vite to run a dev server, the browser console shows these messages, and there is no Milkdown editor.
```
 [Vue warn]: provide() can only be used inside setup().
 [Vue warn]: Invalid VNode type: Symbol("Fragment") (symbol) 
  at <VueEditor editor=fn > 
  at <Milkdown> 
  at <App>
```
Moreover, when accessing Milkdown directly in the console as follows:
```
editor = Editor.make()
        .use(nord)
        .use(commonmark)
        .config((ctx) => {
          ctx.set(rootCtx, parent || document.body);
          ctx.set(editorViewOptionsCtx, { editable });
          if (node)
            ctx.set(defaultValueCtx, {
              type: "html",
              dom: node,
            });
          else ctx.set(defaultValueCtx, text || "#New Milkdown");
        })
        .use(math)
        .use(history)
        .use(emoji)
        .use(tooltip)
        .use(slash)
        .create()
```
the console given such message as 
```
Uncaught (in promise) Error: It seems that no theme found in editor, please make sure you have use theme in front of all plugins.
If you prefer to use an empty theme, you can use `themeFactory({})`.
```
What's wrong?

**Comment by Saul-Mirone** [comment]
You should check the demo here: https://codesandbox.io/s/milkdown-vue-setup-wjdup.

**Comment by ZzzzzzzSkyward** [comment]
After completely reinstalling vue it started to work.
By the way, when using plugin shiki as `import { shiki } from 'milkdown-plugin-shiki';`, vite reported ` matching export in "node_modules/@milkdown/core/lib/index.js" `, it seemed that prosePluginFactory and findChildren were missing, were they?

**Comment by Saul-Mirone** [comment]
> After completely reinstalling vue it started to work. By the way, when using plugin shiki as `import { shiki } from 'milkdown-plugin-shiki';`, vite reported `No matching export in "node_modules/@milkdown/core/lib/index.js"`, it seemed that prosePluginFactory and findChildren were missing, were they?

`milkdown-plugin-shiki` only supports milkdown@v4, I think they need to upgrade to milkdown@v5.
