### ISSUE TITLE
[Bug] Empty text nodes are not allowed

### ISSUE THREAD

**Issue by ununian** [Saul-Mirone/milkdown#203]
**To Reproduce**

1. set value
```js
ctx.set( defaultValueCtx, '```js\n ```' );
```

**Expected behavior**

**Screenshots**
 
![image](https://user-images.githubusercontent.com/4506072/144229826-f72fa67a-519c-476a-ad21-888917a1d418.png)

**Comment by Saul-Mirone** [comment]
Fixed by https://github.com/Saul-Mirone/milkdown/commit/924e12ddd642af099cc4d8e422fffef3090c410f
Will be released in this week.
