### ISSUE TITLE
[Bug] MilkdownEditor onChange is fired many times on load with the same content (extra new line added to the end and with escaped _)

### ISSUE THREAD

**Issue by sytolk** [Saul-Mirone/milkdown#204]
**Describe the bug**

`"@milkdown/core": "^5.1.1",`

```javascript
const milkdownListener = React.useCallback((getMarkdown: () => string) => {
    updateContent(getMarkdown());
  }, []);

const updateContent = (content: string) => {
    if (window.mdContent.trim() !== content.trim()) {
      window.mdContent = content;
      console.log('content changed'+content);
    }
  };

<MilkdownEditor
          ref={milkdownRef}
          content={getContent()}
          onChange={milkdownListener}
          readOnly={readOnly()}
        />
```

This is the console log output:
```
content changed:![dropdown mockup](https://www.cbui.dev/github-actions-limitations-and-gotchas/no-dropdowns.png)

workflow\_dispatch
```

**To Reproduce**

The issue only happened with this md file content
```
![dropdown mockup](https://www.cbui.dev/github-actions-limitations-and-gotchas/no-dropdowns.png)

workflow_dispatch
```

**Comment by Saul-Mirone** [comment]
We don't have  onChange API now, what's your version?

**Comment by sytolk** [comment]
"@milkdown/core": "^5.1.1"

**Comment by Saul-Mirone** [comment]
How do you define your component?

**Comment by sytolk** [comment]
This is my MilkdownEditor component
```
import React, { forwardRef } from 'react';
import { editorViewCtx, parserCtx } from '@milkdown/core';
import { EditorRef, ReactEditor, useEditor, useNodeCtx } from '@milkdown/react';
import { Slice } from 'prosemirror-model';

import { createEditor } from './editor';
import { Loading } from './Loading';
import className from './style.module.css';
import { Content, useLazy } from './useLazy';
import { commonmark, image, link } from '@milkdown/preset-commonmark';
import 'katex/dist/katex.css';

type Props = {
  content: Content;
  readOnly?: boolean;
  onChange?: (getMarkdown: () => string) => void;
};

export type MilkdownRef = { update: (markdown: string) => void };
const MilkdownEditor = forwardRef<MilkdownRef, Props>(
  ({ content, readOnly, onChange }, ref) => {
    const editorRef = React.useRef<EditorRef>(null);
    const [editorReady, setEditorReady] = React.useState(false);

    const [loading, md] = useLazy(content);

    React.useImperativeHandle(ref, () => ({
      update: (markdown: string) => {
        if (!editorReady || !editorRef.current) return;
        const editor = editorRef.current.get();
        if (!editor) return;
        editor.action(ctx => {
          const view = ctx.get(editorViewCtx);
          const parser = ctx.get(parserCtx);
          const doc = parser(markdown);
          if (!doc) return;
          const state = view.state;
          view.dispatch(
            state.tr.replace(
              0,
              state.doc.content.size,
              new Slice(doc.content, 0, 0)
            )
          );
        });
      }
    }));

    function hasURLProtocol(url: any) {
      return (
        url.startsWith('http://') ||
        url.startsWith('https://') ||
        url.startsWith('file://') ||
        url.startsWith('data:') ||
        url.startsWith('ts:?ts')
      );
    }

    // @ts-ignore
    const isWeb = window.isWeb;

    const TSLink: React.FC = ({ children }) => {
      const { node } = useNodeCtx();

      // title={node.attrs.title}

      const clickLink = (evt: any) => {
        evt.preventDefault();

        let path;
        if (!hasURLProtocol(node.attrs.href)) {
          path =
            (isWeb ? '' : 'file://') +
            // @ts-ignore
            window.fileDirectory +
            '/' +
            encodeURIComponent(node.attrs.href);
        } else {
          path = node.attrs.href;
        }

        window.parent.postMessage(
          JSON.stringify({
            command: 'openLinkExternally',
            link: path
          }),
          '*'
        );
      };
      return readOnly ? (
        <a href="#" onClick={clickLink}>
          {children}
        </a>
      ) : (
        <a href="#">{children}</a>
      );
    };

    const TSImage: React.FC = ({ children }) => {
      const { node } = useNodeCtx();

      let path;
      if (!hasURLProtocol(node.attrs.src)) {
        path =
          (isWeb ? '' : 'file://') +
          // @ts-ignore
          window.fileDirectory +
          '/' +
          node.attrs.src;
      } else {
        path = node.attrs.src;
      }

      return (
        <img
          // className="ts-image"
          src={path}
          alt={node.attrs.alt}
          title={node.attrs.title}
        />
      );
    };

    /*const TSParagraph: React.FC = ({ children }) => (
          <p>
              <div style={{ display: 'inline-flex' }}>{children}</div>
          </p>
      );*/

    const editor = useEditor(
      (root, renderReact) => {
        const nodes = commonmark
          // .configure(paragraph, { view: renderReact(TSParagraph) })
          .configure(link, { view: () => renderReact(TSLink) })
          .configure(image, { view: () => renderReact(TSImage) });
        return createEditor(
          root,
          md,
          readOnly,
          setEditorReady,
          nodes,
          onChange
        );
      },
      [readOnly, md, onChange]
    );

    return (
      <div className={className.editor}>
        {loading ? (
          <Loading />
        ) : (
          <ReactEditor ref={editorRef} editor={editor} />
        )}
      </div>
    );
  }
);

export default MilkdownEditor;

```

**Comment by sytolk** [comment]
and this is editor.ts

import {
  defaultValueCtx,
  Editor,
  editorViewOptionsCtx,
  EditorViewReady,
  MilkdownPlugin,
  rootCtx
} from '@milkdown/core';
import { clipboard } from '@milkdown/plugin-clipboard';
// import { cursor } from '@milkdown/plugin-cursor';
import { diagram } from '@milkdown/plugin-diagram';
import { emoji } from '@milkdown/plugin-emoji';
import { history } from '@milkdown/plugin-history';
import { listener, listenerCtx } from '@milkdown/plugin-listener';
import { math } from '@milkdown/plugin-math';
import { prism } from '@milkdown/plugin-prism';
import { defaultActions, slash, slashPlugin } from '@milkdown/plugin-slash';
import { tooltip } from '@milkdown/plugin-tooltip';
import { gfm } from '@milkdown/preset-gfm';
import { nord } from '@milkdown/theme-nord';
import { commonmark } from '@milkdown/preset-commonmark';
import { AtomList } from '@milkdown/utils';

const complete =
  (callback: () => void): MilkdownPlugin =>
  () =>
  async ctx => {
    await ctx.wait(EditorViewReady);

    callback();
  };

export const createEditor = (
  root: HTMLElement | null,
  defaultValue: string,
  readOnly: boolean | undefined,
  setEditorReady: (ready: boolean) => void,
  nodes: AtomList<MilkdownPlugin>,
  onChange?: (getMarkdown: () => string) => void
) => {
  const editor = Editor.make()
    .config(ctx => {
      ctx.set(rootCtx, root);
      ctx.set(defaultValueCtx, defaultValue);
      ctx.set(editorViewOptionsCtx, { editable: () => !readOnly });
      ctx.set(listenerCtx, { markdown: onChange ? [onChange] : [] });
    })
    .use(nord)
    .use(commonmark)
    .use(nodes)
    .use(gfm)
    .use(complete(() => setEditorReady(true)))
    .use(clipboard)
    .use(listener)
    .use(history)
    // .use(cursor)
    .use(prism)
    .use(diagram)
    // .use(table)
    .use(tooltip)
    .use(math)
    .use(emoji)
    .use(
      slash.configure(
        slashPlugin,
        {
          config: ctx => {
            // Get default slash plugin items
            const actions = defaultActions(ctx);
            // Define a status builder
            return ({ isTopLevel, content, parentNode }) => {
              // You can only show something at root level
              if (!isTopLevel) return null;

              // Empty content ? Set your custom empty placeholder !
              if (!content) {
                return {
                  placeholder: readOnly
                    ? 'Click the edit button or double click to start editing'
                    : 'Type / to use the slash commands...'
                };
              }

              if (content.startsWith('/')) {
                return content === '/'
                  ? {
                      placeholder: 'Type to filter...',
                      actions
                    }
                  : {
                      // @ts-ignore
                      actions: actions.filter(({ keyword }) =>
                        keyword.some((key: any) =>
                          key.includes(content.slice(1).toLocaleLowerCase())
                        )
                      )
                    };
              }
            };
          }
        }
        /*{
        placeholder: {
          [CursorStatus.Empty]: readOnly
            ? 'Click the edit button or double click to start editing'
            : 'Type / to use the slash commands...',
          [CursorStatus.Slash]: 'Type to filter...'
        }
      }*/
      )
    );

  return editor;

  /*Editor.make()
        .config((ctx) => {
            context = ctx;
            ctx.set(rootCtx, root);
            const content = getContent();
            if (content) {
                ctx.set(defaultValueCtx, content);
            }
            ctx.set(listenerCtx, listenerConf); // { markdown: [(x) => console.log(x())] });
            ctx.set(editorViewOptionsCtx, { editable });
        })
        .use(nord)
        .use(nodes)
        // .use(AtomList.create([clickPlugin()]))
        //.use([directiveRemarkPlugin, link])
        .use(commonmark)
        .use(clipboard)
        .use(listener)
        .use(history)
        .use(emoji)
        .use(table)
        .use(math)
        .use(slash)
        .use(tooltip)*/
};

**Comment by Saul-Mirone** [comment]
Seems you put everything into the MilkdownEditor component, and if it rerender, the components inside it will be recreated, would it be helpful if you move out them?

**Comment by sytolk** [comment]
I'm using this plugin `import { listener, listenerCtx } from '@milkdown/plugin-listener';` to handle editor content changes. The debugging shows that there is no rerenders of MilkdownEditor component only onChange event is fired many times and this depends of content of the markdown file. If you have plugin-listener sample I can try to repeat this issue ?

**Comment by sytolk** [comment]
const updateContent = (content: string) => {
    const cleanContent = content.trim().replace('\\_', '_');
    if (window.mdContent !== cleanContent) {

const updateContent = (content: string) => {
    if (window.mdContent.trim() !== content.trim()) {
      window.mdContent = content;
      console.log('content changed'+content);
    }
  };

**Comment by Saul-Mirone** [comment]
https://codesandbox.io/s/milkdown-listener-count-eteqe?file=/src/index.ts

I can only see one update on this case.

**Comment by sytolk** [comment]
I'm using `markdown` not `doc` here:
https://github.com/Saul-Mirone/milkdown/tree/main/packages/plugin-listener#example-usage

**Comment by Saul-Mirone** [comment]
They will be called at the same time, so it's still 2 if I switch to `markdown`

**Comment by sytolk** [comment]
just add `markdown: [(get) => console.log(get())],` and you will see in console `workflow\_dispatch` -> escaped

**Comment by Saul-Mirone** [comment]
Yeah, I see that. But if I remove the underline here to make it as `workflowdispatch`, the render times is still 2.

**Comment by sytolk** [comment]
The question is why markdown content listener is fired with the escaped Markdown content? I'm expecting it will be fired with the user content changes only

**Comment by Saul-Mirone** [comment]
I mean in this demo, if you remove the escaped markdown content, the times listener being called will still be 2, so it's not caused by escape string, at least not in milkdown.

**Comment by sytolk** [comment]
You can try with the `const markdown = `test`;` render will be only 1

**Comment by Saul-Mirone** [comment]
That's because of the image node. If you remove the image node it will also be 1. When image be loaded, it will render so it's 2 here.

**Comment by Saul-Mirone** [comment]
With the prove of this demo. What I'm thinking is that this behavior maybe caused by something not related to milkdown itself.

**Comment by sytolk** [comment]
I can make temp fix for this issue if I you know what characters is escaped ? Do you have an idea

**Comment by Saul-Mirone** [comment]
I really don't know, that's the part handled by [remark](https://github.com/remarkjs/remark).

**Comment by sytolk** [comment]
Summary: this issue happened if its have link in markdown like: `![dropdown mockup](https://www.cbui.dev/github-actions-limitations-and-gotchas/no-dropdowns.png)`
then content change listener will be called one more time and markdown content will be escaped here: `markdown: [(get) => console.log(get())],`

**Comment by Saul-Mirone** [comment]
Yeah, and these two behaviors are all expected and reasonable.

**Comment by sytolk** [comment]
I'm not expect this behaviors :) I'm expecting md content listener to be fired when user type some changes in editor only.  maybe fix for this issue can be done in @milkdown/plugin-listener ?

**Comment by Saul-Mirone** [comment]
I don't think so for 2 reasons:

1. Now the listener will be called if the document changed. If we just watch user typing, we will miss a lot of other cases such as drag and drop or update content programatically. 
2. Calculate the markdown is a very expensive behavior if you have a lot of content in your editor. If we calculate the markdown content every time in a update, it will be not friendly to performance.

I also recommend you to not update markdown content everytime it's been changed. I think it would be better to access the markdown content at the time you need it.

**Comment by sytolk** [comment]
For reason 1. This can be handled better: `source` parameter = [ userChanges , ProgrammaticallyChanged, DnD] 
2. where you see that I have reload markdown on changed? I'm using markdown content listener in iframe to communicate with the parent and let it know that there is not saved changes. But with this issue MD Edited state is appear on MD file loaded. You can try with https://github.com/tagspaces/tagspaces

**Comment by Saul-Mirone** [comment]
```typescript  
const milkdownListener = React.useCallback((getMarkdown: () => string) => {
    updateContent(getMarkdown());
  }, []);
```

I mean it here. It's calculating the markdown from prosemirror state tree everytime.

And as for the reason 1, it's not possible to list all the change scenarios because there are too many.

But, anyway, there's should only at most 2 changes here and should not related to escape characters. It should only about image. I will check your project to see if I can find the root cause.

**Comment by Saul-Mirone** [comment]
So, what you want here is that if user set the content as `workflow_dispatch`, you don't want get notification from listener to make it as `workflow\_dispatch`?

**Comment by Saul-Mirone** [comment]
I think you can do this:

```typescript
    React.useImperativeHandle(ref, () => ({
      update: (markdown: string) => {
       // ...
      },
      isEqualMarkdown: (prev: string, next: string) => {
        if (!editorReady || !editorRef.current) return;
        const editor = editorRef.current.get();
        if (!editor) return;
        return editor.action(ctx => {
          const parser = ctx.get(parserCtx);
          const prevDoc = parser(prev)?.toJSON();
          const nextDoc = parser(next)?.toJSON();
          console.log(JSON.stringify(prevDoc));
          console.log(JSON.stringify(nextDoc));
          return JSON.stringify(prevDoc) === JSON.stringify(nextDoc);
        })
      }
    }));
```

**Comment by sytolk** [comment]
> So, seems the image update won't bother you because you just compare the markdown content. What you want here is that if user set the content as `workflow_dispatch`, you don't want get notification from listener to make it as `workflow\_dispatch`?

Exactly! 

So you idea is to use isEqualMarkdown function to filter false MD content updates from the listener?

**Comment by Saul-Mirone** [comment]
Because we cannot control what character will the remark escape, so why don't we just compare the markdown tree?

**Comment by Saul-Mirone** [comment]
Close for idle
