### ISSUE TITLE
Visual regression on the published website

### ISSUE THREAD

**Issue by echarles** [Saul-Mirone/milkdown#206]
Today my chrome shows strange visuals (on the top left area of the white page) when I change page on the published website https://milkdown.dev/#/why-milkdown. Maybe linked to my env, but pretty sure I did not have that behavior a few days ago.

![Untitled](https://user-images.githubusercontent.com/226720/144858621-0199545a-8182-4b1b-818a-2c0b1ac014a4.gif)

**Comment by Saul-Mirone** [comment]
Thanks for your report, fixed by: https://github.com/Saul-Mirone/milkdown/commit/8830557901bf8e997b4230d8ea934e3295ecabd5
