### ISSUE TITLE
Can it support Table of content？

### ISSUE THREAD

**Issue by wuhaihan** [Saul-Mirone/milkdown#208]
Hope that Table of content can be automatically generated.

**Comment by Saul-Mirone** [comment]
You can get the JSON structure with the listener and you can create something like `toc` with that.

**Comment by snailsdream** [comment]
> You can get the JSON structure with the listener and you can create something like `toc` with that.

then, how do I  link to the title ?

**Comment by Saul-Mirone** [comment]
> > You can get the JSON structure with the listener and you can create something like `toc` with that.
> 
> then, how do I link to the title ?

That need a little bit more works, you need to extend the heading nodes to make it support anchor.

**Comment by snailsdream** [comment]
Thank you，how to extend the node？I can only define a node to overwrite heading nodes

**Comment by Saul-Mirone** [comment]
> Thank you，how to extend the node？I can only define a node to overwrite heading nodes
<img width="1134" alt="Screen Shot 2021-12-10 at 10 20 01 AM" src="https://user-images.githubusercontent.com/10047788/145506421-46464a01-33bc-4101-b940-2d8767b79459.png">

https://milkdown.dev/#/using-utils-package

**Comment by Saul-Mirone** [comment]
If you can create a auto heading plugin, I think a lot of people will love it.

**Comment by snailsdream** [comment]
> https://milkdown.dev/#/using-utils-package
Sorry, I missed it

**Comment by snailsdream** [comment]
> If you can create a auto heading plugin, I think a lot of people will love it.

ok，I'd be happy to

**Comment by snailsdream** [comment]
> If you can create a auto heading plugin, I think a lot of people will love it.

Should I refer to  https://github.com/Saul-Mirone/milkdown/blob/main/CONTRIBUTING.md？

**Comment by Saul-Mirone** [comment]
> > If you can create a auto heading plugin, I think a lot of people will love it.
> 
> Should I refer to [https://github.com/Saul-Mirone/milkdown/blob/main/CONTRIBUTING.md？](https://github.com/Saul-Mirone/milkdown/blob/main/CONTRIBUTING.md%EF%BC%9F)

If you want to open a pull request for milkdown, you may need to.
If you want to keep the plugin like this: https://github.com/songhn233/milkdown-plugin-shiki, then you don't need to.

**Comment by snailsdream** [comment]
> If you want to open a pull request for milkdown, you may need to. If you want to keep the plugin like this: https://github.com/songhn233/milkdown-plugin-shiki, then you don't need to.

After cloning Milkdown, run `pnpm install` to install dependencies.Then I run `pnpm test` it's not passed

```shell
D:\workspace\milkdown\milkdown\packages\vue\src\VueNode.tsx
  2:52  error  Unable to resolve path to module '@milkdown/prose'  import/no-unresolved

D:\workspace\milkdown\milkdown\packages\vue\src\VueNodeView.tsx
  3:28  error  Unable to resolve path to module '@milkdown/prose'  import/no-unresolved

✖ 277 problems (277 errors, 0 warnings)

 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Test failed. See above for more details.
```

**Comment by Saul-Mirone** [comment]
> 

Sorry, I've just merged a new PR and havn't update the CONTRIBUTION.md file.

You need to run `pnpm build:packs` before run `pnpm test` now.
