### ISSUE TITLE
InsertLink

### ISSUE THREAD

**Issue by yuetai-1** [Saul-Mirone/milkdown#210]
I hope you can add a function of inserting links, similar to inserting images

**Comment by Saul-Mirone** [comment]
You can insert links with tooltip plugin, what's the problem?

**Comment by yuetai-1** [comment]
But that feature requires selecting text, and all I need is to click the button to generate a link directly



---Original---
From: ***@***.***&gt;
Date: Thu, Dec 9, 2021 10:18 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Saul-Mirone/milkdown] InsertLink (Issue #210)




 
You can insert links with tooltip plugin, what's the problem?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Saul-Mirone** [comment]
You can write your action to do that.

**Comment by yuetai-1** [comment]
sorry my ability is poor ，I try to do it but I failed



---Original---
From: ***@***.***&gt;
Date: Thu, Dec 9, 2021 10:34 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Saul-Mirone/milkdown] InsertLink (Issue #210)




 
You can write your action to do that.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Saul-Mirone** [comment]
Something like here
https://codesandbox.io/s/milkdown-listener-count-eteqe?file=/src/index.ts

**Comment by zgrybus** [comment]
@yuetai-1 @Saul-Mirone 
May you share it once again?

**Comment by solos** [comment]
The example url https://github.com/Milkdown/milkdown/issues/210#issuecomment-989456678  is broken. I wonder how to insert a link. I just find a toggle link command and update link command. How to insert a link ?

```
this.editor.action((ctx) => {

   const commandManager = ctx.get(commandsCtx);
   commandManager.call(toggleLinkCommand.key, {
       href: link,
       title: name,
   });
 });
```
