### ISSUE TITLE
[Feature] Code grammar adds mental model

### ISSUE THREAD

**Issue by hua1995116** [Saul-Mirone/milkdown#211]
**Is your feature request related to a problem? Please describe.**

Code grammar adds mental model, markdown editor like typora, \``` + Enter will trigger code block, but in milkdown it is \``` + space. 
And if you enter in milkdown
\```
conosle.log('Hello');
\```

It won't render as
```
conosle.log('Hello');
```

**Describe the solution you'd like**

Code grammar like typora、 Github Issues Editor.

**Comment by Saul-Mirone** [comment]
I'll optimize this

**Comment by hua1995116** [comment]
There is also a bug in code inline.

step1: \`
step2: \`d
step3: \`d\`
It's ok.


step1: \`
step2: \`\`
step3: \`d\`
But it doesn't work

**Comment by Saul-Mirone** [comment]
Done by https://github.com/Saul-Mirone/milkdown/commit/dd9fd95e61be6dc200373132025714cfd79bf5e1

As for the code inline. It's not a bug, that's due to the limitation of prosemirror. There's nothing we can do about it.

**Comment by hua1995116** [comment]
great！thx.
