### ISSUE TITLE
[Bug]   Front-matter 解析出错

### ISSUE THREAD

**Issue by zhemima** [Saul-Mirone/milkdown#212]
由于使用了hexo的[fontmatter](https://hexo.io/zh-cn/docs/front-matter)

类似这样的标记
```
---
title: Hello World
---
```
在回车后被解析成了
```
***

## title: Hello World
```
这将会造成markdown文件的一些信息不会被hexo识别

同样的还有`-` 会被解析成`*`

我在想是不是有一个配置,可以保持原来的markdown语法.
如果文件使用git之类的版本控制工具，这会带来意外的更改。

**Comment by Saul-Mirone** [comment]
Front matter本来就不是标准的markdown语法，按照标准的markdown解析器解析会出现问题。

你需要写一个Front-matter语法插件来支持这个行为。

**Comment by zhemima** [comment]
> Front matter本来就不是标准的markdown语法，按照标准的markdown解析器解析会出现问题。
> 
> 你需要写一个Front-matter语法插件来支持这个行为。

不是这个意思..
是它不应该被解析和转换
同样的例如:
`-`会被解析成`*`

是否有一个配置可以保持原来的markdown

**Comment by Saul-Mirone** [comment]
什么东西会被解析和转换也是编译器控制的，milkdown的工作原理：

https://milkdown.dev/#/zh-hans/architecture

所以不存在所谓的“不应该被解析”，而是解析的时候能够保持原信息。

**Comment by zhemima** [comment]
> 什么东西会被解析和转换也是编译器控制的，milkdown的工作原理：
> 
> https://milkdown.dev/#/zh-hans/architecture
> 
> 所以不存在所谓的“不应该被解析”，而是解析的时候能够保持原数据。

对,你说的对.那就是如何能够保持原数据呢?
当我输入 `-`时,而不是获得一个`*`

**Comment by Saul-Mirone** [comment]
> > 什么东西会被解析和转换也是编译器控制的，milkdown的工作原理：
> > https://milkdown.dev/#/zh-hans/architecture
> > 所以不存在所谓的“不应该被解析”，而是解析的时候能够保持原数据。
> 
> 对,你说的对.那就是如何能够保持原数据呢? 当我输入 `-`时,而不是获得一个`*`

1. 保持元数据：

需要编写Remark插件，在解析这部分语法的时候把它转换为一个特殊的AST节点，类似这样：

```typescript
type Node = {
  type: 'keepOrigin';
  data: string;
}
```

2. 输入`-`时不获得`*`：

其实这个问题以前讨论过，由于Remark的限制，目前无法做到输入什么就一定输出什么，最多可以配置成不管输入`*`还是`-`都获得`-`，这也是Remark的设计导致的。

**Comment by zhemima** [comment]
谢谢..我尝试一下

**Comment by Saul-Mirone** [comment]
https://github.com/remarkjs/remark-frontmatter
我看Remark有Frontmatter插件，应该可以帮助到你。

**Comment by zhemima** [comment]
> 

十分感谢
