### ISSUE TITLE
[Bug] Could not load document when there unsupported language in code block

### ISSUE THREAD

**Issue by warmthdawn** [Saul-Mirone/milkdown#214]
**Describe the bug**
When open a document containing code block of unsupported language, it did not show the entire document at all.

**To Reproduce**
Open a document with code block like

```zenscript
val reci = RecipeBuilder.newBuilder();
reci.addAuraInput(3000);
reci.addAuraInput(1000, true);
reci.build();
```

**Expected behavior**
do not highlight code rather than error

**Desktop (please complete the following information):**
-   OS: Windows 11
-   Browser Edge
-   Version 96.0.1054.43

**Comment by warmthdawn** [comment]
emm, the github just formatted the code block，resend with escape

  \```zenscript
  val reci = RecipeBuilder.newBuilder(...);
  reci.addAuraInput(3000);
  reci.addAuraInput(1000, true);
  reci.build();
  \```

**Comment by Saul-Mirone** [comment]
Fixed by https://github.com/Saul-Mirone/milkdown/commit/ab6af7be0d98cada8657931f40d976bb85d1ae8b
