### ISSUE TITLE
[Feature] Will we have Windows Installer or MacOS DWG files?

### ISSUE THREAD

**Issue by richild999** [Saul-Mirone/milkdown#216]
I hope we can have a windows installer or macOS dwg program files 
thank you ！that will make your program more convenient！

**Comment by Saul-Mirone** [comment]
Milkdown is a editor framework, but you're talking about an app. They're totally different thing.
For example, you can use milkdown to build an note app like notion or evernote, or a pure markdown editor like typora.

If you just want to use milkdown to edit markdown files, there is an vscode extension you can use: https://marketplace.visualstudio.com/items?itemName=mirone.milkdown
