### ISSUE TITLE
[Feature]请问怎么获取编辑器内的 doc 啊？

### ISSUE THREAD

**Issue by xukecheng** [Saul-Mirone/milkdown#222]
此时编辑器内还没有改动，所以无法通过 listener 获取数据。想知道有没有其他办法获取？或者提供 Parser 的方法？

**Comment by Saul-Mirone** [comment]
![image](https://user-images.githubusercontent.com/10047788/146541989-b97ed358-2bab-46bc-a409-c53a73882f88.png)
https://milkdown.dev/#/zh-hans/interacting-with-editor
