### ISSUE TITLE
Mermaid diagram in front of the document not recognized as such [Bug]

### ISSUE THREAD

**Issue by uggrock** [Saul-Mirone/milkdown#237]
**To Reproduce**
Open demo page
Clean content
Paste:
```mermaid
 graph TD;
    EditorState-->EditorView;
    EditorView-->DOMEvent;
    DOMEvent1-->Transaction;
    Transaction-->EditorState;
```
Result: no diagram recognized
Add a h1 title 
Diagram appears 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

**Smartphone (please complete the following information):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**

**Comment by liu-jh** [comment]
@Saul-Mirone
现在这个问题好像还存在，图表放在文档的开头会解析成代码块

**Comment by Saul-Mirone** [comment]
> @Saul-Mirone 现在这个问题好像还存在，图表放在文档的开头会解析成代码块

![msedge_NtW5ESScWJ](https://user-images.githubusercontent.com/10047788/149736009-bb96ec6b-ede9-4d87-9c51-c0b40c236e69.gif)

It's not released yet.

**Comment by liu-jh** [comment]
直接编辑没问题，你这样初始化试试
```javascript
let input = "```mermaid\ngraph TD;\n    EditorState-->EditorView;\n    EditorView-->DOMEvent;\n    DOMEvent-->Transaction;\n    Transaction-->EditorState;\n```\n"
ctx.set(defaultValueCtx, input)
```

**Comment by Saul-Mirone** [comment]
> 直接编辑没问题，重新打开文档就会有问题，你这样初始化试试。@Saul-Mirone
> 
> ```js
> let md = "```mermaid\ngraph TD;\n    EditorState-->EditorView;\n    EditorView-->DOMEvent;\n    DOMEvent-->Transaction;\n    Transaction-->EditorState;\n```\n"
> ctx.set(defaultValueCtx, md)
> ```

因为这个fix还没发布

**Comment by liu-jh** [comment]
好的

> > 直接编辑没问题，重新打开文档就会有问题，你这样初始化试试。@Saul-Mirone
> > ```js
> > let md = "```mermaid\ngraph TD;\n    EditorState-->EditorView;\n    EditorView-->DOMEvent;\n    DOMEvent-->Transaction;\n    Transaction-->EditorState;\n```\n"
> > ctx.set(defaultValueCtx, md)
> > ```
> 
> 因为这个fix还没发布

好的
