### ISSUE TITLE
使用Antd时标题文字颜色不正确

### ISSUE THREAD

**Issue by MrWater233** [Saul-Mirone/milkdown#245]
环境：Vue3+Antd+Milkdown
在黑暗模式下，使用Milkdown输入标题的时候，出现了Antd的标题颜色样式覆盖Milkdown标题颜色样式的情况，导致h1文字颜色不能正常显示成白色
截图如下：
![image](https://user-images.githubusercontent.com/45112790/147385465-44722516-d878-4ee8-9841-2e70dcfd50ce.png)
请问这种情况如何解决呢？

**Comment by Saul-Mirone** [comment]
可以考虑手动覆盖一下样式

**Comment by MrWater233** [comment]
> 可以考虑手动覆盖一下样式

感谢作者，已经解决
