### ISSUE TITLE
[Bug] Image link does not scroll with content.

### ISSUE THREAD

**Issue by rancy98** [Saul-Mirone/milkdown#248]
**Describe the bug**
After clicking the picture, the link space area does not scroll with the content area.

**To Reproduce**

1. Upload an image
2. Click on the image
3. Scroll content area and the link space area does not scroll with the content area.

**Expected behavior**
Line space area scroll with the content area

**Screenshots**
![image](https://user-images.githubusercontent.com/43943810/147442569-26e467a0-083d-4d4b-ad9b-f161013d7799.png)

**Comment by Saul-Mirone** [comment]
It's a known issue introduced by the menu plugin, I plan to fix it but I'm looking for a good solution.
