### ISSUE TITLE
怎样粘贴截图后得到的图片

### ISSUE THREAD

**Issue by liu-jh** [Saul-Mirone/milkdown#249]
https://user-images.githubusercontent.com/54222118/147528232-c52721e6-715a-46a7-8c6c-371e58279f1f.mp4

我用了clipboard和upload插件，但只能粘贴从网页上复制的图片，不能像官网一样粘贴截图得到的图片。

**Comment by Saul-Mirone** [comment]
upload插件有这个功能，但还没发布，请等待下个版本（预计本周内

**Comment by liu-jh** [comment]
> upload插件有这个功能，但还没发布，请等待下个版本（预计本周内

好的
