### ISSUE TITLE
[Bug]Can not lock package version in 5.0.0

### ISSUE THREAD

**Issue by leon-kfd** [Saul-Mirone/milkdown#256]
I lock the milkdown version in v5.0.0 in package.json, but after `npm install`, the `@milkdown/design-system` and `@milkdown/exception` will always install in the latest version(v5.3.1 now). 

![image](https://user-images.githubusercontent.com/30256102/147850171-1735f4c1-14e8-4df7-8a08-1b86c6e46f9f.png)

![image](https://user-images.githubusercontent.com/30256102/147850208-f8e9b913-d50c-4082-8b6b-5d42a585d8ae.png)

Then I will get a error in `transformer.ts:5`. Although I think upgrading to the latest version will solve this problem, but i think it need a way to lock version.

![image](https://user-images.githubusercontent.com/30256102/147850287-569487fa-c780-460d-9b6e-2eccb599ea31.png)

**Comment by Saul-Mirone** [comment]
It's fixed by this commit so you can lock it since v5.1
