### ISSUE TITLE
代码块前后区域支持插入光标

### ISSUE THREAD

**Issue by liu-jh** [Saul-Mirone/milkdown#261]
如果代码块在整个文章开头，没法再往前面插入内容，要插入内容的话需要把整个代码块删掉。另外我发现表格前后是能插入光标的，但如果代码块和表格连在一起的话，也会变成插入不了光标。

**Comment by Saul-Mirone** [comment]
代码块插入不了光标是框架限制导致。
不过你也可以把内容拖拽过去。
![AJdaFS3q25](https://user-images.githubusercontent.com/10047788/148002301-9b37e78b-28cc-442d-8111-f46abb963dd1.gif)
