### ISSUE TITLE
[Bug] nextjs + react 项目中使用出现的问题

### ISSUE THREAD

**Issue by dashixiong-11** [Saul-Mirone/milkdown#267]
1.使用next v12 版本后可以正确import依赖了，但是如果刷新当前页面会出现如下报错
![image](https://user-images.githubusercontent.com/39214393/148646425-bc88fec4-2963-4728-a556-b694518c7a14.png)
2.在使用Action获取上下文时候，文档中的 editor 返回值是一个函数而不是对象，
```javascript
import { Editor, editorViewCtx, serializerCtx } from '@milkdown/core';

async function playWithEditor() {
    const editor = await Editor.make().use(commonmark).create();

    const getMarkdown = () =>
       //eidtor = () =>{}, 这边需要改成 editor().action
        editor.action((ctx) => {
            const editorView = ctx.get(editorViewCtx);
            const serializer = ctx.get(serializerCtx);
            return serializer(editorView.state.doc);
        });

    // get markdown string:
    getMarkdown();
}
```
3. 我改成上面这样后，运行报错
![image](https://user-images.githubusercontent.com/39214393/148646622-d4f52a65-c7a5-462c-ae39-3bb4a5ee7032.png)

以下是我的代码
![image](https://user-images.githubusercontent.com/39214393/148646649-d15246a9-1cf4-43b1-9551-3a32ab5857fe.png)

**Comment by Saul-Mirone** [comment]
- 问题1 `dcoument is undefined`:
https://stackoverflow.com/questions/60629258/next-js-document-is-not-defined

- 问题2，react中获取editor的方法应参考：
https://codesandbox.io/s/milkdown-react-update-sdl77
