### ISSUE TITLE
[Feature] Configurable hover menus

### ISSUE THREAD

**Issue by echarles** [Saul-Mirone/milkdown#280]
It would be great to have more configurable hover menus. Last time I have looked at the source code, I had the impression that the menu buttons were not configurable.

<img width="433" alt="Screenshot 2022-01-15 at 08 45 58" src="https://user-images.githubusercontent.com/226720/149614137-24533b62-06dc-45a5-bfaa-3553b56d9049.png">

**Comment by quank123wip** [comment]
@Saul-Mirone Would you mind me try this out? I can make a PR for this for sure.

**Comment by quank123wip** [comment]
@echarles I'm currently working on this. Please give me a more detailed spec about what do you want, for example, configurable icons, configurable button arrangements(I personally don't recommend this), or inserting customized buttons(this should be complicated, user need to handle events).

**Comment by echarles** [comment]
@quank123wip Thx for asking. High level, I would say a list of {icon, proseMirrorCommand} pair would be what I would be searching for. But the real life API may make this more complex that what I think.

In first instance, the API would allow to simply override the existing default setting.

Hope this input helps you.

**Comment by quank123wip** [comment]
> @quank123wip Thx for asking. High level, I would say a list of {icon, proseMirrorCommand} pair would be what I would be searching for. But the real life API may make this more complex that what I think.
> 
> In first instance, the API would allow to simply override the existing default setting.
> 
> Hope this input helps you.

OK, this would require a refactor of this modules. Unfortunately I'm working on an exam now, that I can't give you a brief deadline or due date. I'll try to finish this within 1 month.

**Comment by quank123wip** [comment]
Currently I'm thinking how to do this, but encountered problems. If you want to take over the buttons, how should we determine their status? For example the button icon's color should change with style changes. If we want this fully configurable, then we should expose schema object to user and let them refer them in their config. It's a bit hard to do this simply by letting user give a json object to achieve such a customizability. What do you think? @echarles @Saul-Mirone If you have a better idea or you think this is good enough, mention me anytime.

**Comment by Saul-Mirone** [comment]
> 

We need to maintain a balance between the two, configurable and usable. I don't think we need to make everything can be configured. No one want to write 100 lines of code if all they want is adding a button. Here's the API comes into my mind:
```typescript
import type { Icon } from '@milkdown/design-system';
type Item = {
  // the icon, support design system icon or user provided
  icon: Icon | (ctx: Ctx) => HTMLElement;
  // the command or calllback function called when user click the icon
  onClick: string | (ctx: Ctx) => void;
 
  // check if the button should be hide, for example the schema don't have the mark/node type we need or selection is not a text selection 
  isHidden: (ctx: Ctx) => boolean;

 // check if the button should be active, for example bold button should be actived when in bold text
  isActive: (ctx: Ctx) => boolean;
}
```

**Comment by quank123wip** [comment]
> 

Thanks a lot. That's definitely helpful, same as I think but can't express. Also, I think you have got this in your mind that we should provide buttons now as a object can be imported by user. But for this I can't figure out that we should place them in toolbar plugin or commonmark preset. That could make the code more intergrated.

**Comment by Saul-Mirone** [comment]
@quank123wip Are you working on this?

**Comment by quank123wip** [comment]
> @quank123wip Are you working on this?

I'm about to do this job this week, but if you are willing to work on this, then I'm sorry for slowing down on this, I would find another task to work on.

**Comment by Saul-Mirone** [comment]
> 

I'm just tracking these issues. Feel free to work on this.

**Comment by quank123wip** [comment]
I'm currently working on this right now. I found that currently we already have a strong api creating buttons, but with complexity, here I have a prototype idea which can work with that. Would you mind to have a review on this?

```
export type Item = {
    icon: Icon | ((ctx: Ctx) => HTMLElement);

    onClick: string | ((ctx: Ctx) => () => void);

    isHidden: (ctx: Ctx) => Pred;

    isActive: (ctx: Ctx) => Pred;
};
export type ButtonItem = {
    $: HTMLElement;
    command: () => void;
    active: Pred;
    disable?: Pred;
    enable: Pred;
};
const Buttonize = (item: Item, ctx: Ctx): ButtonItem => ({
    $:
        typeof item.icon === 'function'
            ? item.icon(ctx)
            : (ctx.get(themeManagerCtx).get(ThemeIcon, item.icon)?.dom as HTMLElement),
    command: typeof item.onClick === 'function' ? item.onClick(ctx) : ctx.get(commandsCtx).callByName(item.onClick),
    disable: item.isHidden(ctx),
    active: item.isActive(ctx),
    enable: (view: EditorView) => !item.isHidden(ctx)(view),
});
```

I don't have any idea if this works well, the command part is conflicting with the logics now.

**Comment by Saul-Mirone** [comment]
https://github.com/Saul-Mirone/milkdown/pull/458
