### ISSUE TITLE
[Feature] Show correct state/marks on hover menu

### ISSUE THREAD

**Issue by echarles** [Saul-Mirone/milkdown#281]
The hover menu does not reflect the selection marks as the main menu does. For example, if the selected text is bolded, the menu B button is selected, whereas the hover menu does not reflect that.

<img width="500" alt="Screenshot 2022-01-15 at 08 47 55" src="https://user-images.githubusercontent.com/226720/149614194-c0395cee-f642-428a-9693-e0b170913ca1.png">

**Comment by Saul-Mirone** [comment]
It has a highlight on it's icon color, did you notice that?

**Comment by echarles** [comment]
No, I don't see the diff. I may be color blind in some ranges...

A darker background like the main menu would make it more clear imho.

**Comment by Saul-Mirone** [comment]
It's decided by our designer so I need to discuss with her. You can also customize the active style using css. The actived icon has a `.active` class name on it.
![Screen Shot 2022-01-15 at 4 46 35 PM](https://user-images.githubusercontent.com/10047788/149615778-149583c0-bbbe-4213-9a2d-bf279fa7f636.png)

**Comment by duhaime** [comment]
I think what @echarles means is that the hover state and active state of buttons in the menu are identical, which makes it hard to determine if a button is active. I also think this is the case. 

It's easy enough to add something like:

```
.icon:hover {
  opacity: 0.7;
}
```

to fix this
