### ISSUE TITLE
Provide more cases in example

### ISSUE THREAD

**Issue by Saul-Mirone** [Saul-Mirone/milkdown#288]

**Comment by Saul-Mirone** [comment]
https://github.com/Saul-Mirone/milkdown/discussions/178

**Comment by Saul-Mirone** [comment]
https://github.com/Saul-Mirone/milkdown/discussions/349

**Comment by Saul-Mirone** [comment]
https://github.com/Saul-Mirone/milkdown/discussions/409

**Comment by guluguru** [comment]
Hello, Since a lot of docs is misssing in [zh-hans-docs](https://milkdown.dev/zh-hans/), is there any plan to fill zh-CN documents?

If it needs, I'm glad to help to translate to zh.

**Comment by Saul-Mirone** [comment]
I'm working on it and I think will be finished within this week.
