### ISSUE TITLE
[Feature] Allow Menu to be inserted separately from Editor body

### ISSUE THREAD

**Issue by andrewmee** [Saul-Mirone/milkdown#290]
**Is your feature request related to a problem? Please describe.**
I have a design that requires the menu to be inserted into a part of my interface (in the page header) that's apart from the main Editor body.

**Describe the solution you'd like**
Rather than `Editor.make()` returning a single combined node with both the menu and the contenteditable body, perhaps it could return a object `Editor.make().menu` and `Editor.make().body`?  Or maybe this alternate return structure could be opted in to with some new config value if we don't want to make the default behaviour more complex for users.

**Comment by Saul-Mirone** [comment]
An option to pass in a function to menu plugin seems make sense to me

**Comment by andrewmee** [comment]
This is great, thanks very much!
