### ISSUE TITLE
[Bug] How to escape from code block at end of document?

### ISSUE THREAD

**Issue by duhaime** [Saul-Mirone/milkdown#296]
**Describe the bug**
On the demo page, if one navigates to the bottom of the document and inserts a codeblock with ```, neither the down arrow nor the enter key allow one to exit the block.

I know one can add a block below the codeblock to allow the keyboard to escape the codeblock, but is it possible to escape the codeblock with the arrow keys if there's nothing below the code block?

**To Reproduce**
See above

**Expected behavior**
I'd expect the down arrow to exit the cursor from the block (as is the case if the code block is not the terminal block in the document)

**Desktop (please complete the following information):**

-   OS: macOS Monterey 
-   Browser: recent Chrome

**Comment by Saul-Mirone** [comment]
`Mod(Cmd for Mac/Ctrl for others) + Enter`

**Comment by duhaime** [comment]
@Saul-Mirone this library is truly outstanding. I've been looking into rich text editors the last few days, and this is head and shoulders above the others I surveyed. Great work to you and Meo 🥇
