### ISSUE TITLE
[Bug] Slash menu text appears under images

### ISSUE THREAD

**Issue by prncc** [Saul-Mirone/milkdown#297]
**Describe the bug**

The slash menu text (e.g., "Type / to use the slash commands...") is visible under images, if the image is selected or the cursor is before the image.

**To Reproduce**

1. Go to https://milkdown.dev/online-demo
2. Remove all text
3. Paste in any image
4. Place cursor before the image or select the image

**Expected behavior**

The slash menu is not present when the cursor is on the same line as the image (that's consistent with how text appears).

**Screenshots**

![image](https://user-images.githubusercontent.com/1467751/150698722-6208248e-00e6-4850-8297-a200537a7e09.png)

**Desktop (please complete the following information):**

-   OS: Linux
-   Browser Chrome
-   Version 95

**Additional context**

Not sure if this is intended, but images appear inside the "empty-node" that represents the menu, like this

![image](https://user-images.githubusercontent.com/1467751/150698790-4df8b289-a6f1-441a-9670-bc7a9307d9d0.png)

In my app, I toggle the editor between read-only and editable modes. In the read-only case, I also hide empty-nodes to hide the slash command. So this effectively hides my images when clicked (or when they are the only content in the editor). [I have an easy solution, but thought this info might be useful anyway.]

**Comment by Saul-Mirone** [comment]
I think it is already fixed in https://github.com/Saul-Mirone/milkdown/commit/dbf7de0c465f83899c9e2846a02953c6fceda4c2.

It's not been released yet, but the oneline demo should work right now.
Do you still have this issue in online demo?

**Comment by Saul-Mirone** [comment]
I believe it already been fixed after my double check. Feel free to reopen if you think it's still there.

**Comment by duhaime** [comment]
@Saul-Mirone do you have any sense of when the next release will come? It'd be great to have these patches if you have time :)

**Comment by Saul-Mirone** [comment]
> @Saul-Mirone do you have any sense of when the next release will come? It'd be great to have these patches if you have time :) 

Today

**Comment by prncc** [comment]
Awesome, the bug is gone. Thanks!
