### ISSUE TITLE
[Bug] Only part of the pasted text gets placed into code block

### ISSUE THREAD

**Issue by prncc** [Saul-Mirone/milkdown#302]
**Describe the bug**

Pasting certain text into a new \`\`\` code block can lead to only part of the pasted text appearing in the code block. 

**To Reproduce**

1. Go to the online editor.
2. Erase everything.
3. Create a new code block with \`\`\`
4. Paste the following (this is just the first few lines of `history`)

```
    1  networkctl 
    2  networkctl wlan0 up
    3  reboot
    4  yay -S chrome
    5  yay -Ss google-chrome
    6  yay -S google-chrome
    7  yay -Ss refind
    8  yay -Ss grub
    9  sudo yay -Syu
   10  sudo pacman -S grub-tools grub os-prober
   11  sudo grub-mkconfig -o /boot/grub/grub.cfg 
   12  reboot
   13  test -d /sys/firmware/efi 
   14  efibootmgr -v
   15  efibootmgr 
```

**Expected behavior**

All the code is in the code block.

**Screenshots**

_Actual_

![image](https://user-images.githubusercontent.com/1467751/150904788-400f4b99-38c2-410f-b7de-d0bc10343d5d.png)

_Expected_

![image](https://user-images.githubusercontent.com/1467751/150906414-4acf11b4-d1b8-46c5-bbba-cc695c27be58.png)

(manually edited)

**Desktop (please complete the following information):**

-   OS: Linux
-   Browser Chrome
-   Version 95

**Additional context**

The numbers in the text pasted above are right-aligned, and since the editor is space based, the change in indentation  causes some of the text to appear after the code block in the rendered code.

**Comment by Saul-Mirone** [comment]
It's caused by if you enter tree spaces at the start of the line, it's some kind of markdown syntax so it will be parsed as a standalone code block. I'll disable the parse when paste in code block.
