### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by shiyiya** [Saul-Mirone/milkdown#303]
**break change**？ ^version  https://semver.org/lang/zh-CN/
![image](https://user-images.githubusercontent.com/34017352/150971932-ce475ab4-dac1-4b8f-9678-e0bd7e19506f.png)

emotion.injectGlobal not working.
![image](https://user-images.githubusercontent.com/34017352/150975377-055d44b4-273d-4a85-a655-995a6d8e2af2.png)

@milkdown/preset-gfm
![image](https://user-images.githubusercontent.com/34017352/150975560-f822d698-c369-4c3e-8fe8-5ff2b53ee450.png)

**Comment by Saul-Mirone** [comment]
What bug? Can you provide more information?

**Comment by shiyiya** [comment]
- https://codesandbox.io/s/milkdown-theme-nes-forked-semnj?file=/src/index.ts

**Comment by Saul-Mirone** [comment]
I notice 2 errors in this code sand box:

1. You use `theme-nord` behind some plugins, which you should use `theme` in front of other plugins.
2. You use both `preset-commonmark` and `preset-gfm`. However, gfm already includes the commonmark so you should only import one of them.

Here is a modified one to make it works:

https://codesandbox.io/s/milkdown-theme-nes-forked-oltik?file=/src/index.ts

**Comment by shiyiya** [comment]
👍
