### ISSUE TITLE
[Bug] Slash menu text appears under hourglass when uploading image

### ISSUE THREAD

**Issue by duhaime** [Saul-Mirone/milkdown#304]
**Describe the bug**
If a user drops a large image in the demo (or the user has an upload callback that takes time to run), you can see the slash menu below the hourglass:

<img width="1067" alt="Screen Shot 2022-01-25 at 8 00 50 PM" src="https://user-images.githubusercontent.com/4801116/151085408-42e486a5-0f19-4c0e-9650-7f4e8cddc6fc.png">

Possibly related to https://github.com/Saul-Mirone/milkdown/issues/297

**To Reproduce**

1. Go to [the demo](https://milkdown.dev/online-demo)
2. Drag [this image](https://upload.wikimedia.org/wikipedia/commons/2/2d/Snake_River_%285mb%29.jpg) onto the screen (or any other huge image)
3. Behold the overlap

**Expected behavior**
It would be best if the slash menu disappeared at the same time the hourglass appeared

**Desktop (please complete the following information):**

-   OS: Monterey
-   Browser Chrome (recent)

**Comment by Saul-Mirone** [comment]
It's a little complicated compare to that one, but I think I can find a solution.
