### ISSUE TITLE
[Bug] Setting editor state with ref 

### ISSUE THREAD

**Issue by duhaime** [Saul-Mirone/milkdown#306]
**Describe the bug**
This is almost certainly user error. I'm trying to programmatically set the editor state using the ref syntax from [this thread](https://github.com/Saul-Mirone/milkdown/issues/127#issuecomment-919343853) but my pen is bombing: https://codesandbox.io/s/milkdown-react-setup-forked-e713g?file=/src/App.js

**To Reproduce**

1. Go to [this codesandbox](https://codesandbox.io/s/milkdown-react-setup-forked-e713g?file=/src/App.js)
2. Click on the digit "3"
3. See the console explode

**Expected behavior**
I'd like to set the editor using the count variable--how can this be achieved?

**Comment by Saul-Mirone** [comment]
Change the line 35 to

```javascript
// Make sure it's a markdown string, not other things, that's why I love typescript
const doc = parser(count.toString());
```

**Comment by duhaime** [comment]
Thank you @Saul-Mirone!
