### ISSUE TITLE
[Bug] @milkdown/plugin-math is required for @milkdown/plugin-tooltip ？

### ISSUE THREAD

**Issue by shiyiya** [Saul-Mirone/milkdown#307]
![image](https://user-images.githubusercontent.com/34017352/151292703-9b344345-e455-485e-ad20-9e7a595d3005.png)

- I want @milkdown/plugin-tooltip . do I need to install @milkdown/plugin-math? Is this wrong?  

![image](https://user-images.githubusercontent.com/34017352/151293633-3935b116-94ce-4b32-b4ee-f3cccc36c1d8.png)

![image](https://user-images.githubusercontent.com/34017352/151293371-f80e6b7f-db2a-41ee-a0b6-263d2c6efafa.png)

Are they interdependent?   

- https://github.com/Saul-Mirone/milkdown/blob/main/packages/plugin-math/src/math-inline/index.ts#L15
- https://github.com/Saul-Mirone/milkdown/blob/main/packages/plugin-tooltip/src/utility/input.ts#L43

**Comment by Saul-Mirone** [comment]
They have some relationship. The tooltip input component supports to modify value of inline math. But put it as a dependency doesn't make sense to me.
There's a PR to improve this, but it's still being tested: https://github.com/Saul-Mirone/milkdown/pull/301

**Comment by shiyiya** [comment]
https://github.com/Saul-Mirone/milkdown/blob/main/packages/preset-gfm/package.json#L34

Maybe `@milkdown/preset-gfm` is a separate plugin and should depend on `dependencies` here instead of `peerdependencies`?

**Comment by shiyiya** [comment]
![image](https://user-images.githubusercontent.com/34017352/151509921-a8bd9278-ec67-4614-970e-7bce72dd2d5f.png)

- The dependency was removed but it is used in the code, did you forget?
https://github.com/Saul-Mirone/milkdown/blob/main/packages/plugin-tooltip/src/utility/input.ts#L3

**Comment by Saul-Mirone** [comment]
> 

I'm working on a feature to make it not a dependency. I think user has to install @milkdown/plugin-math when using @milkdown/plugin-tooltip even though they don't need it doesn't make sense now.

**Comment by shiyiya** [comment]
why need math？🤔

**Comment by Saul-Mirone** [comment]
For now, the plugin tooltip can support modify inline math. So it needs to use command keys defined in math plugin. That's why it needs to install math plugin. I want it to be optional.

**Comment by shiyiya** [comment]
I got it.

**Comment by shiyiya** [comment]
I found the following unreasonable (in my opinion).
- slash depends on tooltip, tooltip depends on math. when I only need slash, I need to install three dependencies.

![image](https://user-images.githubusercontent.com/34017352/151647782-24b82bd2-003a-4a1a-86ff-a25116933031.png)

- `code` `table` state. https://codesandbox.io/s/milkdown-theme-nes-forked-semnj?file=/src/index.ts

**Comment by Saul-Mirone** [comment]
1. Slash doesn't dependes on tooltip. And since 5.4.1 you don't need install them all anymore.
2. Use `Ctrl/Cmd + Enter` to quit the code block.

**Comment by shiyiya** [comment]
but now, clicking image placeholder will not pop up the tooltip of the input link.

https://codesandbox.io/s/milkdown-theme-nes-forked-semnj?file=/src/index.ts:712-754

**Comment by Saul-Mirone** [comment]
1. The image input function is part of the tooltip plugin. If you remove it of course it cannot work.
2. Use selection button in menu plugin (or something like that) and drag & drop the code block.
