### ISSUE TITLE
[Feature] Version migration guides

### ISSUE THREAD

**Issue by gcaptn** [Saul-Mirone/milkdown#318]
In a lot of cases migrating to a new milkdown **minor** version breaks my code. I have to dig really deep myself through the docs to find out which API changed. This takes up a lot of uneccessary maintenance effort and for me, it's a blocker from using milkdown in newer projects.

You should consider making a migration guide before releasing any breaking changes — it would really help the developer experience. And if you're using [semver](https://semver.org/#if-even-the-tiniest-backwards-incompatible-changes-to-the-public-api-require-a-major-version-bump-wont-i-end-up-at-version-4200-very-rapidly), you should also consider incrementing the major version for every breaking change.

**Comment by gcaptn** [comment]
> Thanks, I'll take care of the breaking changes. BTW, what breaks your code this time?

Upgrading from 5.2.1 to the latest version gives me this error:

```
TypeError: createThemePack is not a function
    at theme.ts:32:31
    at async Promise.all (:3000/index 0)
    at async _Editor.create (editor.ts:86:35)
```

**Comment by v1r0x** [comment]
I get the same error when switching from Nord theme to a self-made theme. I'm new to Milkdown, so I can't say if this is related to an update.

btw: very nice editor :tada:
