### ISSUE TITLE
[Feature] Create placeholder text for entire editor

### ISSUE THREAD

**Issue by duhaime** [Saul-Mirone/milkdown#319]
**Is your feature request related to a problem? Please describe.**
Can one currently provide placeholder text that will disappear once the editor has any user-provided text?

I thought one could hack this into place by providing a placeholder value to the slash plugin and only showing the ::before content in the placeholder node if it's a child of the first paragraph in the editor and the paragraph is empty. But in that case a user can enter text in the second paragraph, up arrow to the first paragraph, then see the placeholder text.

**Describe the solution you'd like**
Ideally, there would be a plugin that would display placeholder text if the editor did not have any user-provided content.

**Comment by duhaime** [comment]
Oh cool, there's an `:only-child` selector, so we can do:

```
.editor .paragraph.empty-node::before {
  display: none;
}

.editor .paragraph.empty-node:only-child::before {
  display: block;
}
```

**Comment by duhaime** [comment]
It could still be neat to provide a plugin to accomplish this without a hack though :)

**Comment by Saul-Mirone** [comment]
> It could still be neat to provide a plugin to accomplish this without a hack though :)

I think it's not complicated. Welcome to build it as a commercial plugin 😃 . Like https://github.com/songhn233/milkdown-plugin-shiki

**Comment by HexMox** [comment]
Is this ok? @Saul-Mirone 

https://github.com/HexMox/milkdown-plugin-placeholder

> > It could still be neat to provide a plugin to accomplish this without a hack though :)
> 
> I think it's not complicated. Welcome to build it as a commercial plugin 😃 . Like https://github.com/songhn233/milkdown-plugin-shiki

**Comment by kasem-sm** [comment]
The placeholder plugin doesn't seems to work. Am I missing something 😅

**Comment by knownasilya** [comment]
Looks like this plugin no longer works for v7. This should be part of core

**Comment by knownasilya** [comment]
@Saul-Mirone anything that needs changing to make this work for v7? https://github.com/HexMox/milkdown-plugin-placeholder/blob/main/src/index.ts
