### ISSUE TITLE
[Bug]中文标题的拼音输入法似乎有问题

### ISSUE THREAD

**Issue by stan12138** [Saul-Mirone/milkdown#326]
**Describe the bug**
版本：5.4.1

首先输入##，然后回车，切换中文拼音输入法，在拼音输入中，显示正常：
![image](https://user-images.githubusercontent.com/20102702/151707995-6d7195eb-1a82-49ec-be39-83b508d280e6.png)
然后点击数字键选择中文文字，显示的内容却依旧是拼音：
![image](https://user-images.githubusercontent.com/20102702/151708055-c0e8c1b9-e78b-48c8-947e-ca2744d47235.png)

**Comment by Saul-Mirone** [comment]
https://user-images.githubusercontent.com/10047788/151708582-7112d19e-c2e5-4c72-907f-694c2b8092cf.mov

**Comment by Saul-Mirone** [comment]
已经修复了，但是一直没发布

**Comment by stan12138** [comment]
好的，非常感谢回答！请问会在下一个版本发布吗？

**Comment by Saul-Mirone** [comment]
会的
