### ISSUE TITLE
[Bug] Selections made with hotkeys and cursor produce different UI states

### ISSUE THREAD

**Issue by duhaime** [Saul-Mirone/milkdown#334]
**Describe the bug**
This behavior strikes me as a bug, but perhaps I'm overlooking something.

In the current demo, if one types a word then uses the keyboard to select all text, the heading item disappears from the menu. However, if one selects all the text with the mouse, the heading item remains in the menu:

![output](https://user-images.githubusercontent.com/4801116/151859085-cf1bec11-8bc0-429e-b15a-c32633916102.gif)

**To Reproduce**

1. Go to [the demo](https://milkdown.dev/online-demo)
2. Type a word
3. Select with mouse (header item is available in menu)
4. Select with hotkeys (header item in menu is unavailable)

**Expected behavior**
I would expect both selections to produce the same view state (I think the heading item should be available in both cases)

**Comment by quank123wip** [comment]
I had a quick insight into this problem.

If you use shift+arrows to select, the bug doesn't occur. But if you use Ctrl+A this problem occured.

It's related to the default config, but I don't understand how disable event works. I will keep working on it, mention you later.

**Comment by Saul-Mirone** [comment]
Yeah. When use select all it means select the whole documents in prosemirror so it's not entirely equal to select heading node. If we want to solve this we do need some workaround, such as check if heading node is the only node in document.

**Comment by quank123wip** [comment]
> Yeah. When use select all it means select the whole documents in prosemirror so it's not entirely equal to select heading node. If we want to solve this we do need some workaround, such as check if heading node is the only node in document.

Sorry, but IMO, just check this is not enough, because in practical situation, maybe the document includes not only one node, but include serveral text nodes.

**Comment by duhaime** [comment]
Stalebot should only close tickets that are awaiting end user feedback imo

**Comment by quank123wip** [comment]
Leave this issue open please. This indicated a individual problem.
