### ISSUE TITLE
[Bug] Trouble deleting mermaid diagram on iOS

### ISSUE THREAD

**Issue by duhaime** [Saul-Mirone/milkdown#339]
**Describe the bug**
I thought hitting backspace from the end of the demo document would delete the mermaid diagram on iOS, but the cursor gets kind of trapped such that additional backspace keydown events don't delete the diagram:

https://user-images.githubusercontent.com/4801116/152169147-8b2e97a8-8dc5-42cd-8e8f-20c0b2b66b4c.MP4

**To Reproduce**

1. Visit the [demo](https://milkdown.dev/online-demo) on iOS
2. Try to delete the mermaid diagram

**Expected Behavior**

I thought repeatedly hitting the backspace character would delete the diagram

**Comment by Saul-Mirone** [comment]
You can touch on the rendered part and press backspace to delete it.

**Comment by duhaime** [comment]
Ah, sounds good!

**Comment by Saul-Mirone** [comment]
BTW, same with math block.

**Comment by Saul-Mirone** [comment]
I'll close this. Feel free to reopen if you have furthur questions.
