### ISSUE TITLE
[Bug] New line between list items in resulting Markdown string

### ISSUE THREAD

**Issue by v1r0x** [Saul-Mirone/milkdown#343]
**Describe the bug**
When creating a new list (bullet, ordered, ...) and adding items to it, the resulting string has empty lines between them. This leads to unexpected results when rendered as HTML (tested with Laravel's Markdown helper and markdown-it)

**To Reproduce**

1. Add a markdown listener to the editor
2. Start a new list (e.g. typing `- Hello World`)
3. Hit return and add another item
4. Check resulting markdown code in listener
5. A new line is added after every line

**What I type**
```javascript
# Unordered List with new lines
*   Hello
*   Hello again!
*   Hello World!
```
**What I get**
```javascript
# Unordered List with new lines

*   Hello
 
*   Hello again!

*   Hello World!

```
**What I get in HTML** (`<p>` tags ar unnecessary)
```html
<ul>
<li>
<p>Hello</p>
</li>
<li>
<p>Hello again!</p>
</li>
<li>
<p>Hello World!</p>
</li>
</ul>
```

**Expected behavior**
Lists should not contain empty lines between the items. Otherwise a markdown to html parser adds a wrapping element (in my case a `<p>`) which leads to poor results

**Screenshots**
**Rendered HTML**
![Bildschirmfoto von 2022-02-04 11-35-10](https://user-images.githubusercontent.com/9248714/152514795-d716f717-42b2-4225-a3a6-595bc70833c6.png)
**Edited rendered HTML without `<p>`**
![Bildschirmfoto von 2022-02-04 11-35-38](https://user-images.githubusercontent.com/9248714/152514916-18282406-16a1-4ba3-a342-5d371e2e650f.png)

**Desktop (please complete the following information):**

-   OS: Ubuntu 20.04 LTS
-   Browser: Firefox Beta
-   Version: 97

**Additional context**

**Comment by Saul-Mirone** [comment]
That's related to the behavior of remark itself:
https://github.com/remarkjs/remark/issues/563

**Comment by v1r0x** [comment]
Thanks for the link! I somehow missed that while searching for a solution...

My current workaround is to add a class to the wrapper element around my converted html and display paragraphs inside lists as inline element

```html
style {
    .from-milkdown li > p {
        display: inline !important;
    }
}
<!-- ... -->
<div class="from-milkdown">
    {{ Str::markdown($markdownStr) }}
</div>
```

**Comment by Saul-Mirone** [comment]
Seems this package can help, but we need to wrap it as a remark plugin.

https://www.npmjs.com/package/mdast-flatten-listitem-paragraphs

**Comment by quank123wip** [comment]
> Seems this package can help, but we need to wrap it as a remark plugin.
> 
> https://www.npmjs.com/package/mdast-flatten-listitem-paragraphs

I'm trying to do this, but it needs time.

Also, it's a expected behavior in gfm standard but not commonmark standard. In that case, I should integrate this feature into preset-gfm package, right?

**Comment by Saul-Mirone** [comment]
> > Seems this package can help, but we need to wrap it as a remark plugin.
> > https://www.npmjs.com/package/mdast-flatten-listitem-paragraphs
> 
> I'm trying to do this, but it needs time.
> 
> Also, it's a expected behavior in gfm standard but not commonmark standard. In that case, I should integrate this feature into preset-gfm package, right?

I think we can integrate it in commonmark because most people expect there's no newline break IMO.

**Comment by quank123wip** [comment]
I'm a bit of confused now. I tried render markdown in a simple remark instance like [this](https://codesandbox.io/s/cocky-wozniak-f0w7eg?file=/src/index.js:294-314). But I got no paragraphs in list item blocks. Is this really caused by remark?

**Comment by Saul-Mirone** [comment]
> I'm a bit of confused now. I tried render markdown in a simple remark instance like [this](https://codesandbox.io/s/cocky-wozniak-f0w7eg?file=/src/index.js:294-314). But I got no paragraphs in list item blocks. Is this really caused by remark?

That's not really a simple one. The `html` module will do the trick for remark. However, you need to look deep into the AST. Like this: https://codesandbox.io/s/jolly-galileo-d7lyjd

You can see there is a paragraph in the list item.
![image](https://user-images.githubusercontent.com/10047788/155865037-691faf59-c811-4788-bf4e-b23fb34110ae.png)

**Comment by quank123wip** [comment]
> > I'm a bit of confused now. I tried render markdown in a simple remark instance like [this](https://codesandbox.io/s/cocky-wozniak-f0w7eg?file=/src/index.js:294-314). But I got no paragraphs in list item blocks. Is this really caused by remark?
> 
> That's not really a simple one. The `html` module will do the trick for remark. However, you need to look deep into the AST. Like this: https://codesandbox.io/s/jolly-galileo-d7lyjd
> 
> You can see there is a paragraph in the list item. ![image](https://user-images.githubusercontent.com/10047788/155865037-691faf59-c811-4788-bf4e-b23fb34110ae.png)

I have tried to write a plugin since few days ago, but unfortunately I can't get visit working at all, most of the time the attrs which plugin get is undefined. I'm a little confused on this. But one thing is clear, I think that remark is working under unified standard, and unified & mdast & remark plugins should be working directly on remark. They all seems do a similar job but naming on there workspace.

**Comment by Saul-Mirone** [comment]
> > > I'm a bit of confused now. I tried render markdown in a simple remark instance like [this](https://codesandbox.io/s/cocky-wozniak-f0w7eg?file=/src/index.js:294-314). But I got no paragraphs in list item blocks. Is this really caused by remark?
> 
> > 
> 
> > That's not really a simple one. The `html` module will do the trick for remark. However, you need to look deep into the AST. Like this: https://codesandbox.io/s/jolly-galileo-d7lyjd
> 
> > 
> 
> > You can see there is a paragraph in the list item. ![image](https://user-images.githubusercontent.com/10047788/155865037-691faf59-c811-4788-bf4e-b23fb34110ae.png)
> 
> 
> 
> I have tried to write a plugin since few days ago, but unfortunately I can't get visit working at all, most of the time the attrs which plugin get is undefined. I'm a little confused on this. But one thing is clear, I think that remark is working under unified standard, and unified & mdast & remark plugins should be working directly on remark. They all seems do a similar job but naming on there workspace.

Yeah, a remark plugin can be just a wrapper of a mdast plugin

**Comment by Saul-Mirone** [comment]
Add to planned since @quank123wip  is working on this.

**Comment by quank123wip** [comment]
Got stucked again but I would still keep on trying to solve it by myself. The last time I tried write a plugin but the plugin is not running inside that. Then I tried to use remark.process(), and luckily it runs. It seems like a different behavior between parse and process, and a remark plugin should run only when there calls process. What does milkdown actually requires now, a mdast or rendered HTML. I prefer to assume it's a mdast. I will read more milkdown codebase but it needs more time. Hope that won't cause you slow down or bothered by me.

**Comment by quank123wip** [comment]
> Add to planned since @quank123wip is working on this.

Check [this](https://stackblitz.com/edit/js-5gax9h) out ✨

I think we need a post processor for ast?

**Comment by Saul-Mirone** [comment]
Since we're working on the v6 version. I think we can use `unidied`, but we should make sure the output of the entire `parse` process is still the AST tree.

**Comment by quank123wip** [comment]
> Since we're working on the v6 version. I think we can use `unidied`, but we should make sure the output of the entire `parse` process is still the AST.

Yes, as ```remark```'s definition is simply ```unified().use(remarkParse).use(remarkStringify).freeze()```, this won't be hard, and it will give us a chance to customize remark-parse and remark-stringnify's behavior. For example, I have made an [example](https://stackblitz.com/edit/js-hg67nj) showing how to solve this issue by just one unified instance.

**Comment by quank123wip** [comment]
I'm working on a refactor now. My idea is replace the remark() in transformer with unified() instance, than use remarkParse and remarkStringify in preset-commonmark and preset-gfm. But here comes a conflict: If we configured remarkParse in commonmark, how can we configure them in gfm or other presets? Here I have two ideas: make mdast plugin can be managed explicitly by a separate way, or move these two plugins into a separate plugin list, any preset shoulde define them and merge them into their config themselves. What do you think? 🙏

**Comment by Saul-Mirone** [comment]
Can we use remarkParser and remarkStringify in the transformer module? I'm not sure the reason that we need to define them for different presets.

**Comment by quank123wip** [comment]
> Can we use remarkParser and remarkStringify in the transformer module? I'm not sure the reason that we need to define them for different presets. Can you help me to understand this?

IMO, it seems the simplest way to provide a method for applying changes on mdast, not only for [mdast-flatten-listitem-paragraphs](https://gitlab.com/staltz/mdast-flatten-listitem-paragraphs). In fact it seems like the preset in remark-rehype have
done much more then I expected. Commonmark standard and GFM standard are two different standards, contains differences like whether we should provide listitems without paragraph inside or not. Their differences may cause unknown issues in other applications. And we don't know if there is a new markdown standard in the future. My opinion is to keep their original flavor in preset packages, and extend them with our own milkdown-standard plugins, that may cause less conflicts. What do you think about this? 😋

**Comment by Saul-Mirone** [comment]
> > Can we use remarkParser and remarkStringify in the transformer module? I'm not sure the reason that we need to define them for different presets. Can you help me to understand this?
> 
> IMO, it seems the simplest way to provide a method for applying changes on mdast, not only for [mdast-flatten-listitem-paragraphs](https://gitlab.com/staltz/mdast-flatten-listitem-paragraphs). In fact it seems like the preset in remark-rehype have done much more then I expected. Commonmark standard and GFM standard are two different standards, contains differences like whether we should provide listitems without paragraph inside or not. Their differences may cause unknown issues in other applications. And we don't know if there is a new markdown standard in the future. My opinion is to keep their original flavor in preset packages, and extend them with our own milkdown-standard plugins, that may cause less conflicts. What do you think about this? 😋

I'm still a little confused by this. For now, the milkdown editor pick up the AST generated by reamrk, and use them to create prosemirror state. But IMO remark-rehype generates HTML, how can we keep our workflow? Do you mean we need to create prosemirror state from html string?

**Comment by quank123wip** [comment]
> > > Can we use remarkParser and remarkStringify in the transformer module? I'm not sure the reason that we need to define them for different presets. Can you help me to understand this?
> > 
> > IMO, it seems the simplest way to provide a method for applying changes on mdast, not only for [mdast-flatten-listitem-paragraphs](https://gitlab.com/staltz/mdast-flatten-listitem-paragraphs). In fact it seems like the preset in remark-rehype have done much more then I expected. Commonmark standard and GFM standard are two different standards, contains differences like whether we should provide listitems without paragraph inside or not. Their differences may cause unknown issues in other applications. And we don't know if there is a new markdown standard in the future. My opinion is to keep their original flavor in preset packages, and extend them with our own milkdown-standard plugins, that may cause less conflicts. What do you think about this? 😋
> 
> I'm still a little confused by this. For now, the milkdown editor pick up the AST generated by reamrk, and use them to create prosemirror state. But IMO remark-rehype generates HTML, how can we keep our workflow? Do you mean we need to create prosemirror state from html string?

Sorry for my misdirection😢, I means if we want to implement a similar output as remark-rehype, we may need more ast jobs.

**Comment by Saul-Mirone** [comment]
I think it may not that complicated because we do can apply changes to AST now with remark plugins. In fact, IMO the remark plugin is just a wrapper of mdast plugin. I created a simple demo for this: https://codesandbox.io/s/milkdown-compact-list-item-2ifbmg?file=/src/index.ts

As for the standards difference you mentioned. I think it should always decided by nodes and marks. For example, if you find list item has many differences between gfm and commonmark, we can just create two differenct list item nodes.

**Comment by yuri2peter** [comment]
@Saul-Mirone 

Sorry to rehash this issue from a few years ago, I'm trying to integrate crepe 7.14 into my project with the same "extra blank lines" issue in its list. I don't really understand the underlying concept of the editor, is there any way to fix it?

**Comment by Saul-Mirone** [comment]
@yuri2peter 
There's no way in the editor to fix it. But you can pipe the markdown you get from the editor to a formatter like prettier.

For example

```ts
let markdown = getMarkdown(editor);
markdown = prettier(markdown)
```

**Comment by yuri2peter** [comment]
> [@yuri2peter](https://github.com/yuri2peter) There's no way in the editor to fix it. But you can pipe the markdown you get from the editor to a formatter like prettier.
> 
> For example
> 
> let markdown = getMarkdown(editor);
> markdown = prettier(markdown)

That sounds like a viable solution, thanks for the point

**Comment by arthur5005** [comment]
I will say, stuff like this makes it very hard to adopt this as a reliable markdown editor. Inconsistent markdown state should be avoided at all costs. When it changes valid markdown on a minor edit to something wildly different, I keep thinking "Oh there must be a bug"
