### ISSUE TITLE
[Bug] Ctrl+z don't work in math mode

### ISSUE THREAD

**Issue by gf0507033** [Saul-Mirone/milkdown#362]
Thank you for excellent editor!

I found small bug: I can't undo via ctrl+z while editing math block. Undo button from menu works as expected. Could be reproduced in recent Firefox and Chrome on linux. 

Ctrl+z in inline math works perfect.

Not js guru, so can't fix it via myself :(

**Comment by Saul-Mirone** [comment]
It won't work because I havn't do this feature. Will consider in future.

**Comment by gf0507033** [comment]
Thx for fixing (with blazing speed!).
