### ISSUE TITLE
[Bug] No ability to fully clear the input & Inconsistency in input\output

### ISSUE THREAD

**Issue by ze-kel** [Saul-Mirone/milkdown#364]
**Describe the bug**
In certain conditions view can appear empty but you still have content when viewing raw string. 

**To Reproduce**
*Case A:*
1. Create header
`### Some Header`
2. Hold backspace to clear everything
3. Check the internal value, it will be 
`###`

The only way you can fully clear is by pressing enter and then backspace two times 

*Case B:**
1. In an empty editor press enter. You will be on the second line, internal value is
`\n\n`
2. Save internal value somewhere and reload the editor passing that value to defaultValueCtx
3. Editor will appear empty, you will be on the first line, yet you passed the content.

**Expected behavior**
*Case A:**
Pressing backspace when editing empty header should first bump header level by one(### -> ## -> #) and then get rid of the header completely.

*Cabe B:*
Either respect passed linebreaks or output empty string unless there is some text aside from line breaks.

**Screenshots**

**Desktop (please complete the following information):**

-   OS: Mac Os 12
-   Browser: Electron
-   Version: 17(Chromium 98.0.4758.74)

**Comment by Saul-Mirone** [comment]
CaseA:
https://github.com/ProseMirror/prosemirror/issues/1018

CaseB:
PR welcome
