### ISSUE TITLE
[Feature] Allow specifying mermaid themes for the plugin-diagram via config options

### ISSUE THREAD

**Issue by buehlefs** [Saul-Mirone/milkdown#368]
**Is your feature request related to a problem? Please describe.**
The theme passed to mermaid.render is calculated from css variables of the document root by default.
Because these variables are also used to style other parts of milkdown it is not possible to just change the diagram colors.

(side note: rendering diagram fails if css property contains a space `" #fafafa"`, which can happen under some circumstances)

**Describe the solution you'd like**
Diagram colors passed to mermaid should be configurable for each milkdown editor via javascript.

**Describe alternatives you've considered**
Configure css variables at document root -> changes other styles.

Configure css variables only for diagram dom node -> no effect as css variables are read from document root (also background and primary color of mermaid theme use the same css property)

**Comment by Saul-Mirone** [comment]
I'm working on milkdown@v6 and it won't calculated by document root anymore. But it's make sense to set it as configurable.

**Comment by quank123wip** [comment]
> I'm working on milkdown@v6 and it won't calculated by document root anymore. But it's make sense to set it as configurable.

Would you mind me to make a PR for this? I want to try my best to solve problems like this without making breaking changes and bug-free, and make that as elegantly as possible to get some experiences for myself. I don't want to make it a waste of your time.

**Comment by Saul-Mirone** [comment]
> > I'm working on milkdown@v6 and it won't calculated by document root anymore. But it's make sense to set it as configurable.
> 
> Would you mind me making a PR for this? I want to try my best to solve problems like this without making breaking changes and bug-free, and make that as elegantly as possible to get some experiences for myself. I don't want to make it a waste of your time.
> 
> Edit: It seems not very hard to do this. But there is a problem with mermaid's type definition. Need a PR for that and I will commit for this if you like.

Sure, you can try it in latest code and I'll release it with v6.0

**Comment by quank123wip** [comment]
> > > I'm working on milkdown@v6 and it won't calculated by document root anymore. But it's make sense to set it as configurable.
> > 
> > 
> > Would you mind me making a PR for this? I want to try my best to solve problems like this without making breaking changes and bug-free, and make that as elegantly as possible to get some experiences for myself. I don't want to make it a waste of your time.
> > Edit: It seems not very hard to do this. But there is a problem with mermaid's type definition. Need a PR for that and I will commit for this if you like.
> 
> Sure, you can try it in latest code and I'll release it with v6.0

Waiting for DefinitelyTyped/DefinitelyTyped #58851 to be merged. I will make a temporary .d.ts definition for this.
