### ISSUE TITLE
[Feature] Add CRDT real-time collaboration using yjs

### ISSUE THREAD

**Issue by Toubat** [Saul-Mirone/milkdown#369]
**Is your feature request related to a problem? Please describe.**
Collaborative doc becomes more and more popular, especially for rich-text/markdown editors like MilkDown.

**Describe the solution you'd like**
Create a plugin that integrates with yjs or y-prosemirror to give power to real-time collaboration. By the official doc
of real-time collaboration for prosemirror, they also implement a version track system like Git, so maybe this is also a good feature to add.
https://github.com/yjs/yjs-demos

**Additional context**
[Yjs Editor Binding](https://docs.yjs.dev/ecosystem/editor-bindings/prosemirror)

**Comment by Saul-Mirone** [comment]
https://github.com/Saul-Mirone/milkdown/blob/main/packages/plugin-collaborative/README.md
