### ISSUE TITLE
Milkdown editor looses focus when space or slash is pressed inside YouTube (custom extension)

### ISSUE THREAD

**Issue by abudhakeer** [Saul-Mirone/milkdown#371]
First of all, thank you for creating such a wonderful open source editor. I am creating a chrome extension using milk-down editor to take notes inside YouTube. I was able to make the editor show up in the page and can type as well. But when i press the hot-keys specific to YT like slash or space, the focus is lost inside the editor and does the actions mapped inside YT. Is there any way this can be avoided? 

Attaching the video for reference.

https://user-images.githubusercontent.com/2256033/154722825-fd5e5555-5465-4d00-83db-9e5953c5fc1c.mp4

**Comment by Saul-Mirone** [comment]
I think maybe the only way is to intercept the keydown DOM event when focusing the editor.

**Comment by Saul-Mirone** [comment]
Closing since it's seems not about what inside milkdown. But about how youtube website handle shortcuts.

**Comment by abudhakeer** [comment]
Sorry for late response. Yes, i had to listen to keydown event and do `e.stopPropagation()` and things worked fine.
