### ISSUE TITLE
[Feature] Discord channel

### ISSUE THREAD

**Issue by Toubat** [Saul-Mirone/milkdown#372]
**Is your feature request related to a problem? Please describe.**
It would be better if we have discord or slack channel for efficient communication.

**Comment by Saul-Mirone** [comment]
<img width="527" alt="Screen Shot 2022-02-19 at 12 05 02 PM" src="https://user-images.githubusercontent.com/10047788/154785440-9634b13e-e8a0-4ab6-b713-f69c4c8d0dac.png">
?
