### ISSUE TITLE
[Feature] MDX plugin

### ISSUE THREAD

**Issue by Toubat** [Saul-Mirone/milkdown#373]
**Is your feature request related to a problem? Please describe.**
MDX is a very powerful markdown format that allows JSX syntax and renders react-like components in real-time.

**Describe the solution you'd like**
A plugin that supports MDX syntax without having conflicts with existing plugins (common mark, gfm, etc). 

**Additional context**
[Github MDX](https://github.com/mdx-js/mdx)

**Comment by Saul-Mirone** [comment]
Duplicate with https://github.com/Saul-Mirone/milkdown/discussions/345
