### ISSUE TITLE
[Feature] Simplify the way of configure plugins

### ISSUE THREAD

**Issue by charescape** [Saul-Mirone/milkdown#377]
**Is your feature request related to a problem? Please describe.**

No, It's just that the current configuration form is not simplified enough, and it will not be easy to maintain in the future.

**Describe the solution you'd like**

Use json or plain-object as configuration options.

**Describe alternatives you've considered**

**Additional context**

**Comment by quank123wip** [comment]
It's very easy to import plugins by chain-loading which we are using now, it enables developers to write their own plugins and integrate them in seconds. Also it's convenient to export and integrate configs in some situation. This method is proved by many projects such as unifie, remark and markdownit.

**Comment by charescape** [comment]
Makes sense, thank you.

**Comment by adaboese** [comment]
Where is the documentation for this? I am still struggling to understand how the config works

**Comment by Saul-Mirone** [comment]
> Where is the documentation for this? I am still struggling to understand how the config works

Which part of it you want to know more about?

**Comment by adaboese** [comment]
I was confused because I thought I can do something like this:

```
export const keywordsContext = $ctx([], 'keywordsContext');

...

ctx.get(keywordsContext)
```

but turns out I was supposed to use the name (`'keywordsContext'`)

**Comment by Saul-Mirone** [comment]
> I was confused because I thought I can do something like this:
> 
> ```
> export const keywordsContext = $ctx([], 'keywordsContext');
> 
> ...
> 
> ctx.get(keywordsContext)
> ```
> 
> but turns out I was supposed to use the name (`'keywordsContext'`)

It's just `ctx.get(keywordsContext.key)`, `$ctx` is a helper to make sure it creates exactly a milkdown plugin.
