### ISSUE TITLE
[Feature] i18n support for the editor & plugins

### ISSUE THREAD

**Issue by charescape** [Saul-Mirone/milkdown#378]
**Is your feature request related to a problem? Please describe.**

It’s a feature request, for language localization.

**Comment by Saul-Mirone** [comment]
All plugin's text can be configured to any language. What's the issue you have?

**Comment by charescape** [comment]
After a few days of usage, I realized that this is not a feature request, but a question of adding more examples. #288

**Comment by charescape** [comment]
Close as figured out.
