### ISSUE TITLE
[Bug] @milkdown/core compatibility with Next failing due to Server-side Rendering

### ISSUE THREAD

**Issue by schroeder-g** [Saul-Mirone/milkdown#389]
**Describe the bug**
Hi again, 

firstly your input was greatly appreciated earlier today. Currently encountering another `next`-specific issue. Briefly, standard import syntax fails due to the nature of dynamic rendering in `next`. It will render in both the server and client context, and when rendering server side it breaks due to the fact that `window.document is undefined` while outside of a DOM. 

Next offers a work around for these issues with [dynamic imports](https://nextjs.org/docs/advanced-features/dynamic-import). However, when implementing their `dynamic` method, I run into a typing issue (pictured below). Looking at the error, it has something to do with the structure of the exports in `/core/src/index.ts`.

Do you have insight into how I could resolve this issue? If there's anything I can provide that would be of assistance please let me know.

Many thank yous,
Alex

**To Reproduce**
Steps to reproduce the behavior in a next@12.1.0 context:

1. `import { Editor, rootCtx } from '@milkdown/core';`
2.  Note the 'document is not defined' error
3. import and implement `dynamic` from `next` to negate SSR
4.  Attempt a dynamic import as pictured below
5.  Note the type mismatch which prevents successful import of requisite components

**Expected behavior**
Successful implementation of @milkdown/react

**Screenshots**
Following Es6 import syntax:
![image](https://user-images.githubusercontent.com/66321261/155626592-c751b102-943b-4732-87d4-3fa2a547af13.png)
![image](https://user-images.githubusercontent.com/66321261/155626575-795a994e-f540-49d0-b731-5f1044304259.png)

Using `next` dynamic imports:
![image](https://user-images.githubusercontent.com/66321261/155626717-c62acc79-63bc-41a2-b036-de6ffdfc84dd.png)

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Browser Chrome

**Comment by Saul-Mirone** [comment]
The prosemirror is dependent on document so you need to import the component with `ssr: false` in nextjs.

**Comment by schroeder-g** [comment]
Thank you sincerely for the response, Saul. While dynamic import with `ssr: false` fixes the document issue, there seems to be trouble with the expected types with that format. The final picture above shows the problem ^

**Comment by Saul-Mirone** [comment]
That's caused by that in @milkdown/react, we didn't export the component as default. However react expect to import component as default. So one way to solve this is to wrap your editor component like this:

```typescript
// MyEditor.ts

export default function myEditor() {
  const useEditor = /* ... */
  return <ReactEditor {/*...*/}  />
}
```

```typescript
// Your next page

const EditorComponent = dynamic(() => import("./MyEditor.ts"), { ssr: false })
```
