### ISSUE TITLE
[Bug] The `/` command popup is covered by menubar

### ISSUE THREAD

**Issue by charescape** [Saul-Mirone/milkdown#393]
**Describe the bug**
The `/` command popup is covered by menubar.

1. Go to https://milkdown.dev/online-demo
2. Type `/` on top line

**Screenshots**
![image](https://user-images.githubusercontent.com/53265646/155703945-b9fd222a-c194-40d5-a020-3dbda59c464e.png)

**Desktop (please complete the following information):**

-   OS: [Windows]
-   Browser [Chrome]
-   Version [96]

**Comment by quank123wip** [comment]
Do you have more details about how to reproduce this? I have only encountered this when the editor has a very tight height, like half of the screen. If this is caused by this, I think this is a user-side
problem, and the workaround is, define a minimum height for the editor and make it overflow and scrollable on the parent node.

**Comment by charescape** [comment]
@quank123wip Here is a gif screenshot:

![screen](https://user-images.githubusercontent.com/53265646/155750241-e0f6f0c1-a01e-406c-8d9d-c6cf8f9768d2.gif)

**Comment by quank123wip** [comment]
> Here is a gif screenshot:
> 
> ![screen](https://user-images.githubusercontent.com/53265646/155750241-e0f6f0c1-a01e-406c-8d9d-c6cf8f9768d2.gif)

I think this is related to the height of the editor. Could you please inspect the editor's size in devtools? Also, adjust it into a acceptable size can solve this I think. But this requires a little CSS knowledge. Anyway, it's true that we have to solve this problem related to editor height.

**Comment by abudhakeer** [comment]
Hey @charescape i faced similar issue as explained in [here](https://github.com/Saul-Mirone/milkdown/issues/371). Probably you can add event listener for `keydown` event and do `e.stopPropagation()`. And yeah it can be difficult if you want to do this for different keys.
