### ISSUE TITLE
[Feature] Is there any plans to add prefix for all css classes?

### ISSUE THREAD

**Issue by charescape** [Saul-Mirone/milkdown#395]
In most use cases, the web application will use css frameworks (e.g. bootstrap.css), which can cause some unexpected style or layout changes.

**Comment by Saul-Mirone** [comment]
Make sense.

**Comment by quank123wip** [comment]
Maybe we can do this better, like provide a scoped option like vue compiler does or even more than that, use shadow root feature? This would cause browser support dropping. It's definitely a thing we need before it can be put in massive production or open source use.

**Comment by charescape** [comment]
Using scoped class is not a proper solution, it may take more time to solve the problem of style mixin, because bootstrap does not use scoped class.

**Comment by charescape** [comment]
What I'm trying to say is that scoped class is definitely a good idea, but adding prefixes still makes sense.

**Comment by Saul-Mirone** [comment]
> CSS variables should also be prefixed if they are set on the root element (milkdown 5 sets some css variables with common names that can mess up existing css).

There will be no css variables.

**Comment by Saul-Mirone** [comment]
There won't be something like `prefix` for all css classes. But users now can use `configure` to change the class name to whatever they want, same as [here in documentation](https://milkdown.dev/styling#add-custom-class-name).
