### ISSUE TITLE
Tab should move cursor to next column inside table element

### ISSUE THREAD

**Issue by johnoscott** [Saul-Mirone/milkdown#41]
I am making a suggestion to make the Tab key move cursor to next column inside table element.

Love this editor BTW!

**Comment by Saul-Mirone** [comment]
Hi, Thank!

You can use `Mod + ]` and `Mod + [` to move across the table. BTW, `Mod` is `Ctrl` on windows and `Command` on mac.
I think that might be helpful.

**Comment by johnoscott** [comment]
OK good to know. If I want to change these keyboard shortcuts, where is the config ?

**Comment by Saul-Mirone** [comment]
Currently configure shortcuts has not been supported. I'll do it in the next release, maybe this weekend.

**Comment by Saul-Mirone** [comment]
The custom keymap for tab plugin has already been supported, you can check the readme here:

https://github.com/Saul-Mirone/milkdown/blob/main/packages/plugin-table/README.md

I'll close this issue, feel free to reopen if needed.

**Comment by johnoscott** [comment]
Cool. I will check it out.

**Comment by Saul-Mirone** [comment]
@johnoscott 
BTW, we have a new document section about [keyboard shortcuts](https://saul-mirone.github.io/milkdown/#/keyboard-shortcuts).

**Comment by johnoscott** [comment]
nice !
