### ISSUE TITLE
Nested lists

### ISSUE THREAD

**Issue by yoohahn** [Saul-Mirone/milkdown#42]
Is there any plans to add support for nested list items in the editor?

Milkdown supports the rendering of such lists;

```
1. First item
2. Second item
3. Third item
    1. Indented item
    2. Indented item
        * ABC
        * DFG
4. Fourth item
```

But when creating a news lists I do not find a way to create more than the first level. So the list above is only possible to create like this.

```
1. First item
2. Second item
3. Third item
4. Indented item
5. Indented item
6. ABC
7. DFG
8. Fourth item
```

**Comment by Saul-Mirone** [comment]
Hi, yoohahn.

You can use `Mod-[` and `Mod-]` to control the nest lists. BTW, `Mod` is `Command` on macOS and `Ctrl` on windows.

The custom keymap is also in the plan.

**Comment by yoohahn** [comment]
Ah cool. That worked when I switched layout to english. :)

**Comment by ashutoshsaboo** [comment]
@Saul-Mirone Just stumbled upon this. For task lists, I don't think nested task lists are supported yet isn't it? Do you plan to support them? I like how ToastUI's editor does it - https://ui.toast.com/tui-editor.
