### ISSUE TITLE
[Feature] Remark only read-only mode

### ISSUE THREAD

**Issue by durdenx** [Saul-Mirone/milkdown#430]
**Is your feature request related to a problem? Please describe.**
Milkdown doesn't seem to handle SSR mode correctly because of Prosemirror. Moreover it is not necessary to load the Prosemirror lib when you just want to display the content.

**Describe the solution you'd like**
I would like to have a read-only mode that only uses Remark rendering out of the box (e.g. that manage all custom components or plugins). It will be better for SEO and bundle size.

**Describe alternatives you've considered**
Create a duplicate remark rendering component to use in read-only mode.

**Comment by Saul-Mirone** [comment]
We cannot only use remark to render content because there are bunch of custom components such as task list and code fence. I think we can make SSR mode work finally. If you need to render markdown just use remark. You should put this logic on your side.

**Comment by durdenx** [comment]
Ok @Saul-Mirone, thanks for your answer. May I ask how you plan to make the SSR work?

**Comment by Saul-Mirone** [comment]
> Ok @Saul-Mirone, thanks for your answer. May I ask how you plan to make the SSR work?

The code in main stream should work well now thanks to @kevinmarrec
