### ISSUE TITLE
[Bug]diagram plugin config error

### ISSUE THREAD

**Issue by swordream** [Saul-Mirone/milkdown#459]
**Describe the bug**
import { diagram, TurnIntoDiagram } from "@milkdown/plugin-diagram";
Editor.make().use(diagram({options...}));

Generate the following error:
```
This expression is not callable.
  Type 'AtomList<Metadata<GetPlugin<string, Options>> & MilkdownPlugin>' has no call signatures.ts(2349)
```

**Comment by Saul-Mirone** [comment]
The doc is for latest (beta) version.
