### ISSUE TITLE
Vue 2 support

### ISSUE THREAD

**Issue by quank123wip** [Saul-Mirone/milkdown#46]
As there is a bunch of projects using vue 2 and it's a long journey to migrate to vue 3, it would be nice to support vue 2, as it's tiring to include both vue 2 and vue 3 instance in one project, and I think it's not elegant to use vanilla javascript in vue 2 project.

**Comment by Saul-Mirone** [comment]
Vue2 can use  this project simply via `$ref`, it's very easy.

**Comment by quank123wip** [comment]
But Vue 2 have no custom component support out of box as far as I know. Is there something right there I don't know? If it isn't, do you have a plan to support it

**Comment by Saul-Mirone** [comment]
I don't have plan for it right now, there are still so many works to do.
Maybe I'll consider to support more UI frameworks after finish core abilities, but now is not a good time I think.
However, support the custom component is not so hard, I think you can have a try if really you really need that.

**Comment by quank123wip** [comment]
I'm trying to understand the vue 3.0 package now, if I can, I'll try to write a vue 2.0 component support and make a PR. Thanks for your help!

**Comment by Saul-Mirone** [comment]
You can also create your own package and I'll mention it in [awesome-milkdown](https://github.com/Saul-Mirone/awesome-milkdown) if you want.
I think vue2 will use .vue file and may not use typescript, so the build and dev pipeline maybe totally different.

**Comment by Saul-Mirone** [comment]
Closed for no new message for days.
