### ISSUE TITLE
The image and link feature depend on tooltip plugin

### ISSUE THREAD

**Issue by swordream** [Saul-Mirone/milkdown#460]
The image and link features depend on the tooltip plugin. If the tooltip plugin is not installed, the input box of the image and link  will not pop up. It feels that this design is unreasonable and should be decoupled.

image 和 link 特性依赖于 tooltip 插件，如果不安装tooltip 插件，image 和 link 更新链接的输入框就不会弹出，感觉这样设计不合理，应该解耦。

**Comment by Saul-Mirone** [comment]
It's already been done in latest code.
