### ISSUE TITLE
[Bug] factory is not a function

### ISSUE THREAD

**Issue by Retr0ve** [Saul-Mirone/milkdown#461]
**Describe the bug**
When I try to integrate the prosemirror plugin from [here](https://prosemirror.net/examples/track/).
I got this error:
```
TypeError: factory is not a function
    at eval (index.es.js?0e52:244)
    at async Promise.all (:8080/index 1)
    at async _Editor.create (index.es.js?5cd3:317)
```

**To Reproduce**

1. import trackPlugin from '../plugin/track-state';
2. use plugin
```
const trackStatePlugin = createPlugin({
      prosePlugins: () => [trackPlugin],
});
const editor = useEditor((root) =>
      Editor.make()
        .config((ctx) => {
          ctx.set(rootCtx, root);
          ctx.set(defaultValueCtx, "# Milkdown 💖 Vue");
        })
        .use(defaultTheme)
        .use(emoji)
        .use(commonmark)
        .use(trackStatePlugin())
);
```
3. got the error in console

**Expected behavior**
Plugin successfully installed

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Browser Electron 16.0.5

**Comment by Saul-Mirone** [comment]
It's
```typescript
const trackStatePlugin = createPlugin(() => ({
      prosePlugins: () => [trackPlugin],
}));
```

BTW, you can also do:
```typescript
import { $prose } from '@milkdown/utils';

const trackStatePlugin = $prose(() => trackPlugin)
```

**Comment by Retr0ve** [comment]
Thank you for the quick reply! I guess It's better to update the doc then?

**Comment by Saul-Mirone** [comment]
It's in the v6.0 iteration plan, I'm still working on it.
