### ISSUE TITLE
[Bug]到底如何配置插件呢

### ISSUE THREAD

**Issue by swordream** [Saul-Mirone/milkdown#477]
import { diagram } from "@milkdown/plugin-diagram";
 Editor.make()
      .use(diagram({...options}));

以上代码会提示 ：
This expression is not callable.
  Type 'AtomList<Metadata<GetPlugin<string, Options>> & MilkdownPlugin>' has no call signatures.

其实我就是想配置一下默认提示语言：
```
 Editor.make()
      .use(diagram({
         placeholder: {
             empty:"点击此处编辑",
            error: “语法错误”,
           },
    }));
```
这个问题当时我提过，当时说新版的解决了。但我切换到6.0版本，还是这样的，还是我不会用？

**Comment by Saul-Mirone** [comment]
```typescript
import { diagramPlugin } from '@milkdown/plugin-diagram';

Editor.make().use(diagramPlugin({ placeholder: /* */ }))
```

**Comment by swordream** [comment]
这个，没看到有 export  diagramPlugin 啊

```
  import { AtomList } from '@milkdown/utils';

  import { diagramNode } from './node';

export * from './remark-mermaid';

export const diagram = AtomList.create([diagramNode()]);

export type { Options } from './node';
export { TurnIntoDiagram } from './node';
```

会提示 Module '"@milkdown/plugin-diagram"' has no exported member 'diagramPlugin'
