### ISSUE TITLE
[Bug] Can not render empty lines of markdown

### ISSUE THREAD

**Issue by 4-1-1** [Saul-Mirone/milkdown#487]
**Describe the bug**
Edit the example of react, add some empty line or \ to markdown 

**To Reproduce**

```
const markdown = `
# Milkdown Test

---

Now you can play!



\


`;
```

**Expected behavior**
show empty line  both in edit and readonly mode

**Screenshots**

**Desktop (please complete the following information):**

-   OS: Mac
-   Browser chrome
-   Version [e.g. 22]

**Smartphone (please complete the following information):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**

**Comment by Saul-Mirone** [comment]
That's how remark works, you should create a bug there if you think its a bug.

In my option, markdown will combine multiple new lines and every markdown parser should behave like this.

**Comment by knownasilya** [comment]
This is for the editor side? Is there a way to add a remark plugin in v7?

**Comment by jrpedrianes** [comment]
@knownasilya, did you happen to find a solution? I was trying to integrate "remark-breaks" into Milkdown without success. Maybe my integration wasn't correct.

**Comment by shenzhongkang** [comment]
> @knownasilya, did you happen to find a solution? I was trying to integrate "remark-breaks" into Milkdown without success. Maybe my integration wasn't correct.

how to integrate remark plugin in milkdown?

**Comment by knownasilya** [comment]
@jrpedrianes I was not able to implement it, had to move on.
