### ISSUE TITLE
[Bug] Hard break in a table，save data and rerender, the hard break is gone

### ISSUE THREAD

**Issue by 4-1-1** [Saul-Mirone/milkdown#494]
**Describe the bug**
In a table th/td shell, using `Shift + Enter` to insert a break. and rerender using the saved data

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="329" alt="image" src="https://user-images.githubusercontent.com/4401981/167533751-cedecfce-a6ab-46d3-ab6e-c9a18700873c.png">

<img width="265" alt="image" src="https://user-images.githubusercontent.com/4401981/167533804-2c98ed56-e3ef-446a-aa09-764b4afe65bb.png">

**Desktop (please complete the following information):**

-   OS: Mac OS
-   Browser ：chrome
-   Version 100

**Smartphone (please complete the following information):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**

**Comment by Saul-Mirone** [comment]
Seems we should disable hardbreak for table

**Comment by 4-1-1** [comment]
If I escape space with backlash in table cell, and trans two space to br. Is it a good way?
