### ISSUE TITLE
[Bug] demo not show menu

### ISSUE THREAD

**Issue by zhangwei900808** [Saul-Mirone/milkdown#495]
**Describe the bug**
react demo not show menu

**To Reproduce**
open https://milkdown.dev/zh-hans/react

**Expected behavior**
show editor menu

**Screenshots**
<img width="697" alt="image" src="https://user-images.githubusercontent.com/4385154/167831337-004523ce-bccf-492b-a101-fce426274a53.png">

**Desktop (please complete the following information):**

-   OS:macos
-   Browser chrome
-   Version 101

**Comment by Saul-Mirone** [comment]
Menu is a plugin and not installed in demo

**Comment by zhangwei900808** [comment]
@Saul-Mirone 怎么配置这个菜单啊，在官网上面也没看到

**Comment by Saul-Mirone** [comment]
https://milkdown.dev/plugin-menu
