### ISSUE TITLE
[Bug] Getting Started page codesandbox doesn't work

### ISSUE THREAD

**Issue by gcaptn** [Saul-Mirone/milkdown#497]
The codesandbox in https://milkdown.dev/getting-started shows just a blank page and a MIME type error:

<details>

On Brave/chrome:
<img width="1101" alt="Screen Shot 2022-05-12 at 14 59 40" src="https://user-images.githubusercontent.com/35653836/168022516-000a11ae-1e56-4f4a-81e4-ae2dfe97f361.png">

Safari:
<img width="1043" alt="Screen Shot 2022-05-12 at 15 00 32" src="https://user-images.githubusercontent.com/35653836/168022539-97e93dbc-3d08-4bcf-8573-c777b4a9b17e.png">

</details>

**Comment by Saul-Mirone** [comment]
It's working well on 3 devices on my side.
