### ISSUE TITLE
[Bug] Bullet list insert HTML comment between paragraphs

### ISSUE THREAD

**Issue by fb-datax** [Saul-Mirone/milkdown#498]
**Describe the bug**
Using the bullet list button on 2 paragraphs inserts `<!---->` between them in the resulting markdown

**To Reproduce**

Create 2 paragraphs and convert them to bullet lists

**Screenshots**
![20220512-demo-milkdown-bug](https://user-images.githubusercontent.com/7262103/168105852-3db4044a-fcdb-4905-80e9-a2d6875a2949.gif)

**Desktop (please complete the following information):**

-   OS: Win, Linux
-   Browser: Chrome, FF
-   Version: latest

**Comment by Saul-Mirone** [comment]
That's the expected behavior controlled by remark to separate two different lists.
