### ISSUE TITLE
[Feature] Did you have a plan to make a plugin work with remark-rehype?

### ISSUE THREAD

**Issue by 4-1-1** [Saul-Mirone/milkdown#501]
**Is your feature request related to a problem? Please describe.**
To support html in markdown

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Saul-Mirone** [comment]
Why do we need remark-rehype?

**Comment by 4-1-1** [comment]
font color in markdown , breaks in table cell, etc .

**Comment by 4-1-1** [comment]
Most markdown  engine can support html tag by a little config

**Comment by Saul-Mirone** [comment]
It's been considered before in https://github.com/Saul-Mirone/milkdown/issues/126. However, it's impossible and unsafe to make within the prosemirror's architecture. These feature needs to be done through other approaches such as https://www.npmjs.com/package/remark-directive
