### ISSUE TITLE
Is Vite supported?

### ISSUE THREAD

**Issue by WJCHumble** [Saul-Mirone/milkdown#51]
I use milkdown in `Vue3` + `Vite` project, but it seems doesn't work normally, is milkdown support vite ?

**Comment by Saul-Mirone** [comment]
Milkdown is developed using vite, so of course it supports vite. Could you please provide a sample project to show the problems?

**Comment by WJCHumble** [comment]
I created a repo https://github.com/WJCHumble/milk-demo

**Comment by Saul-Mirone** [comment]
@WJCHumble I clone the repo and run npm install & npm run dev, then the milkdown works as expected...
So, what's your concern?

![image](https://user-images.githubusercontent.com/10047788/124389726-086abb00-dd1b-11eb-9212-32eb254130f8.png)

**Comment by WJCHumble** [comment]
@Saul-Mirone Why is the result of my is different from yours 😂

<img width="1437" alt="截屏2021-07-04 下午11 10 35" src="https://user-images.githubusercontent.com/48761114/124390196-0bff4180-dd1d-11eb-8286-9f458fb654a0.png">

**Comment by Saul-Mirone** [comment]
> @Saul-Mirone Why is the result of my is different from yours 😂
> 
> 
> 
> <img width="1437" alt="截屏2021-07-04 下午11 10 35" src="https://user-images.githubusercontent.com/48761114/124390196-0bff4180-dd1d-11eb-8286-9f458fb654a0.png">
> 
> 

I just enter something, If you don't enter anything, the editor will have no text so it's empty.
 You may want to set some markdown content as defaultValue or use @milkdown/plugin-slash as the placeholder.

**Comment by WJCHumble** [comment]
Okay, I know 😂. Thank you @Saul-Mirone
