### ISSUE TITLE
[Bug] Input chips without an apply button are hidden after every input

### ISSUE THREAD

**Issue by buehlefs** [Saul-Mirone/milkdown#513]
**Describe the bug**
Try to edit an inline math node or a footnote reference (e.g. <https://milkdown.dev/online-demo>). The input chip will close after every single input. To show the input again to input the next character one needs to click on another node first before clicking on the math node.

**To Reproduce**

1. Go to <https://milkdown.dev/online-demo>
2. Click on an inline math element (or a footnote)
3. Try to edit the element
4. The input chip hides itself after the first keypress

**Expected behavior**
The input chip should not hide itself until the user clicked outside.

**Desktop (please complete the following information):**

-   OS: windows
-   Browser vivaldi (chromium)

**Additional context**
Debugging the problem suggests, that the `view.hasFocus()` function of the node returns `false` after an input which in turn hides the input chip.

**Comment by Saul-Mirone** [comment]
I'll fix it soon.
