### ISSUE TITLE
Removing space when writing on Firefox 89.0.2 Mac

### ISSUE THREAD

**Issue by yoohahn** [Saul-Mirone/milkdown#52]
Found an issue using FireFox and milkdown. When typing in a paragraph it will remove spaces from what I am typing, but it works fine in a header.

![md](https://user-images.githubusercontent.com/994522/124457057-b0b86800-dd8b-11eb-8fc9-aa473e8bc2a8.gif)

**Comment by Saul-Mirone** [comment]
Caused by css issues, have been fixed.

**Comment by Saul-Mirone** [comment]
Feel free to reopen this if you have further questions.
