### ISSUE TITLE
[Bug] Using milkdown with vite2 and vue3, have error with "extend" export

### ISSUE THREAD

**Issue by WHYBBE** [Saul-Mirone/milkdown#523]
**Describe the bug**

When I use milkdown with vite2 and vue3, there is an error with "extend" export.

It may to do with `resolve.extensions`.

When I set something in `vite.config.ts` file like below,

```ts
resolve: {
  extensions: ['.ts'],
},
```

error happened.

When I annotate the extensions configuration, there is no problem.

I would like to know why the extensions setting of vite2 affects the usage of milkdown. Is this a vite2 problem or a milkdown problem?

**To Reproduce**

[https://github.com/WHYBBE/reproduce/tree/main/milkdown](reproduce repo url)

1. git repo with `git clone git@github.com:WHYBBE/reproduce.git`
2. enter project, `cd reproduce/milkdown`
3. get depts, `npm install`
4. run with `npm run` and would get error in terminal
5. if annotate line 7 in `vite.config.ts`, there would be get expected behavior

**Expected behavior**

visit `http://localhost:3000/` and get an editor with "Hello Vue 3 + TypeScript + Vite"

**Screenshots**

Failed to resolve entry for package "extend" in terminal

![image](https://user-images.githubusercontent.com/40510346/169784985-79e465b5-973b-4c0f-883a-e289eadfbf86.png)

cannot get @milkdown bundle error in browser console

![image](https://user-images.githubusercontent.com/40510346/169781348-b0d1794b-092d-4fca-ad90-4ff6e26e60d1.png)

**Desktop:**

-   OS: Windows11 25120.1010
-   Browser: Edge 101.0.1210.53, Firefox 100.0.2 

**Additional context**

None

**Comment by Saul-Mirone** [comment]
It's not something related to milkdown. If you set the config like that, any package from node_modules won't work.

**Comment by WHYBBE** [comment]
> It's not something related to milkdown. If you set the config like that, any package from node_modules won't work.

but other package work fine under that config, like axios, vue-router and etc.

and if I set that config, @milkdown/* would not packed by esbuild to `node_modules/.vite/deps`

**Comment by Saul-Mirone** [comment]
The error information is:

```bash
Failed to resolve entry for package "extend". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "extend". The package may have incorrect main/module/exports specified in its package.json.
```

The [extend](https://www.npmjs.com/package/extend) package is an old package and it's main entry is set as `index`, so I guess vite will only try `index.ts`.

Milkdown use [remark](https://github.com/remarkjs/remark) which depends on this library. I think extend is the only package that has this problem.

**Comment by WHYBBE** [comment]
Thank you for your answer.

So, it's a problem of the upstream repository.

Is there any way to solve this problem?
Just use that configuration without error?

Although I can omit the extension without using that configuration.

**Comment by Saul-Mirone** [comment]
I don't think there's other way to do this, the only way is that add `.js` in your configuration.

**Comment by WHYBBE** [comment]
> I don't think there's other way to do this, the only way is that add `.js` in your configuration.

I got it.
Thanks!!
