### ISSUE TITLE
[Bug] 如果把光标移动到2个emoji中间， 光标会移动到行尾

### ISSUE THREAD

**Issue by ununian** [Saul-Mirone/milkdown#524]
**Describe the bug**
如果把光标移动到2个emoji中间， 光标会移动到行尾

**To Reproduce**

1. 打开官网示例
2. 输入2个emoji
3. 鼠标点击2个emoji中间，或者先点击后面那个emoji右边再按左键。
4. 可以发现光标出现在了行尾

**Expected behavior**
期望出现在2个emoji中间

**Screenshots**
![image](https://user-images.githubusercontent.com/4506072/169796600-431b4269-1f5d-44fd-a087-5bdc8fae78e0.png)

**Desktop (please complete the following information):**

-   OS: Windows
-   Browser chrome
-   Version 100

**Comment by Saul-Mirone** [comment]
Seems it's a common bug in prosemirror.
https://discuss.prosemirror.net/t/cursor-jumps-at-the-end-of-line-when-it-betweens-two-inline-nodes/4641
