### ISSUE TITLE
[Bug] Copy paste text into milkdown adds a "\"

### ISSUE THREAD

**Issue by onegigbyte** [Saul-Mirone/milkdown#525]
**Describe the bug**
Copy paste text into milkdown adds a "\"

**To Reproduce**

1. Go to github.com, search "news"
2. Double click and copy the text "Where the world builds software"
3. Go to https://milkdown.dev/online-demo
4. Paste the text "Where the world builds software"
5. There will be a "\" at the end of the paragraph.
See https://imgur.com/a/u4khzhU

**Expected behavior**
No slash.

**Screenshots**
https://imgur.com/a/u4khzhU

**Desktop (please complete the following information):**
chrome

**Comment by Saul-Mirone** [comment]
Can you paste a video or something like that? I cannot repro on my side.

https://user-images.githubusercontent.com/10047788/169949594-4052b0be-768b-49e9-9e7e-79541ae18a5e.mp4

.

**Comment by Saul-Mirone** [comment]
OK, I know, if you **double click to select the title**, the content you get will include a `<br>` in it:
```bash
<html>
<body>
<!--StartFragment--><h1 class="h1-mktg color-text-white mb-3 position-relative z-2" style="box-sizing: border-box; font-size: 72px !important; margin-top: 0px; margin-right: 0px; margin-bottom: 16px !important; margin-left: 0px; font-weight: 800 !important; position: relative !important; color: var(--color-scale-white)  !important; font-family: &quot;Alliance No.1&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-feature-settings: &quot;ss02&quot;, &quot;ss01&quot;; letter-spacing: -0.03em !important; line-height: 76px !important; z-index: 2 !important; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(4, 13, 33); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Where the world builds software</h1><br class="Apple-interchange-newline"><!--EndFragment-->
</body>
</html>
```
