### ISSUE TITLE
[Bug] Copy Paste does not work with string in the markdown link format

### ISSUE THREAD

**Issue by onegigbyte** [Saul-Mirone/milkdown#528]
**Describe the bug**
Copy Paste does not work with string in the markdown link format

**To Reproduce**

1. Copy text:[repo]: https://github.com/Saul-Mirone/milkdown
3. Go to https://milkdown.dev/online-demo and paste
4. Paste not showing up

**Expected behavior**
Paste should works, even as a raw string

**Desktop (please complete the following information):**

chrome

**Comment by Saul-Mirone** [comment]
Its [repo](https://github.com/Saul-Mirone/milkdown)

**Comment by onegigbyte** [comment]
Thanks,
I wonder what the reason is that we do not support copy paste this?
[repo]: https://github.com/Saul-Mirone/milkdown

For example, I found a nice markdown conte

https://user-images.githubusercontent.com/1879635/170177339-964defae-e6b5-4433-9581-9d0e42914a88.mov

nt, then I paste it to milkdown, however, it does not show up all the content I copied and pasted.

Here is a video showing such flow, it's a little clunky. Do you think it will be supported to paste everything I copied?

**Comment by Saul-Mirone** [comment]
> Thanks, I wonder what the reason is that we do not support copy paste this? [repo]: https://github.com/Saul-Mirone/milkdown
> 
> For example, I found a nice **markdown** content, then I paste it to milkdown, however, it does not show all the content I copied and pasted.
> 
> Here is a video showing such flow, it's a little clunky, isn't it? Do you think it will be supported to paste everything I copied?
> 
>  Screen.Recording.2022-05-24.at.9.04.08.PM.mov

Cause it's something like a reference, it only useful if you really *ref* to it. Otherwise it won't have any effects
https://www.markdownguide.org/basic-syntax/#reference-style-links
