### ISSUE TITLE
[Bug] dot "." sometimes got appended after ] in a nested list 

### ISSUE THREAD

**Issue by onegigbyte** [Saul-Mirone/milkdown#529]
**Describe the bug**
dot "." sometimes got appended after ] in a nested list 

See video

**To Reproduce**

1. Go to https://milkdown.dev/online-demo
2. Create a nested list, type [x] following with two spaces, 
3. A random dot will show up
4. It does not happen consistently, but happens a lot

**Screenshots**
Video: https://user-images.githubusercontent.com/1879635/170175842-016fc0ca-1c95-4548-a9dd-29644433ee3d.mov

**Questions**:

1. In the demo, I see there is a checkbox in the nested list, but when I typed [x] in the nested list, it didnt show up. 
What is the format here for checkbox in the nested list?

2. What is the best way to create a nested list? Is what I did in the video accurate? Create the 2nd list, then delete, then space and another *?

**Desktop (please complete the following information):**

-   Mac
-   Chrome

**Comment by Saul-Mirone** [comment]
I can't reproduce this random dot bug. As for your questions:

1. Just type [x] with a `space`.
2. Use key `Mod-]` and `Mod-[` to indent a list.

**Comment by Saul-Mirone** [comment]
Can you reproduce this bug after refresh the page?

**Comment by onegigbyte** [comment]
yes, btw, i'm also in incognito.

**Comment by Saul-Mirone** [comment]
> yes, btw, i'm also in incognito.
> 
> [x] with a space does not create a checkbox for me in the list. :(

If you're already in a list, you need to delete the bullet first.

**Comment by Saul-Mirone** [comment]
Well it's a feature of mac, if you press double space anywhere after some words, it will create a dot for you, lmao.

**Comment by onegigbyte** [comment]
Thanks!
