### ISSUE TITLE
VSCode Integration

### ISSUE THREAD

**Issue by L1lith** [Saul-Mirone/milkdown#53]
I would love to use this project in my code editor

**Comment by Saul-Mirone** [comment]
Hi, this idea is interesting, however, this repo is all about editor core and plugin, vscode extension is an application level thing I think. We need to build it in an standalone repo.

I'm still working on some core modules of milkdown. Maybe I'll give it a try when I'm free, if anyone have interests in this idea please just go ahead and let me know and I'll record it in [awesome-milkdown](https://github.com/Saul-Mirone/awesome-milkdown)

**Comment by Saul-Mirone** [comment]
Closed for no new messages for some days.

**Comment by Saul-Mirone** [comment]
Hi @L1lith,

You can try our new vscode extension here:

https://marketplace.visualstudio.com/items?itemName=mirone.milkdown&ssr=false#overview
