### ISSUE TITLE
[Feature] Can milkdown support delete the "format" ?

### ISSUE THREAD

**Issue by onegigbyte** [Saul-Mirone/milkdown#530]
**Is your feature request related to a problem? Please describe.**
For formats like # or ```, even if I keep pressing delete, the format will never go away unless I use menu or edit the raw markdown text.

**Describe the solution you'd like**
Now:
When I keep pressing delete, the format will stay there, eg. # and codeblock

1. 
https://user-images.githubusercontent.com/1879635/170180371-8c93fcd4-b2c4-4af2-aaf4-6735b3fd5467.mov

2. 
https://user-images.githubusercontent.com/1879635/170180230-d06c0019-fab0-4d9a-b744-96883d08774f.mov

Proposal:
When I keep pressing delete, the format will eventually be deleted.
From **typora**: 

https://user-images.githubusercontent.com/1879635/170180678-e8428d8a-0ec9-42f6-8278-944bfcda4ae9.mov

**Comment by Saul-Mirone** [comment]
That's due to the design of prosemirror. I don't have a plan to add workaround for this right now.
https://github.com/ProseMirror/prosemirror/issues/1018
