### ISSUE TITLE
keyboard-friendly and more compact fenced code blocks

### ISSUE THREAD

**Issue by benatkin** [Saul-Mirone/milkdown#54]
It would be nice if I could just type ` ```js ` and tab or enter to start a JavaScript code block. I think if it showed a dropdown with the language, that used the text after ` ``` `, and by default showed "Insert plain text code block" and you could type Tab or Enter to complete that, it would be almost as convenient as being able to get that just by typing ` ``` `.

Showing the file format dropdown also takes up space and adds some visual noise. I think it might be better if it showed a palette when you left-click on the margin of the code block, which on desktop the user could detect by seeing the cursor change betwen an I-beam and an arrow. On mobile perhaps triple dots which could be shown or hidden would do the trick.

Finally, the ability to add a title would be useful. [Docusaurus supports this](https://docusaurus.io/docs/markdown-features/code-blocks#code-title) by adding it to the opening code fence like ` ```ts title="mod.ts" `.

**Comment by Saul-Mirone** [comment]
Let me discuss with designer about this.

**Comment by Saul-Mirone** [comment]
- [x] keyboard friendly code fence
- [ ] compact code fence ui

As for the title feature, I think it should go to plugins like `powerful fence` or something. In commonmark preset, we should keep features simple to fit for everyone.
