### ISSUE TITLE
[Bug] NuxtJs，Demo does not work properly

### ISSUE THREAD

**Issue by know-that** [Saul-Mirone/milkdown#540]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

**Smartphone (please complete the following information):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**

![image](https://user-images.githubusercontent.com/31246220/171584835-a7753f5c-ad78-437f-9fca-024ea2b66040.png)
![image](https://user-images.githubusercontent.com/31246220/171584864-8170abee-76bc-4213-9f33-52a6aba81c1d.png)
![image](https://user-images.githubusercontent.com/31246220/171584912-9aefefc2-9d59-4e91-83bd-3e3804851456.png)

**Comment by Saul-Mirone** [comment]
We only support nuxt 3.
