### ISSUE TITLE
[Bug]When update the state of view, lost all css injected by plugins.

### ISSUE THREAD

**Issue by Ahmong** [Saul-Mirone/milkdown#544]
**Describe the bug**
When update the state of view using view.updateState(newState), the view page will lost all css injected by plugins.

**To Reproduce**
I try to switch the view to a new doc by creating new state like this:

![image](https://user-images.githubusercontent.com/9511090/172054574-0731df9c-b8fd-48f8-a78c-8fa22ab6273c.png)

Then all css injected by plugins have gone.

**Expected behavior**
The css settings should preserve. 

**Screenshots**
The page expected:

![image](https://user-images.githubusercontent.com/9511090/172055260-31427c10-5775-4214-8eed-6fcd537d1556.png)

But I got:

![image](https://user-images.githubusercontent.com/9511090/172055060-da8f60c6-fc5d-4a21-a665-41ad67938fba.png)

**Desktop (please complete the following information):**

-   OS: MacOS 11.6.0 (architecture: x64)
-   Browser: chrome (bundled in electron)
-   Version: v94.0.4606.81

**Comment by Saul-Mirone** [comment]
What's your version?

**Comment by Ahmong** [comment]
> What's your version?

@milkdown v5.5.0

**Comment by Saul-Mirone** [comment]
V6 has fixed the issue.

**Comment by Ahmong** [comment]
Thanks for your reply.
