### ISSUE TITLE
[Bug] Can`t resolve @milkdown/prose/commands

### ISSUE THREAD

**Issue by mkremnev** [Saul-Mirone/milkdown#548]
**Describe the bug**
Installed packages @milkdown/*^6.1.3 when I include them in the project I get the error 

`Module not found: Can't resolve '@milkdown/prose/commands' in 'pwd/node_modules/@milkdown/core/lib'`

 Moreover, if I use v5.5.0, then such an error does not appear

**To Reproduce**

1. Install CRA
2. Install @milkdown/* necessary

**Desktop (please complete the following information):**

-   OS: Ubuntu 20.04
-   node v16.13

**My package.json**

> {
>   "name": "front-cms",
>   "version": "0.1.0",
>   "private": true,
>   "main": "src/index.tsx",
>   "dependencies": {
>     "@material-ui/core": "^4.12.4",
>     "@material-ui/data-grid": "^4.0.0-alpha.37",
>     "@material-ui/icons": "^4.11.3",
>     "@material-ui/lab": "^4.0.0-alpha.61",
>     "@milkdown/core": "6.1.3",
>     "@milkdown/plugin-emoji": "6.1.3",
>     "@milkdown/plugin-listener": "6.1.3",
>     "@milkdown/plugin-menu": "6.1.3",
>     "@milkdown/preset-commonmark": "6.1.3",
>     "@milkdown/preset-gfm": "6.1.3",
>     "@milkdown/prose": "6.1.3",
>     "@milkdown/react": "6.1.3",
>     "@milkdown/theme-nord": "6.1.3",
>     "@types/axios": "^0.14.0",
>     "@types/react": "^17.0.45",
>     "@types/react-dom": "^17.0.17",
>     "axios": "^0.27.2",
>     "clsx": "^1.1.1",
>     "mobx": "^6.6.0",
>     "mobx-react-lite": "^3.4.0",
>     "mobx-state-tree": "^5.1.5",
>     "react-dom": "^17.0.2",
>     "react-router-dom": "^6.3.0",
>     "react-scripts": "^4.0.3",
>     "typescript": "^4.7.2",
>     "web-vitals": "^2.1.4"
>   },
>   "devDependencies": {
>     "@types/react-router-dom": "^5.3.3",
>     "@typescript-eslint/eslint-plugin": "^5.26.0",
>     "@typescript-eslint/parser": "^5.26.0",
>     "eslint": "^7.32.0",
>     "eslint-config-airbnb": "^19.0.4",
>     "eslint-config-prettier": "^8.5.0",
>     "eslint-plugin-import": "^2.26.0",
>     "eslint-plugin-jsx-a11y": "^6.5.1",
>     "eslint-plugin-prettier": "^4.0.0",
>     "eslint-plugin-react": "^7.30.0",
>     "eslint-plugin-react-hooks": "^4.5.0",
>     "husky": "^8.0.1",
>     "lint-staged": "^12.4.2",
>     "mst-middlewares": "^5.1.5",
>     "prettier": "2.6.2",
>     "react": "^17.0.2",
>     "react-app-rewired": "^2.2.1",
>     "remotedev": "^0.2.9"
>   },
>   "scripts": {
>     "start": "react-scripts start",
>     "build": "react-app-rewired build",
>     "eject": "react-scripts eject",
>     "lint": "eslint --cache --fix src/**/*.{js,jsx,ts,tsx,json}",
>     "format": "prettier --write 'src/**/*.{js,jsx,ts,tsx,css,md,json}'",
>     "prepare": "husky install"
>   },
>   "browserslist": {
>     "production": [
>       ">0.2%",
>       "not dead",
>       "not op_mini all"
>     ],
>     "development": [
>       "last 1 chrome version",
>       "last 1 firefox version",
>       "last 1 safari version"
>     ]
>   },
>   "lint-staged": {
>     "*.(j|t)s(x)": "eslint --fix",
>     "*.{js,ts,tsx,jsx,md,yml,json}": "prettier --write"
>   },
>   "engines": {
>     "node": "^16.0.0"
>   }
> }

Help me, please!

**Comment by Saul-Mirone** [comment]
What's your cra version?

**Comment by valVk** [comment]
Are there any ways to use milkdown with webpack@4?
Because unfortunately it could not be used in NuxtJS@2

Thanks in advance

cc @Saul-Mirone
