### ISSUE TITLE
left-click to follow url

### ISSUE THREAD

**Issue by benatkin** [Saul-Mirone/milkdown#55]
It looks like from a UX standpoint it would work fine to be able to left-click and follow a URL. If you select text it shows both the formatting bar on the top and the URL bar on the bottom. If it just showed the URL bar when you left-click, I don't think that would get in the way of selecting. I think it would need to disappear when typing, until it gets clicked again.

<img width="409" alt="Captura de Pantalla 2021-07-08 a la(s) 13 25 09" src="https://user-images.githubusercontent.com/4126/124985976-ecec0280-dfef-11eb-81de-7ed90f5a1386.png">

A way to open a link with the keyboard would be handy.

**Comment by Saul-Mirone** [comment]
Thanks for your suggestion! I thinks what you said makes sense so I'll optimize the UX.

**Comment by Saul-Mirone** [comment]
Done in main branch.
