### ISSUE TITLE
[Bug] mark don't work right  

### ISSUE THREAD

**Issue by 4-1-1** [Saul-Mirone/milkdown#553]
**Describe the bug**

**To Reproduce**
```typescript
import React from 'react';
import { render } from 'react-dom';

import { Milkdown } from './component/milkdown';

const markdown = `
abc**'de**
`;

const App: React.FC = () => {
    return <Milkdown value={markdown} />;
};

render(<App />, document.getElementById('app'));
```

**Expected behavior**
It should be bold  'de

**Screenshots**
<img width="412" alt="image" src="https://user-images.githubusercontent.com/4401981/172628500-e9c0115f-569d-46fd-9c46-ac6156cb3237.png">

**Desktop (please complete the following information):**

-   OS: [e.g. iOS] macos
-   Browser [e.g. chrome, safari] chrome
-   Version [e.g. 22] 101

milkdown version 6.1.3

**Additional context**

**Comment by 4-1-1** [comment]
ok ,But some editor works with it。 And the real problem is to bold "'xxx'" with the tooltip menu, and save to preview agian , the bold style gone

**Comment by Saul-Mirone** [comment]
That's a bug I think.

**Comment by Saul-Mirone** [comment]
Seems it's about Example 358.
https://spec.commonmark.org/0.30/#emphasis-and-strong-emphasis
<img width="884" alt="Screen Shot 2022-06-09 at 12 27 30" src="https://user-images.githubusercontent.com/10047788/172764217-e5fecdb7-213e-4257-9a57-cb3332ee5e49.png">

**Comment by 4-1-1** [comment]
Do you have any plan, to support it ? or update the input rules and mark command?

**Comment by Saul-Mirone** [comment]
I'll figure out how to do it when I have time.
