### ISSUE TITLE
[Bug] Unable to add links to images

### ISSUE THREAD

**Issue by mpociot** [Saul-Mirone/milkdown#555]
**Describe the bug**
Right now it is not possible to add a link to an image using the menu plugin. 

When clicking on an image, the "image settings" open up. When you then click on the "link" menu item, the image settings are still visible. After closing/saving them, you see the link input field - but entering anything in there does not get applied to the image.

**To Reproduce**

1. Go to the Milkdown online demo: https://milkdown.dev/online-demo
2. Click on the polar bear 👋 
3. Click on the "link" menu item

**Expected behavior**
When clicking on an image, I would expect the image settings to show up - just as they do right now.
When clicking on the link icon, the image settings should close and the link settings should show up instead.
Saving them should append the link to the image tag. Clicking on the link icon should also add the ability to remove the link from the image

**Comment by Saul-Mirone** [comment]
I get you point, let me think about it.
