### ISSUE TITLE
[Feature] Enable writing in markdown

### ISSUE THREAD

**Issue by djcoin** [Saul-Mirone/milkdown#559]
Hi,

I must have missed it but I can't find any example which shows how to display raw markdown (not to mention being able to edit it).

Is Milkdown a wysiwyg-only editor or does it provide a way to display and write markdown, say in separate view, as it's very common to be seen in other editors?

Thanks a lot

**Comment by Saul-Mirone** [comment]
Hi, it's a wysiwyg only editor. If you want to enable raw markdown, you can integrate a code editor such as https://codemirror.net/ with milkdown to do that, like what we do in online demo.

**Comment by djcoin** [comment]
Hi Mirone,

oh I didn't see the top/right icon. Is the code of the online demo website available somewhere, or a quick example demonstrating integration?

I stumbled upon a [comment](https://news.ycombinator.com/item?id=28007982) that was also looking for a way to get this view ("In Typora I can just press Ctrl+Slash").

I was just looking for a simple integration, not much (but indeed it would have been great if scrolling was synchronized for example).

Thanks

**Comment by Saul-Mirone** [comment]
Full code is available here:
https://github.com/Saul-Mirone/milkdown/blob/main/gh-pages/component/Demo/Demo.tsx
