### ISSUE TITLE
Remove prosemirror-tables from dependencies because it seems no longer maintaned.

### ISSUE THREAD

**Issue by Saul-Mirone** [Saul-Mirone/milkdown#566]
https://discuss.prosemirror.net/t/why-is-prosemirror-tables-not-maintained/4522

**Comment by frnhr** [comment]
At a glance, it seems there is some recent activity on [prosemirror-tables](https://github.com/ProseMirror/prosemirror-tables). Is that real maintenance activity that would enable tables to work again in milkdown?

**Comment by Saul-Mirone** [comment]
> At a glance, it seems there is some recent activity on [prosemirror-tables](https://github.com/ProseMirror/prosemirror-tables). Is that real maintenance activity that would enable tables to work again in milkdown?

Yep, in main branch I added it back :)
