### ISSUE TITLE
[Bug] Two softbreaks at the end of the document cause weird behavior

### ISSUE THREAD

**Issue by fb-datax** [Saul-Mirone/milkdown#568]
**Describe the bug**
Two softbreaks at the end of the document cause weird behavior

**To Reproduce**

* Insert Text
* Add two softbreak at the end
* Apply the resulting markdown again to the component

**Screenshots**
![20220615-bug-softbreaks](https://user-images.githubusercontent.com/7262103/173822724-a9c197b4-d585-4aff-ba58-99e7da2844c4.gif)

**Milkdown version**
Latest

**Desktop (please complete the following information):**

-   OS: Win, Linux
-   Browser Chrome, FF, etc
-   Version latest

**Comment by fb-datax** [comment]
Thanks!
Is there an E.T.A. for the for the next release which includes this fix?

**Comment by Saul-Mirone** [comment]
> Thanks!
> 
> Is there an E.T.A. for the for the next release which includes this fix?

I think it will be within next week.
