### ISSUE TITLE
[Bug] Update in react nodeview will cause crash in React@17

### ISSUE THREAD

**Issue by 4-1-1** [Saul-Mirone/milkdown#575]
**Describe the bug**
Run with react 17.0.2
**To Reproduce**

1. render with readonly true
2. set readonly to false

```typescript
 const { editor, loading, getInstance } = useEditor(
        (root, renderReact) => {
            return createEditor({
                root,
                defaultValue: content,
                readOnly,
                setMentionState,
                onChange,
                domHandler: editorProps.domHandler,
                renderReact,
                inputRef: inputRef.current || undefined,
                LinkComponent: NewLink,
                ImageComponent: NewImage,
                markdownPasteHandler: filterUnSupportDirective,
            });
        },
        [readOnly, NewLink],
    );
    useEffect(() => {
        if (!loading) {
            const editor = getInstance();
            editorRef.current = editor;
            editor?.action((ctx) => {
                const view = ctx.get(editorViewCtx);
                const commandManager = ctx.get(commandsCtx);
                const serializer = ctx.get(serializerCtx);
                setEditorReady(view, commandManager, serializer);
            });
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [editorRef, loading, setEditorReady]);

    return (
        <div style={{ position: 'relative' }}>
            <ReactEditor editor={editor} />
            <input ref={inputRef} type="file" accept="image/*" style={{ display: 'none' }} />
        </div>
    );
```

**Expected behavior**

**Screenshots**
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/4401981/174783718-cbce62c9-3e35-4214-8c85-35162bf389e1.png">

**Milkdown version**
6.1.5

**Desktop (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari] chrome 102
-   Version [e.g. 22]

**Smartphone (please complete the following information):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**

**Comment by Saul-Mirone** [comment]
It's a new feature in v6.2 and hasn't been released.

**Comment by 4-1-1** [comment]
Ok , I should cherry-pick the new plugin, do some test thing

**Comment by 4-1-1** [comment]
@Saul-Mirone It's still happen in the release version 6.2.
You can change the examples of react.  

step1 :back the react version to 17.0.2

step2: 
```typescript
import './style.css';

import React, { StrictMode } from 'react';
import { render } from 'react-dom';

import { Milkdown } from './component/milkdown';

const markdown = `
# Milkdown React Test

> Milkdown is an editor.

\`\`\`javascript [Sample]
const milkdown = new Milkdown();
milkdown.create();
\`\`\`

---

![20220620195536-image.png](hell.png)

Now you can play!
`;

const App: React.FC = () => {
    return <Milkdown value={markdown} />;
};

const root$ = document.getElementById('app');
if (!root$) {
    throw new Error('No root element found');
}

// const root = createRoot(root$);

render(
    <StrictMode>
        <App />
    </StrictMode>,
    root$,
);
```

step3:  open the website , and backspace the image

**Comment by Saul-Mirone** [comment]
https://codesandbox.io/s/objective-zeh-hx6dlp?file=/src/App.js
Don't see any problem here.

**Comment by 4-1-1** [comment]
> https://codesandbox.io/s/objective-zeh-hx6dlp?file=/src/App.js Don't see any problem here.

It need to use custom Component with renderReact,
checkout this one https://codesandbox.io/s/cool-elion-zrquoj?file=/src/App.js

**Comment by Saul-Mirone** [comment]
Still don't know why code works in react 18 cannot work in react 17.

**Comment by 4-1-1** [comment]
> Still don't know why code works in react 18 cannot work in react 17.

I have try to resolve it several day. No clues either

**Comment by 4-1-1** [comment]
@Saul-Mirone Are u resolving this problem. Do you have any clues or suggest.Maybe we should report it to react?

**Comment by 4-1-1** [comment]
https://codesandbox.io/s/icy-waterfall-jcg872
@Saul-Mirone look out the Link component and the finally dom tree, it seems like prosemirror will change react children.

**Comment by 4-1-1** [comment]
milkdown6.3 and  react 17.0.2 

when use React component to link,  the render result is wired, My comopent is  'a', but I got a 'span' in the dom

https://codesandbox.io/s/eager-hypatia-2hpveu?file=/src/App.js

**Comment by Saul-Mirone** [comment]
Should be fixed by https://github.com/Saul-Mirone/milkdown/commit/5ce4335bd76e97a4d450bb4fd648e2a698f14ec8

**Comment by 4-1-1** [comment]
👍
