### ISSUE TITLE
[Bug]代码块无法重新指定代码语言

### ISSUE THREAD

**Issue by dreamncn** [Saul-Mirone/milkdown#577]
**Describe the bug**

代码块中指定代码语言处存在无法修改的问题

**To Reproduce**

1. 编写时指定不存在列表中语言
<img width="521" alt="image" src="https://user-images.githubusercontent.com/37787014/175073774-b84d1837-ca9c-437b-96d9-6279c8cb71b7.png">

2. 这样新生成的代码块语言列表中没有该语言
<img width="440" alt="image" src="https://user-images.githubusercontent.com/37787014/175074075-713dbb30-e770-438f-a08f-8655e007a408.png">

3. 如果此时发现存在拼写之类的错误改起来非常麻烦

<img width="374" alt="image" src="https://user-images.githubusercontent.com/37787014/175074348-c04630ea-d448-48a5-99b1-7b13415999fe.png">

**Solution** 

1. 个人感觉，能写代码块的至少知道自己的这块代码是什么语言，可以不用专门做成列表供选择（代码语言那么多，全放进来肯定不现实），可以学typora使用联想功能：
<img width="265" alt="image" src="https://user-images.githubusercontent.com/37787014/175074566-51541b93-ada8-43d5-a887-684bc94336f2.png">
2. 另外语言部分也可以像typroa一样，做成隐藏的，只有在这个位置有焦点才显示语言输入框，修改起来也比较方便。
<img width="992" alt="image" src="https://user-images.githubusercontent.com/37787014/175075555-8771af51-db66-4a31-80b8-00b4f1db2c1c.png">

**Milkdown version**
List the versions of milkdown packages you have here.

```json
 "@milkdown/core": "^6.1.5",
    "@milkdown/preset-commonmark": "^6.1.5",
    "@milkdown/prose": "^6.1.5",
    "@milkdown/theme-nord": "^6.1.5",
    "@milkdown/utils": "^6.1.5",
    "@milkdown/vue": "^6.1.5",
    "core-js": "^3.8.3",
    "prosemirror-inputrules": "^1.2.0",
    "prosemirror-model": "^1.18.1",
    "remark-directive": "^2.0.1",
    "unist-util-visit": "^4.1.0",
    "vue": "^3.2.13"
```

**Desktop (please complete the following information):**

-   OS: MacOS
-   Browser : Chrome
-   Version: 102

**Comment by Saul-Mirone** [comment]
Language options can be configured
https://github.com/Saul-Mirone/milkdown/blob/main/packages/preset-commonmark/src/node/code-fence.ts#L13
