### ISSUE TITLE
[Bug] Heading in Menu is displayed in incorrect position

### ISSUE THREAD

**Issue by so1ve** [Saul-Mirone/milkdown#587]
**Describe the bug**
Heading in Menu is displayed in incorrect position

**To Reproduce**
See [online demo](https://milkdown.dev/online-demo).

**Expected behavior**
The heading selector should appear in the correct place

**Screenshots**
![demo site](https://user-images.githubusercontent.com/58381667/176186714-8ea21b8e-d449-4d87-bbb3-11365452b7ac.png)

![my usecase](https://user-images.githubusercontent.com/58381667/176187019-1636a237-3ca1-44a2-86b6-0c31c4460e19.png)

**Milkdown version**
6.2.0

**Desktop (please complete the following information):**

-   OS: Windows 11 - 22621.160
-   Browser: Edge
-   Version: 103.0.1264.37

**Comment by maartenbreddels** [comment]
I had a similar issue, because the parent div I put milkdown is was offset from the left. Putting this CSS for me fixed it:
```css
.solara-milkdown {
  position: relative; /* since the dropdown uses position absolute */
}
```
