### ISSUE TITLE
[Bug] Wired table editing in safari

### ISSUE THREAD

**Issue by 4-1-1** [Saul-Mirone/milkdown#592]
**Describe the bug**
Table columns changed wrong

**To Reproduce**

1. https://codesandbox.io/s/eager-hoover-yeum6d?file=/src/App.js 

**Expected behavior**
Table columns do not change
**Screenshots**

https://user-images.githubusercontent.com/4401981/176838650-aced51c4-b449-4c5e-afd6-627ec177d52d.mp4

**Milkdown version**
6.2.0

**Desktop (please complete the following information):**

-   OS: macOS

-   Browser [ safari]
-   Version [e.g. 22]

**Smartphone (please complete the following information):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**

**Comment by Saul-Mirone** [comment]
I'll take a look later.
