### ISSUE TITLE
[Bug]There are two instances of milkdown when changing defaultValue dynamically

### ISSUE THREAD

**Issue by so1ve** [Saul-Mirone/milkdown#598]
**Describe the bug**
There are two instances of milkdown when changing defaultValue dynamically

`MilkdownEditor.tsx`
```tsx
import type { FC } from "react";
import { Editor, defaultValueCtx, rootCtx } from "@milkdown/core";
import { ReactEditor, useEditor } from "@milkdown/react";
import { listener, listenerCtx } from "@milkdown/plugin-listener";
import { milkdownPlugins } from "@dolan-x/milkdown-plugins";

import "prism-themes/themes/prism-nord.css";

interface MilkdownEditorProps {
  disabled?: boolean
  value?: string
  onChange?: (s: string) => void
}
const MilkdownEditor: FC<MilkdownEditorProps> = ({ value, onChange, disabled }) => {
  const { editor } = useEditor((root) => {
    const e = Editor.make()
      .config((ctx) => {
        ctx.set(rootCtx, root);
        value && ctx.set(defaultValueCtx, value);
        if (onChange && !disabled) {
          ctx.get(listenerCtx).markdownUpdated((_ctx, markdown, _prevMarkdown) => {
            onChange(markdown);
          });
        }
      })
      .use(listener)
      .use(milkdownPlugins);

    return e;
  }
  , [value],
  );

  return <ReactEditor editor={editor} />;
};

export default MilkdownEditor;

```

`Page.tsx`
```tsx
const EditPost: FC = () => {
  const [content, setContent] = useState("");

  function onFetch () {
    setContent('abcd')
  }
  useEffect(onFetch, []);

  const Milkdown = <MilkdownEditor value={content} onChange={setContent} />;

  return (
    <div>
      {Milkdown}
    </div>
  );
};

export default EditPost;

```

**Expected behavior**
One instance only

**Screenshots**
![](https://user-images.githubusercontent.com/58381667/177366979-47d27caf-41a6-426d-a4fa-7fcf53b6b679.png)

**Milkdown version**
6.2.0

**Desktop (please complete the following information):**

-   OS: Windows 11
-   Browser: Edge
-   Version: 103.0.1264.44

**Comment by so1ve** [comment]
However, once Vite is hot-updated or the content of the editor is manually modified, redundant instances will disappear.

**Comment by Saul-Mirone** [comment]
Why're you recreating a new editor everytime the content is changed?

**Comment by so1ve** [comment]
Not quite sure what I should do, could you please give some advice?

**Comment by Saul-Mirone** [comment]
They're not same, in my code the`onChange` won't cause the `md` state change. But in your code, the `onChange` will cause the `content` change, which means everytime user input anything, the onChange will update the content and a new editor will be created.

You should treat milkdown editor as an [uncontrolled component](https://reactjs.org/docs/uncontrolled-components.html)

**Comment by so1ve** [comment]
Thanks!

**Comment by so1ve** [comment]
But...I still don't quite know what I should do...

**Comment by so1ve** [comment]
Sorry, it works now

**Comment by ningkehua** [comment]
> Sorry, it works now

hi，how did you solve this problem before？I want to wrap milkdown-editor as a form-item...

**Comment by so1ve** [comment]
> hi，how did you solve this problem before？I want to wrap milkdown-editor as a form-item...

The issue is a little bit stale and I forgot what I have done :(

but you can checkout https://github.com/dolan-x/dolan-admin/blob/main/src/components

**Comment by ningkehua** [comment]
> 

ok，thanks a lot！

> > hi，how did you solve this problem before？I want to wrap milkdown-editor as a form-item...
> 
> The issue is a little bit stale and I forgot what I have done :(
> 
> but you can checkout https://github.com/dolan-x/dolan-admin/blob/main/src/components/MilkdownEditor.tsx. It uses an older version of milkdown so it might not work in the new version.
> 
> I'm using milkdown in vue now so I no longer get this issue. In the link I may not use React properly. Hope this will help.

ok，thanks a lot！
