### ISSUE TITLE
Comparison to Typora?

### ISSUE THREAD

**Issue by ice1000** [Saul-Mirone/milkdown#6]
I wonder how this project compares to Typora apart from the looking and the license. Thank you!

Also I'm wondering about math support. Is kAtEx or mATHjAX planned?

**Comment by Saul-Mirone** [comment]
Typora is a software and can only be used as a desktop app. However, milkdown is designed to be a front-end library and can be used by everynone. In terms of design, milkdown will provide a simple core, complicated features will be supported by plugin so users can choose which feature they would like to involve.

**Comment by Saul-Mirone** [comment]
Hi @ice1000 , the latex feature has been supported, you can try it online, feel free to open disscussions and issues for any ideas.
