### ISSUE TITLE
[Bug] Task list status can't change

### ISSUE THREAD

**Issue by iqiziqi** [Saul-Mirone/milkdown#601]
**Describe the bug**
task list can't click

**To Reproduce**

1. Go to '[online-demo](https://milkdown.dev/online-demo)'
2. Click one of task list

**Expected behavior**
The task list item status change

**Screenshots**

![image](https://user-images.githubusercontent.com/8640316/178060254-c87d3e09-b33f-43de-91c8-f164832a3189.png)
![image](https://user-images.githubusercontent.com/8640316/178060331-6b9d9907-73fb-4c90-ab63-7db1e8068e55.png)

**Milkdown version**
- 6.1.5

**Desktop (please complete the following information):**

-   OS: [Windows 10]
-   Browser [Firefox]
-   Version [102.0]

**Comment by Saul-Mirone** [comment]
Can reproduce on my side.

**Comment by iqiziqi** [comment]
I'm sorry. I think it's probably not milkdown's bug. It's work fine when i disable firefox‘s bitwarden add-on.
