### ISSUE TITLE
[Bug] Code fence without language renders wrong markdown

### ISSUE THREAD

**Issue by emcfarlane** [Saul-Mirone/milkdown#604]
Removing the lang on code block renders the markdown as the code but without the backticks.

**To Reproduce**

1. Go to https://milkdown.dev/online-demo
2.  View the source next to the editor.
3. Remove the language
4. See error:

**Expected behavior**
Should have  `` ``` `` without langugage tag.

````
```
function main() {
    console.log('Hello milkdown!');
}
```
````

**Screenshots**
<img width="1410" alt="Screenshot 2022-07-11 at 17 19 47" src="https://user-images.githubusercontent.com/3036610/178310938-2268d815-167d-49e5-8f9b-7009bce2ba0d.png">

**Milkdown version**
6.2.0

**Desktop (please complete the following information):**

-   macOS
-   Chrome
-    103.0.5060.114 (Official Build) (x86_64)

**Comment by Saul-Mirone** [comment]
That's a valid markdown syntax and the behavior is controlled by remark, you may want to pass [options](https://github.com/remarkjs/remark/tree/main/packages/remark-stringify#optionsfences) to remark to control the behavior.

**Comment by emcfarlane** [comment]
Ah right! Sorry I had never seen indents used before. Thanks!

**Comment by emcfarlane** [comment]
Accomplished this with:

```
        ctx.update(remarkCtx, (remark) => {
          return remark.data("settings", {
            fences: true,
          });
        });
```
From https://github.com/remarkjs/remark/tree/main/packages/remark#example-passing-options-to-remark-stringify
