### ISSUE TITLE
当我 使用这个插件"@milkdown/plugin-block": "^6.2.0"报错

### ISSUE THREAD

**Issue by blog-xylia** [Saul-Mirone/milkdown#610]
当我 使用这个插件"@milkdown/plugin-block": "^6.2.0"报错，是我缺少什么吗
![image](https://user-images.githubusercontent.com/40161722/179184173-3db3f907-e204-42e7-9f47-70d0081969e2.png)
![image](https://user-images.githubusercontent.com/40161722/179183973-44dc3c7d-e4f1-4ae2-b578-14017f95da9b.png)

**Comment by Saul-Mirone** [comment]
You should use ^6.3.0, together with `@milkdown/prose@^6.3.0`.

**Comment by blog-xylia** [comment]
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/40161722/179186789-c9c61827-5bbb-4d32-989b-612f7eca87a3.png">
我想问一下这个拖拽的功能是这个块吧，然后我用的时候没有出现，有没有例子提供我看一下，谢谢

**Comment by Saul-Mirone** [comment]
https://codesandbox.io/s/sleepy-nobel-4icgur?file=/src/index.ts
