### ISSUE TITLE
[Bug] Can't do hardbreak('Shift-Enter') in code block

### ISSUE THREAD

**Issue by otkmnb2783** [Saul-Mirone/milkdown#614]
**Describe the bug**

hardbreak('Shift-Enter') in code block causes error.

**To Reproduce**

1. Focus on code block
2. enter text
3. hardbreak[shift+enter]

**Expected behavior**
Line break in text mode.

**Screenshots**
<img width="1670" alt="code_block_hardbreak_error" src="https://user-images.githubusercontent.com/3377349/179648727-3e2fec11-b375-464e-91c9-4c64b0c41405.png">

**Milkdown version**

- 6.2.0
- 6.3.0

**Desktop (please complete the following information):**

- OS: macOS Monterey 12.4
- Browser: chrome
- Version 103.0.5060.114 (Official Build) （x86_64） 

**Smartphone (please complete the following information):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**

**Comment by Saul-Mirone** [comment]
Hardbreak won't work in code block. I'll fix the error here but the right behavior is that it's just generate a normal line break.
