### ISSUE TITLE
[Bug] input rules in inlineCode should keep code. 

### ISSUE THREAD

**Issue by 4-1-1** [Saul-Mirone/milkdown#622]
**Describe the bug**

All punctuation in an inline code should be reserved.
**To Reproduce**

input \`\*a\*\`
got a bold in an inline code.

**Expected behavior**

**Screenshots**
<img width="179" alt="image" src="https://user-images.githubusercontent.com/4401981/180175227-525c27bb-1d21-42b5-8a3a-a36ca281dde4.png">

**Milkdown version**
List the versions of milkdown packages you have here.

**Desktop (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [chrome]
-   Version [6.3]

**Smartphone (please complete the following information):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**

**Comment by 4-1-1** [comment]
https://codesandbox.io/s/eager-hypatia-2hpveu?file=/src/App.js

Just input three *

<img width="482" alt="image" src="https://user-images.githubusercontent.com/4401981/180356503-115807e5-38fe-4413-9147-3a038af077a0.png">

**Comment by 4-1-1** [comment]
<img width="659" alt="image" src="https://user-images.githubusercontent.com/4401981/182085561-bb8e7a51-5bf6-4ccd-a64e-8d4081166a05.png">

Just one line code

**Comment by Saul-Mirone** [comment]
> <img alt="image" width="659" src="https://user-images.githubusercontent.com/4401981/182085561-bb8e7a51-5bf6-4ccd-a64e-8d4081166a05.png">
> 
> Just one line code

Not that simple, this will break something like **`bold code`**

**Comment by 4-1-1** [comment]
if you mean bold the text in code . `**bold**`.
it should be break

**Comment by Saul-Mirone** [comment]
**`bold code`**

```markdown
**`bold code`**
```

**Comment by stan12138** [comment]
I have same problem。when I want input someting like: 
the data_name should not same with data_label

in other markdown software like typora，I should input:
~~~
the `data_name` should not same with `data_label`
~~~
It will be like this:
<img width="469" alt="image" src="https://user-images.githubusercontent.com/20102702/184318602-3575b36c-00e9-44cb-a5d4-3886639e1ded.png">

but in milkdown it will be like this:
<img width="540" alt="image" src="https://user-images.githubusercontent.com/20102702/184318734-eec77762-cdc1-4dd4-bd87-c698c1bdf496.png">
