### ISSUE TITLE
[Bug] Space after bold word breaks bold format

### ISSUE THREAD

**Issue by fb-datax** [Saul-Mirone/milkdown#637]
**Describe the bug**
Adding a space after a bold word adds the space between the word and the two asterisks

**Expected behavior**
Space added after the asterisks

**Screenshots**
![20220726-space-breaks-bold](https://user-images.githubusercontent.com/7262103/180941937-29ab124c-e45e-4fb2-8d2e-32d5283eaa32.gif)

**Milkdown version**
Latest on milkdown.dev

**Comment by Saul-Mirone** [comment]
https://github.com/Saul-Mirone/milkdown/pull/695
