### ISSUE TITLE
[Feature] Can there be a way to support rehype-raw?

### ISSUE THREAD

**Issue by so1ve** [Saul-Mirone/milkdown#639]
Can there be a way to support rehype-raw?

Yes, I read the previous issue and found that you are not going to support html.

rehype-raw depends on remark-rehype. I can't seem to get it to work with milkdown.

I'm using milkdown for my backend editor for my personal blog, and sometimes I want to insert direct html snippets instead of using remark-directive. I don't know how to use rehype-raw inside milkdown.

**Comment by Saul-Mirone** [comment]
Since remark is just a special instance of unified, what's the problem if you just use rehype-raw as a remark plugin?
https://github.com/remarkjs/remark/blob/main/packages/remark/index.js#L5

**Comment by so1ve** [comment]
what should I do? is that so?

```ts
import { $remark } from "@milkdown/utils";
import rehypeRaw from "rehype-raw";

export const raw = $remark(() => rehypeRaw);
```

I don't think it's right

**Comment by Saul-Mirone** [comment]
That's right, do you meet any problem if you use this method?

**Comment by Saul-Mirone** [comment]
I see, seems this plugin will transform the AST.

**Comment by Saul-Mirone** [comment]
OK, I see the problem here. rehype-raw will only work with remark-rehype. However, remark-rehype will generate html nodes instead of AST. So, if you want milkdown to work with remark-rehype. You'll need to some plugins to make html nodes generated by remark-rehype can be transformed into prosemirror nodes.

**Comment by so1ve** [comment]
It might be a bit presumptuous, but could you please provide a simple implementation? I don't know how to operate prosemirror

**Comment by so1ve** [comment]
Maybe I can implement one myself based on the mermaid plugin.

**Comment by Saul-Mirone** [comment]
I don't have a laptop now because I'm on vacation.

**Comment by so1ve** [comment]
Have a great holiday! I will try to implement this feature myself

**Comment by Saul-Mirone** [comment]
Do you think this would be helpful?
https://milkdown.dev/interacting-with-editor#dom

In fact we support using dom as default value.

**Comment by so1ve** [comment]
Occur activity =)

**Comment by Saul-Mirone** [comment]
Do you still need any help?

**Comment by so1ve** [comment]
How can I pass HTML into Milkdown?

**Comment by so1ve** [comment]
I want to insert HTML directly into Milkdown, but it seems to be filtered.
