### ISSUE TITLE
[Bug] an extra editor will be render when load markdown

### ISSUE THREAD

**Issue by shlroland** [Saul-Mirone/milkdown#640]
**Describe the bug**
an extra editor will be render when load markdown

**To Reproduce**

I copied online-demo from website dir, but went wrong

**Expected behavior**

**Screenshots**
there's an attachment in this issue
#550 

**Milkdown version**
    "@milkdown/core": "^6.3.1",
    "@milkdown/plugin-block": "^6.3.1",
    "@milkdown/plugin-clipboard": "^6.3.1",
    "@milkdown/plugin-cursor": "^6.3.1",
    "@milkdown/plugin-diagram": "^6.3.1",
    "@milkdown/plugin-emoji": "^6.3.1",
    "@milkdown/plugin-history": "^6.3.1",
    "@milkdown/plugin-indent": "^6.3.1",
    "@milkdown/plugin-listener": "^6.3.1",
    "@milkdown/plugin-math": "^6.3.1",
    "@milkdown/plugin-menu": "^6.3.1",
    "@milkdown/plugin-prism": "^6.3.1",
    "@milkdown/plugin-slash": "^6.3.1",
    "@milkdown/plugin-tooltip": "^6.3.1",
    "@milkdown/plugin-trailing": "^6.3.1",
    "@milkdown/plugin-upload": "^6.3.1",
    "@milkdown/preset-commonmark": "^6.3.1",
    "@milkdown/preset-gfm": "^6.3.1",
    "@milkdown/prose": "^6.3.1",
    "@milkdown/react": "^6.3.1",
    "@milkdown/theme-nord": "^6.3.1",
"react": "^18.2.0",
    "react-dom": "^18.2.0",
**Desktop (please complete the following information):**

-   OS: [e.g. iOS] macos 12.5
-   Browser [e.g. chrome, safari] chrome
-   Version [e.g. 22] 103

**Additional context**

**Comment by Saul-Mirone** [comment]
Remove your StrrictMode component.

**Comment by shlroland** [comment]
> Remove your StrrictMode component.

I know that remove StrictMode will resolve this error， but I want to keep StrictMode. And in #550 ,you said the fixed this error in React 18 StrictMode, so why this wrong happened again ?

**Comment by Saul-Mirone** [comment]
It's fixed. But my code in website didn't handle it properly. You shouldn't copy that.
https://codesandbox.io/s/lingering-tdd-mesrc7?file=/src/App.js
