### ISSUE TITLE
[Feature] Unfurl a pasted link

### ISSUE THREAD

**Issue by that-dom** [Saul-Mirone/milkdown#641]
Unfurling links that are pasted in the editor would be great. Unfurling is used by Slack to pull in a small amount of information and often times embedded players if it's video content.
Good article on unfurling https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254

**Comment by Saul-Mirone** [comment]
Interesting feature, I would really love to see someone could mke it a community plugin.

**Comment by knownasilya** [comment]
Any ideas if this has been done?

**Comment by Saul-Mirone** [comment]
> Any ideas if this has been done?

As mentioned above. This feature hasn't been part of the official plugins.
