### ISSUE TITLE
[Bug] Context "color" not found

### ISSUE THREAD

**Issue by LittleSound** [Saul-Mirone/milkdown#649]
**Describe the bug**

I encountered the following error when using `Milkdown` in a `Monorepo`:
> MilkdownError: Context "color" not found, do you forget to inject it?

**Screenshots**

<img width="750" alt="image" src="https://user-images.githubusercontent.com/19204772/182304416-33a3f2e9-cc2d-4513-b2ca-8f2e1307dff6.png">

**To Reproduce**
This issue must be reproduced using `pnpm`, as it is not a problem when using `npm`. my pnpm version: 7.1.1
So I have no way to reproduce using the online playground, you can download this zip file I prepared for reproduction.
### [milkdown-issues-649-demo.zip](https://github.com/Saul-Mirone/milkdown/files/9247846/milkdown-issues-649-demo.zip)

**Milkdown version**
```json
"dependencies": {
    "@material-design-icons/font": "^0.11.7",
    "@milkdown/core": "^6.3.1",
    "@milkdown/plugin-listener": "^6.3.1",
    "@milkdown/plugin-menu": "^6.3.1",
    "@milkdown/plugin-upload": "^6.3.1",
    "@milkdown/preset-commonmark": "^6.3.1",
    "@milkdown/prose": "^6.3.1",
    "@milkdown/theme-nord": "^6.3.1",
    "@milkdown/utils": "^6.3.1",
    "@milkdown/vue": "^6.3.1",
}
```

**Additional context**

I see that there is a fix for this issue: issues: #427, and I'm already using the `v6.3.1` version with the patch, but that doesn't solve the problem.
I spent a lot of time checking the code and debugging, but no luck; in the process I found a lot of places in the milkdown source code using `v6.0.1` as `peerDependencies`, could this be the cause of the problem?

<img width="513" alt="image" src="https://user-images.githubusercontent.com/19204772/182305630-ec4d05a3-ee1d-48d3-8b4e-5ea47bd4b0fb.png">

**Comment by Saul-Mirone** [comment]
How to reproduce this?

**Comment by LittleSound** [comment]
> How to reproduce this?

Thank you. I just added the **To Reproduce** information to the description, please check it out.

**Comment by Saul-Mirone** [comment]
Seems you have multiple milkdown core installed in your node_modules. You can try:

1. Keep `@milkdown/prose` and `@milkdown/core` appear in one repo's `package.json`.
2. Or extract them to the root package.json

**Comment by LittleSound** [comment]
Thanks, this does work.

If I want to have @milkdown/core as `devDependencies` and `peerDependencies` dependencies in the core package and as `dependencies` dependencies in the example package, is there a possible solution?

For example, a way to resolve a conflict between two `vue` dependencies is to add `dedupe: ['vue']` to `vite.config.ts`.
(This does not work on milkdown)
```ts
export default defineConfig({
  resolve: {
    dedupe: ['vue'],
  }
})
```

**Comment by Saul-Mirone** [comment]
You need to add both `@milkdown/prose` and `@milkdown/core`, clean your node_modules and pnpm-lock and install agian. I've tried that and everything seems work.

**Comment by LittleSound** [comment]
This does work because there is a dependency between `@milkdown/prose` and `@milkdown/core`?

**Comment by Saul-Mirone** [comment]
I think so. Seems it auto installed the peer dep it needs. But I'm also not sure if it's the root cause.
