### ISSUE TITLE
[Bug] Drag scrolling doesn't seem discoverable on demo page

### ISSUE THREAD

**Issue by benatkin** [Saul-Mirone/milkdown#650]
**Describe the bug**
On the demo page I noticed the drag handle, but when I tried using the drag handle to move the image to the bottom, outside of my screen, it didn't work, until I tried putting my mouse right before the end of the container. It seems to only be like 5 pixels.

**To Reproduce**

1. Go to https://milkdown.dev/online-demo
2. Hover over the polar bear image. Drag the drag handle down.

**Expected behavior**
I expect it to scroll down, but it doesn't. Later I find out that if I had gone to the exact bottom it would scroll. It seems to only be about 5 pixels.

**Milkdown version**
Site as of 2022-08-02

**Desktop (please complete the following information):**

-   OS: MacOS
-   Browser Chrome
-   Version Current Stable version as of 2022-08-02

**Additional context**
Increasing the range to double or triple what it is would probably make it discoverable. Ideally you would also be able to drag past the end of the widget. This might require adding an invisible overlay to capture mouse movement outside of the widget. Movement over the toolbar should probably also activate scrolling up.

**Comment by Saul-Mirone** [comment]
PR welcome :)
