### ISSUE TITLE
[Bug] Drag task-list-item into order-list, seems should to split the order-list

### ISSUE THREAD

**Issue by 4-1-1** [Saul-Mirone/milkdown#655]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

6.3

### Steps to reproduce

 Drag task-list-item into order-list

### Expected behavior

the order-list turn to 

 1.   list-item
 2. list-item

- [ ] task-list-item
 
1.  list-item

### Actual behavior

<img width="755" alt="image" src="https://user-images.githubusercontent.com/4401981/183230567-cf75dd64-b2ce-4946-933d-21dbc901cfbe.png">

### Runtime

Chrome

### OS

macOS

**Comment by Saul-Mirone** [comment]
That's the expected behavior, consider this:

1. 2
2. 212
3. [x] task
4. ok

**Comment by 4-1-1** [comment]
> That's the expected behavior, consider this:
> 
> 1. 2
> 2. 212
> 3. [x]  task
> 4. ok

But I am afraid the markdown rules not support this. the number of order-list  is control by css

**Comment by Saul-Mirone** [comment]
The markdown rules do support this. That's why I can leave a comment like this.
