### ISSUE TITLE
[Feature] Provide a command to hide all tooltip or inner editor, I want to calculate content actual height when exit.

### ISSUE THREAD

**Issue by ourongxing** [Saul-Mirone/milkdown#666]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

![](https://testmnbbs.oss-cn-zhangjiakou.aliyuncs.com/pic/20220811090630.png?x-oss-process=base_webp)

I want to calculate content actual height when exit, so I need hide this area or other tooltips.

### Solution

I don’t know if there are any ways, if so, please tell me.

### Alternatives

none

**Comment by Saul-Mirone** [comment]
You can try to move the selection to the end of all contents.

**Comment by Saul-Mirone** [comment]
You can also change the editor to readonly mode. In this mode there won't be any tooltip or inner editor.

**Comment by ourongxing** [comment]
> You can also change the editor to readonly mode. In this mode there won't be any tooltip or inner editor.
> 
> A simple example: [https://github.com/Saul-Mirone/milkdown/blob/main/examples/vanilla/main.ts#L37](https://github.com/Saul-Mirone/milkdown/blob/main/examples/vanilla/main.ts?rgh-link-date=2022-08-11T02%3A54%3A51Z#L37)

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/48356807/184066794-d3736305-09b3-4b55-bd05-c850f148ad40.png">

not work

**Comment by Saul-Mirone** [comment]
https://codesandbox.io/s/currying-cache-iebbt6?file=/src/index.ts

**Comment by ourongxing** [comment]
> [codesandbox.io/s/currying-cache-iebbt6?file=/src/index.ts](https://codesandbox.io/s/currying-cache-iebbt6?file=/src/index.ts)

It worked, thanks
