### ISSUE TITLE
[Bug] Why is latex tag not supported? But katex supports it.

### ISSUE THREAD

**Issue by ourongxing** [Saul-Mirone/milkdown#679]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

6.3.2

### Steps to reproduce

<img width="946" alt="image" src="https://user-images.githubusercontent.com/48356807/185053837-5e0c1f9e-62cd-4c2c-8878-d958233e308c.png">
<img width="818" alt="image" src="https://user-images.githubusercontent.com/48356807/185053979-ccac5e17-34b6-407d-9eb4-55ff15e3dc05.png">

### Expected behavior

Be the same as the above

### Actual behavior

Be the same as the above

### Runtime

Chrome

### OS

macOS

### Build and bundle tools

esbuild

**Comment by Saul-Mirone** [comment]
https://github.com/Saul-Mirone/milkdown/commit/7232d68ff85d546133efd22d40216008230ca49a

**Comment by Saul-Mirone** [comment]
https://milkdown.dev/online-demo?text=CTBQFEF4FkGED0BMACAOgFwIYHMDeBGAX1BFFCA%3D
