### ISSUE TITLE
[Bug] React custom component not working properly

### ISSUE THREAD

**Issue by hsirkar** [Saul-Mirone/milkdown#687]
### Initial checklist

- [x] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

6.3.2

### Link to runnable example

https://codesandbox.io/s/ecstatic-fermat-p87923?file=/src/App.js

### Steps to reproduce

Follow the [Custom Component for Node](https://milkdown.dev/react#custom-component-for-node) guide from docs:

```
import React from 'react';
import { Editor, rootCtx } from '@milkdown/core';
import { ReactEditor, useEditor, useNodeCtx } from '@milkdown/react';
import { commonmark, paragraph, image } from '@milkdown/preset-commonmark';

const CustomParagraph = ({ children }) => (
    <div className="react-paragraph">{children}</div>
);

const CustomImage = ({ children }) => {
    const { node } = useNodeCtx();

    return (
        <img
            className="react-image"
            src={node.attrs.src}
            alt={node.attrs.alt}
            title={node.attrs.title}
        />
    );
};

export const MilkdownEditor = () => {
    const {editor} = useEditor((root, renderReact) => {
        const nodes = commonmark
            .configure(paragraph, { view: renderReact(CustomParagraph) })
            .configure(image, { view: renderReact(CustomImage) });

        return Editor.make()
            .config(ctx => {
                ctx.set(rootCtx, root);
            })
            .use(nodes);
    });

    return <ReactEditor editor={editor} />;
};

export default MilkdownEditor;
```

### Expected behavior

We should be able to type in editor and edit as normal. Pressing enter after typing some words should go to the next line.

### Actual behavior

Type some words and press enter. The cursor stays on the same line.

New `CustomParagraph` components are being created but the focus stays on the current component.

### Runtime

Firefox, Electron

### OS

Windows

### Build and bundle tools

Create React App

**Comment by Saul-Mirone** [comment]
Please don't try to custom basic node such as `text` and `paragraph` node for now. It will cause unexpected behavior. It's a know issue but it's a kind of trade off. I'll update the document later.

**Comment by Saul-Mirone** [comment]
After reconsidering this issue, I think it's still important for users to do this. I'm working on a new repo called [prosemirror-adapter](https://github.com/Saul-Mirone/prosemirror-adapter) and I'll solve this issue there. After that, milkdown will use the adpater to render react and vue components.

**Comment by Saul-Mirone** [comment]
Closing this as it will be resolved by https://github.com/Saul-Mirone/milkdown/issues/823.
