### ISSUE TITLE
[Bug] Behavior on mobile (only Android) browser is inconsistent, especially around lists

### ISSUE THREAD

**Issue by yergom** [Saul-Mirone/milkdown#688]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

6.3.2

### Steps to reproduce

The following steps are reproducible in the [online demo](https://milkdown.dev/online-demo). You will need to use an Android phone. I've currently tested this on:

- OS: Android 11 (physical device) + Android Virtual Device (**Not reproducible on iOS**)
- Browser: Firefox & Chrome

I've also spent some time investigating Prosemirror's support of Android, and the following [post](https://discuss.prosemirror.net/t/contenteditable-on-android-is-the-absolute-worst/3810) summarizes all the problems with it.

I will indicate with ``_`` the location of the cursor. The simplest way to reproduce the issue is to create an unordered item

```markdown
  * Some content_
```
And press Return. I would have expected to move to a new line and create a new list item. However:
- On Firefox, I have to press enter twice
- On Chrome, the cursor stays in place, no matter how many times I press enter

There seem to be many other related issues. For example:

```markdown
  * Some content
  * _
```
Press Delete. I would have expected to remove the list item and move to the end of the previous item. However:
- On Firefox, after pressing Backspace 4/5 times, the cursor moves to the previous item, without deleting the current one
  ```markdown
    * Some content_
    * 
  ```
On Chrome, things get even weirder. Suppose that I have the following content:

```markdown
  * Some content
  * _
 More text
```
After pressing Backspace, ``More text`` moves into the list item and starts deleting from the front:

```markdown
  * Some content
  * _re text
```

I've tested other Prose Mirror based editors (like Remirror) and they all seem to have similar problems around lists. The basic prosemirror editor (found at https://prosemirror.net/) behaves correctly on Android.

### Expected behavior

--

### Actual behavior

--

### Runtime

Chrome, Firefox

### OS

Other (please specify in steps to reproduce)

**Comment by Saul-Mirone** [comment]
Can this be reproduced on Android 13?

**Comment by yergom** [comment]
I've tried in a virtual device with API level 33 (Android 13), still reproducible.

**Comment by Saul-Mirone** [comment]
Seems the reason is that on Android, when user tap the `delete`, it will trigger `Delete` in key code instead of `Backspace`, which cause the behavior.

**Comment by Saul-Mirone** [comment]
I'll try to remap the behavior.
