### ISSUE TITLE
[Bug] Error on freshly created CRA React app

### ISSUE THREAD

**Issue by akhil-gautam** [Saul-Mirone/milkdown#69]
**Describe the bug**
Getting the following error on a freshly created React app of CRA. I have followed the instruction given in the Getting Started section along with the component given there:

![Screenshot 2021-07-23 at 10 08 43 PM](https://user-images.githubusercontent.com/28865023/126814095-315f7cd2-869d-45c0-a2df-16cde02ac722.png)

**Comment by Saul-Mirone** [comment]
Fixed by version 4.6.7. Feel free to reopen if you have further questions.
