### ISSUE TITLE
inject(nodeMetadata) not operation properly with in multiple editor

### ISSUE THREAD

**Issue by nxnminieye** [Saul-Mirone/milkdown#699]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

"@milkdown/core": "^6.3.2",
"@milkdown/vue": "^6.3.2",

### Steps to reproduce

1. follow [Custom Component for Node]( https://milkdown.dev/vue#:~:text=Online%20Demo-,Custom%20Component%20for%20Node,-We%20provide%20custom)
2. add  console.log like this:
  ```
  const CustomImage: DefineComponent = defineComponent({
    name: 'my-image',
    setup() {
      const { node } = inject(nodeMetadata);
      console.log(node.attrs.src);
      return () => <img class="vue-image" src={node.attrs.src} alt={node.attrs.alt} />;
    },
  });
  ```
3. add more than one editor on one page, each editor has at least one image node 
 

### Expected behavior

console.log print only once for each image node

### Actual behavior

console.log print repeated continuously,page jammed! 

### Runtime

Chrome

### OS

Windows

### Build and bundle tools

Vite

**Comment by Saul-Mirone** [comment]
Does version 6.4 solve this issue?
