### ISSUE TITLE
Editing a link

### ISSUE THREAD

**Issue by Dorkside** [Saul-Mirone/milkdown#7]
Love the project, was thinking of coding something like this myself.

After a brief test it seems that you need to rewrite the whole link in order to edit it ?

What's the plan on this ?

**Comment by Saul-Mirone** [comment]
A toolbar is on my todo list, select the link and the link editor will display.

**Comment by Dorkside** [comment]
Ok, sounds good. Looking forward to seeing more.

**Comment by Saul-Mirone** [comment]
Done by latest commit, you can try online for the tooltip feature.

**Comment by Dorkside** [comment]
Nice, still a few bugs in my opinion, but great start.

**Comment by Saul-Mirone** [comment]
Made some optimize, looks good for now?

**Comment by Dorkside** [comment]
Should have been more explicit maybe, I'm testing on OSX, and the right click for editing a link seems a bit awkward: it triggers the contextual menu with you then need to shake off before editing.

What do you think of maybe keeping single left-click fort editing, and using meta key (cmd or ctrl) + click for opening link ?
Or are there other reasons for not using single-click for editing ?

**Comment by Saul-Mirone** [comment]
Emm, I think select the link should display the context menu, you mean you want to check if the link is correct by opening the link?

**Comment by Dorkside** [comment]
Ok, I've just realized that a double click opens the toolbar.
Actually that is a good UX, no problem there ;-).
