### ISSUE TITLE
[Bug] inline style render wrong

### ISSUE THREAD

**Issue by daqi** [Saul-Mirone/milkdown#704]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest

### Steps to reproduce

https://user-images.githubusercontent.com/1715916/187614745-f1d84fa5-4c8e-4063-a7a7-7c00b5ca312a.mov

### Expected behavior

正常

### Actual behavior

选中一些问题加粗，选中加粗文字斜体，后面会变细，再选择后面的一部分加删除线，渲染问题更多
加粗和斜体混合使用，很容易出问题
mod+z撤销也不能全部撤销掉

**Comment by Saul-Mirone** [comment]
Maybe related to https://github.com/Saul-Mirone/milkdown/blob/main/packages/transformer/src/serializer/stack.ts#L16
