### ISSUE TITLE
[Bug] inline render bug

### ISSUE THREAD

**Issue by daqi** [Saul-Mirone/milkdown#706]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest

### Steps to reproduce

https://user-images.githubusercontent.com/1715916/187716473-eaa80a9e-fe1f-4c1b-8a79-5d65681b41e4.mov

https://user-images.githubusercontent.com/1715916/187716519-fdc90954-e879-48ad-8942-c5fb6d10882d.mov

### Expected behavior

渲染有误

### Actual behavior

渲染错误

**Comment by Saul-Mirone** [comment]
That's by design of markdown. `_You_1` in github will also generate _You_1
