### ISSUE TITLE
[Bug] todo-list bug

### ISSUE THREAD

**Issue by EyebrowsWhite** [Saul-Mirone/milkdown#709]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest

### Steps to reproduce

open [live demo](https://milkdown.dev/online-demo) website,  write a todo item, and then click the box at the beginning of the line.

### Expected behavior

tick the todo item like this
<img width="253" alt="图片" src="https://user-images.githubusercontent.com/48169104/188264758-00db9b14-ab4a-4dc3-9936-1066abef2429.png">

### Actual behavior

it can't be ticked and will throw an error:
<img width="1102" alt="图片" src="https://user-images.githubusercontent.com/48169104/188264593-5618cb3b-755e-4f62-b6e2-6f4a0853353b.png">

**Comment by Saul-Mirone** [comment]
This is caused by your browser extension.
