### ISSUE TITLE
[Feature] Is there way to show Toolbar like one in Notion or Evernote

### ISSUE THREAD

**Issue by akhil-gautam** [Saul-Mirone/milkdown#71]
**Is your feature request related to a problem? Please describe.**
Is there a plugin or something to enable Toolbar for styling? I couldn't find anything from the docs.

Like this:
![images](https://user-images.githubusercontent.com/28865023/126837877-05c993a8-e1e7-41fa-bca4-565915de7e2a.jpeg)

**Comment by Saul-Mirone** [comment]
Try plugin-tooltip？

**Comment by akhil-gautam** [comment]
Tooltip plugin is not the same. It should be similar to https://quilljs.com/ via a plugin.

**Comment by Saul-Mirone** [comment]
> Tooltip plugin is not the same. It should be similar to https://quilljs.com/ via a plugin.  

There isn't one yet.

**Comment by Saul-Mirone** [comment]
But it's a common component I think, I'll give it a consider about implement this plugin or provide utils to help users create their own.

**Comment by Saul-Mirone** [comment]
Implementation plan:

- [ ] Add a command system for nodes and marks to define commands
- [ ] Plugins use commands in command system to create node (slash plugin, tooltip plugin)
- [ ] Add document about command system
- [ ] Add a out of box toolbar

**Comment by drawfund-founder** [comment]
> https://milkdown.dev/#/keyboard-shortcuts

Perhaps:
- AutoHotkey(Windows)
- [VirtualKeyboard API](https://www.chromestatus.com/feature/5680057076940800) (Chrome94)

**Comment by Saul-Mirone** [comment]
Finished by https://github.com/Saul-Mirone/milkdown/pull/202, will be released soon.
