### ISSUE TITLE
[Bug] Using plugin-prism causes error "document is not defined"

### ISSUE THREAD

**Issue by AdrakPro** [Saul-Mirone/milkdown#718]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@milkdown/plugin-prism 6.4.0 @milkdown/core 6.4.0 vite 3.1.0-beta.1 (sveltekit require)

### Steps to reproduce

1. Use boilerplate svelte example
2. Add @milkdown 6.4.0 packages

```
<script lang="ts">
	import { defaultValueCtx, Editor, rootCtx } from '@milkdown/core';
	import { gfm } from '@milkdown/preset-gfm';
	import { indent, indentPlugin } from '@milkdown/plugin-indent';
	import { clipboard } from '@milkdown/plugin-clipboard';
	import { cursor } from '@milkdown/plugin-cursor';
	import { math } from '@milkdown/plugin-math';
	import { history } from '@milkdown/plugin-history';

	import { theme } from './style/theme.ts';
	import 'katex/dist/katex.min.css';
	import './style/highlight.min.css';
	import { prism } from '@milkdown/plugin-prism';

	const defaultValue = "";

	function editor(dom) {
		Editor.make()
			.config((ctx) => {
				ctx.set(rootCtx, dom);
				ctx.set(defaultValueCtx, defaultValue);
			})
			.use(theme)
			.use(gfm)
			.use(prism)
			.use(clipboard)
			.use(history)
			.use(cursor)
			.use(math)
			.use(indent.configure(indentPlugin, {
				type: 'tab',
				size: 2,
			}))
			.create();
	}
</script>

<div spellcheck="false" use:editor></div>
```

### Expected behavior

To highlight code without breaking app down

### Actual behavior

"document is not defined"

ReferenceError: document is not defined
    at [...]/@milkdown/plugin-prism/lib/index.es.js:4266:12
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async nodeImport ([...]/node_modules/vite/dist/node/chunks/dep-3ffe6dd0.js:53401:21)
    at async eval (/src/lib/components/editor/Editor.svelte:27:32)
    at async instantiateModule ([...]/node_modules/vite/dist/node/chunks/dep-3ffe6dd0.js:53330:9)

### Runtime

Chrome, Firefox

### OS

Linux

### Build and bundle tools

Vite

**Comment by Saul-Mirone** [comment]
Can't reproduce on my side, can you provide a stackblitz link?

**Comment by AdrakPro** [comment]
https://stackblitz.com/edit/sveltejs-kit-template-default-iabmeq?file=src/routes/+page.svelte

**Comment by AdrakPro** [comment]
Thanks for hot fix. :smiley: 
Do you know by any chance how to optimize above example to be more performant?
Vite warns it has size more than 500kB and scores medium in lighthouse.

**Comment by Saul-Mirone** [comment]
The common strategy is to lazy load the editor component, because the size of an editor won't be very small. You should only import it when needed.
