### ISSUE TITLE
如何在vue3中使用

### ISSUE THREAD

**Issue by yyqsc** [Saul-Mirone/milkdown#72]
I copied the code Create a Component under the vUE menu in the official document and wrote it in the TSX file.  I then introduce the component into the page, but the console reports an Uncaught (in promise) ReferenceError: React is not defined  

```tsx
import { defineComponent } from 'vue';
import { Editor, rootCtx } from '@milkdown/core';
import { VueEditor, useEditor } from '@milkdown/vue';
import { commonmark } from '@milkdown/preset-commonmark';

import '@milkdown/theme-nord/lib/theme.css';
import '@milkdown/preset-commonmark/lib/style.css';

export const MilkdownEditor = defineComponent(() => {
  const editor = useEditor((root) =>
    new Editor()
      .config((ctx) => {
        ctx.set(rootCtx, root);
      })
      .use(commonmark),
  );

  return () => <VueEditor editor={editor} />;
});
```

```vue
<template>
  <MilkdownEditor />
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { MilkdownEditor } from '../../components/Edit/MilkDownEditor';


export default defineComponent({
  name: 'EditPage',
  components: { MilkdownEditor }
})
</script>
```

![image](https://user-images.githubusercontent.com/38276469/126857751-e2be0b9a-6162-4aa4-b25f-02a04f8a0d17.png)

![image](https://user-images.githubusercontent.com/38276469/126857810-981e1fc3-20ea-4bd9-bbc9-561842f9a86a.png)

**Comment by Saul-Mirone** [comment]
You should update your @milkdown/vue package version to be seems as the core version.

**Comment by yyqsc** [comment]
![image](https://user-images.githubusercontent.com/38276469/126857965-5a0609e7-f1ef-422b-95ff-b8bb7e59c7a4.png)

Still no, I put up a demo, can you help me see what's wrong with it?  
https://github.com/yyqsc/miledown-demo.git

**Comment by Saul-Mirone** [comment]
Hi, I clone your repo and found out that you have the wrong `vite.config.js` config, as mentioned in the [vite documentation](https://vitejs.dev/guide/features.html#vue), you should use following config:

```js
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import vueJsx from '@vitejs/plugin-vue-jsx'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue(), vueJsx()],
  esbuild: {
    jsxFactory: 'h',
    jsxFragment: 'Fragment'
  }
})
```

**Comment by yyqsc** [comment]
Ah, the foundation is not solid, make a joke, thank you very much for your help!!!!
