### ISSUE TITLE
ui界面

### ISSUE THREAD

**Issue by UvDream** [Saul-Mirone/milkdown#720]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

这个编辑器界面我可以自己定制化吗,是只能css覆盖样式吗

### Solution

我想定制化界面

### Alternatives

提供插件化,我可以定制化界面

**Comment by Saul-Mirone** [comment]
Please read docs first
https://milkdown.dev/writing-themes
