### ISSUE TITLE
[Bug] Cannot find module

### ISSUE THREAD

**Issue by AdrakPro** [Saul-Mirone/milkdown#722]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@milkdown/plugin-prism 6.4.1 vite 3.0.1-beta.1 sveltekit 1.0.0-next.454

### Link to runnable example

https://stackblitz.com/edit/sveltejs-kit-template-default-iabmeq?file=package.json

### Steps to reproduce

1. Install @milkdown 6.4.1 with prism plugin
2. App broke

### Expected behavior

To not be broken.

### Actual behavior

App is broken, because it can't find module common.js (It appears after fixing #718). Stack trace:

`Cannot find module '[...]/node_modules/refractor/lib/common' imported from [..]/node_modules/@milkdown/plugin-prism/lib/index.es.js
Did you mean to import refractor/lib/common.js?`

### Runtime

Chrome, Firefox

### OS

Linux

### Build and bundle tools

Vite

**Comment by Saul-Mirone** [comment]
https://github.com/Saul-Mirone/milkdown/commit/4bc08e746f6c722554090051f719ddce75fe2bad

**Comment by Saul-Mirone** [comment]
Please try 6.4.2.
