### ISSUE TITLE
[Bug] plugin-block: unable to drag the first list item to another list item

### ISSUE THREAD

**Issue by ngduc** [Saul-Mirone/milkdown#728]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

6.4.1

### Link to runnable example

https://milkdown.dev/online-demo

### Steps to reproduce

- open https://milkdown.dev/online-demo
- create a list with multiple list item
- try to drag the first list item to another list item (to re-arrange them). It appears to drag the whole list instead of the first item.

### Expected behavior

it should allow dragging the first list item to another list item to re-arrange them.

### Actual behavior

It appears to drag the whole list instead of the first item.

### Runtime

Chrome

### OS

macOS

### Build and bundle tools

Screenshot:
<img width="477" alt="image" src="https://user-images.githubusercontent.com/639189/190787539-a1257fc2-b63c-4026-897e-b3cf1bb4aeb9.png">

**Comment by Saul-Mirone** [comment]
It's by design. you can move the second item to first then move it. If I make the first one can be moved, there will be another bug called "unable to drag the entire list"
