### ISSUE TITLE
[Bug] ”RangeError: Position -11 out of range“ in @milkdown/plugin-slash

### ISSUE THREAD

**Issue by yandif** [Saul-Mirone/milkdown#73]
**Describe the bug**
After the page is loaded for the first time, the toolbar will pop up when no slash is entered, and an error will be reported when an item is clicked.

**To Reproduce**
[codesandbox demo](https://codesandbox.io/embed/xenodochial-dust-jveqo?fontsize=14&hidenavigation=1&theme=dark)
1. Go to the demo page
2. Click on an item
3. See ”RangeError: Position -11 out of range“

**Expected behavior**
Do not display the toolbar when no slash is entered

**Screenshots**
![GIF 2021-7-25 22-35-06](https://user-images.githubusercontent.com/52165593/126903137-01b1c3eb-8ce5-46b4-a4ca-aa37ddd5e388.gif)

**Comment by Saul-Mirone** [comment]
Fixed in 4.6.8
