### ISSUE TITLE
[Feature]Docker deployment

### ISSUE THREAD

**Issue by Crzq** [Saul-Mirone/milkdown#738]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

I need this project's docker image so that i can experience it offline. This is because most of time I am not able to get internet connected. 

### Solution

Pull the docker image

### Alternatives

Pull the offline website

**Comment by Saul-Mirone** [comment]
This project supports [dev container](https://code.visualstudio.com/docs/remote/containers), just follow the instruction.
