### ISSUE TITLE
[Feature] Allow spellcheck to be disabled from editor

### ISSUE THREAD

**Issue by rajatkulkarni95** [Saul-Mirone/milkdown#751]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

Option to disable spellcheck using the HTML attribute `spellCheck` on the Editor component

### Solution

Option to disable spellcheck using the HTML attribute `spellCheck` on the Editor component

### Alternatives

-

**Comment by Saul-Mirone** [comment]
You can set the attribute through this Prosemirror API

https://prosemirror.net/docs/ref/#view.EditorProps.attributes
