### ISSUE TITLE
[Feature] Allow HTML in menu buttons

### ISSUE THREAD

**Issue by creativiii** [Saul-Mirone/milkdown#762]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

I've been implementing my own menu but I don't want to use glyphs or just text, so I thought I'd simply pass an html string and that would work.

Unfortunately that just rendered my html as a string.

### Solution

I copied all the menu plugin files and changed [this line](https://github.com/Saul-Mirone/milkdown/blob/main/packages/plugin-menu/src/button.ts#L78):

```
    $button.innerHTML = config.icon;
```

### Alternatives

Just wondering if you'd accept a PR for this? Shouldn't really change how the current menu works but it allows for a bunch of extra customisation options.

**Comment by Saul-Mirone** [comment]
If that's the case, you can simply extend the icon in theme in next version. I'll give it an example later.

**Comment by Saul-Mirone** [comment]
Ops, sorry for the late update... I write a example for you:
https://codesandbox.io/s/aged-feather-ni4jvv
