### ISSUE TITLE
menu-selector-list does not show

### ISSUE THREAD

**Issue by scenaristeur** [Saul-Mirone/milkdown#767]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

menu

### Link to runnable example

https://scenaristeur.github.io/noosphere

### Steps to reproduce

i've build an app with milkdown in vuejs but the "heading submenu" of the menu does not show, 
I thought it is about the z-index, but i can't display it .
Any idea ? 

source code https://github.com/scenaristeur/noosphere/blob/main/src/views/MilkEditor.vue

see video below

https://user-images.githubusercontent.com/4020744/195898289-14989cf2-68d7-4fd6-93a4-5f389fdaf92d.mp4

### Expected behavior

heading submenu should be shown

### Actual behavior

heading submenu does not show

**Comment by Saul-Mirone** [comment]
Should be fixed by https://github.com/Saul-Mirone/milkdown/pull/745
