### ISSUE TITLE
[Bug] InserImage command adds "<>" to image filename

### ISSUE THREAD

**Issue by creativiii** [Saul-Mirone/milkdown#768]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

6.4.1

### Link to runnable example

https://codesandbox.io/s/milkdown-insert-image-7vit1d

### Steps to reproduce

I've been playing around with my own image uploader plugin and while almost all of it is working Milkdown is returning some invalid Markdown which I can't quite explain.

1. Open Codesandbox
2. Click on "Upload image"
3. Select any image
4. As soon as it's done the markdown will look something like: `![](<image.png>)`

### Expected behavior

The resulting markdown should not have `<>`

### Actual behavior

Ideally the output should be:

```
![](image.png)
```

### Runtime

Safari

### OS

macOS

### Build and bundle tools

Webpack, Next.js

**Comment by Saul-Mirone** [comment]
I can't see the `<>` in your demo after uploading an image with the command, interesting.
<img width="590" alt="Screen Shot 2022-10-15 at 13 01 33" src="https://user-images.githubusercontent.com/10047788/195969639-9fce252e-3d0e-4350-a8f1-19147a4054e8.png">
