### ISSUE TITLE
[Bug]每次渲染渲染编辑器都会注入好多新的style标签

### ISSUE THREAD

**Issue by ljq-96** [Saul-Mirone/milkdown#774]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

6.5.0

### Steps to reproduce

我自定义了主题插件，每次渲染渲染编辑器都会注入好多新的style标签，切换渲染几次后浏览器就会变得卡顿，不知道是什么原因造成的

即使用`themeFactory()`，也会注入新的style 只是数量会少很多

### Expected behavior

不注入新的style标签

### Actual behavior

<img width="530" alt="image" src="https://user-images.githubusercontent.com/34957717/196845706-95ac0287-e8d1-4ac3-811f-bc8729d41865.png">

**Comment by Saul-Mirone** [comment]
You should call `editor.destroy` before rerender.
