### ISSUE TITLE
[Feature] Move tasks/list items up and down with drag and drop

### ISSUE THREAD

**Issue by uggrock** [Saul-Mirone/milkdown#779]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

Currently it is not possible to move tasks in lists up and down. This is useful if you want to move completed tasks in the bottom. 

### Solution

Allow moving the task/list item up and down with drag and drop

### Alternatives

Currently you can select the text of the current list item, cut it and paste it somewhere else. The checkbox of the tasks in not coming with these steps, so it should be set manually.

**Comment by Saul-Mirone** [comment]
It has been supported by @milkdown/plugin-block.
