### ISSUE TITLE
[Bug] plugin-prism not woring in my vite project 

### ISSUE THREAD

**Issue by qirong77** [Saul-Mirone/milkdown#788]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@milkdown/plugin-prism": "^6.5.0

### Steps to reproduce

**Describe the bug**
Hello,

I'm working on a milkdown app on Vite. I use @milkdown/plugin-prism to highlight my code block. It works propertly in the dev environment,but when i bundle the project with vite and run vite preview ,found that the prism-plugin dont work, i don't know what is  the problem.
Is there anything I'm missing? Thanks in advance!

here is my package.json and basic editor component:
```
// package.json
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview"
  },
```

```
import React from 'react';
import { Editor, rootCtx } from '@milkdown/core';
import { nord } from '@milkdown/theme-nord';
import { ReactEditor, useEditor } from '@milkdown/react';
import { commonmark } from '@milkdown/preset-commonmark';
import { prism } from '@milkdown/plugin-prism';
import 'prism-themes/themes/prism-atom-dark.min.css'
export const MilkdownEditor: React.FC = () => {
    const { editor } = useEditor((root) =>
        Editor.make()
            .config((ctx) => {
                ctx.set(rootCtx, root);
            })
            .use(prism)
            .use(nord)
            .use(commonmark),
    );

    return <ReactEditor editor={editor} />;
};
```

### Expected behavior

the plugin-prism works properly in my vite bundler output

### Actual behavior

my steps:
1. npm run dev it works right
2. npm run build
3. npm run preview the prism-plugin not working

### OS

macOS

### Build and bundle tools

Vite

**Comment by Saul-Mirone** [comment]
It's caused by https://github.com/wooorm/refractor.

The problem is that when you load refractor in dev mode, it will load refractor/all, however in production mode, it will load refractor/core somehow, so all the highlight will be missing. The solution is that you need to configure the refractor like [what I do in the doc file](https://github.com/Saul-Mirone/milkdown/blob/main/website/component/MilkdownEditor/docRendererFactory.ts#L33).

**Comment by iNothlu** [comment]
> 这是[由 https://github.com/wooorm/refractor](https://github.com/wooorm/refractor) 引起的。
> 
> 问题是，当您在开发模式下加载折射器时，它将加载折射器/全部，但是在生产模式下，它会以某种方式加载折射器/核心，因此所有亮点都将丢失。解决方案是您需要像[我在文档文件中所做的](https://github.com/Saul-Mirone/milkdown/blob/main/website/component/MilkdownEditor/docRendererFactory.ts#L33)那样配置折射器。

This link has failed，can your send a new one？

**Comment by iNothlu** [comment]
> It's caused by https://github.com/wooorm/refractor.
> 
> The problem is that when you load refractor in dev mode, it will load refractor/all, however in production mode, it will load refractor/core somehow, so all the highlight will be missing. The solution is that you need to configure the refractor like [what I do in the doc file](https://github.com/Saul-Mirone/milkdown/blob/main/website/component/MilkdownEditor/docRendererFactory.ts#L33).

This link has a fail, can you send a new one.
