### ISSUE TITLE
[Feature] JSX/HTML Support + Astro Support

### ISSUE THREAD

**Issue by L1lith** [Saul-Mirone/milkdown#792]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

[Astro](https://astro.build) is an incredible web framework. It also has this incredibly [nifty feature](https://docs.astro.build/en/guides/markdown-content/) where you can put JSX (a form of HTML syntax in JS environments) directly inside of your `.mdx` pages. Currently Milkdown cannot edit these files.

### Solution

It would be cool if Milkdown could support MDX syntax. Also if Milkdown has JSX support anyways would it make sense to edit `.html` and `.astro` files as well? I understand if this is not the direction you want to go with Milkdown, but it's an idea at least :)

### Alternatives

You can currently just stick with plain MD, but it can feel a little limited sometimes. JSX could enable Milkdown to be applicable even to highly dynamic pages. I'm not sure how else you would do this.

**Comment by Saul-Mirone** [comment]
I plan to support MDX and HTML in the next major version.

**Comment by Saul-Mirone** [comment]
Closing this since we'll track the feature in https://github.com/Saul-Mirone/milkdown/issues/819.
