### ISSUE TITLE
Idea - remove current line formatting with "esc"

### ISSUE THREAD

**Issue by poisonborz** [Saul-Mirone/milkdown#8]
Awesome project! I just miss one thing I also haven't seen with other such editors so far - an easy way to exit/remove the current line style. "Esc" key could remove the styling from the current line and place the cursor on the start of it.

Would be even more useful where multiple "sticky" styles are stacked:
```
> some text
## some other|
```
To exit from this style, normally you'd have to erase current line, then press Enter twice to exit the > style.

Going further, selecting multiple lines could remove the formatting from all the selected lines. This would make it easy to add/remove block styles.

**Comment by Saul-Mirone** [comment]
A toolbar is on my todo list, select the line and the style will be easy to toggle, thanks for your idea that reminds me a shortcut maybe nice to have.

**Comment by Dorkside** [comment]
Also other possible pattern : when focusing a piece of styled text, toggle the visibility of the formatting characters.
This would allow to adjust the formatting if needed, or remove it altogether.

**Comment by Saul-Mirone** [comment]
> Also other possible pattern : when focusing a piece of styled text, toggle the visibility of the formatting characters.
> This would allow to adjust the formatting if needed, or remove it altogether.

I think the toolbar has a toggle style for now, does it work?
![image](https://user-images.githubusercontent.com/10047788/115674671-7b050500-a380-11eb-8102-e2af9b6eb068.png)
