### ISSUE TITLE
[Bug] Table column resizing handle wrong

### ISSUE THREAD

**Issue by iHaPBoy** [Saul-Mirone/milkdown#806]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

6.5.2

### Steps to reproduce

hover on the right border of the cell, the handle is **not displayed** or **in the wrong position**.

![table-column-resizing](https://user-images.githubusercontent.com/2498173/201071971-23298f26-09c5-418d-9f1f-886cfcbaf8d8.gif)

### Expected behavior

The handle is displayed in the correct location.

### Actual behavior

The handle is **not displayed** or **in the wrong position**.

**Comment by ningkehua** [comment]
Hi, bro.
I want to know how you added tooltip button to the table.
I only saw it on the milkdown playground, but I didn't see the relevant usage in the doc.
Could you tell me something about it?

**Comment by iHaPBoy** [comment]
> Hi, bro. I want to know how you added tooltip button to the table. I only saw it on the milkdown playground, but I didn't see the relevant usage in the doc. Could you tell me something about it? @iHaPBoy

@ningkehua The code for this PR is in Milkdown 6.x. The new 7.x version does not seem to retain this code.

**Comment by ningkehua** [comment]
> > Hi, bro. I want to know how you added tooltip button to the table. I only saw it on the milkdown playground, but I didn't see the relevant usage in the doc. Could you tell me something about it? @iHaPBoy
> 
> @ningkehua The code for this PR is in Milkdown 6.x. The new 7.x version does not seem to retain this code.

oh... okay，thanks for your reply
