### ISSUE TITLE
[Feature] `ToggleLink` automatically displays the input clip after adding a link

### ISSUE THREAD

**Issue by iHaPBoy** [Saul-Mirone/milkdown#808]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

`ToggleLink` does not automatically display the input chip.

### Solution

`ToggleLink` automatically displays the input chip after adding a link.

**Comment by iHaPBoy** [comment]
I tried to remove `selection.empty` and it looks good, will there be any side effects?

https://github.com/Saul-Mirone/milkdown/blob/50c645edcd42081f0953e9868bbf57e9cd69449a/packages/preset-commonmark/src/mark/link.ts#L149-L158

![toggle-link-auto](https://user-images.githubusercontent.com/2498173/201260592-bf9c8a89-099b-4ead-80ba-372eb61e736c.gif)

**Comment by iHaPBoy** [comment]
> I tried to remove `selection.empty` and it looks good, will there be any side effects?
> 
> https://github.com/Saul-Mirone/milkdown/blob/50c645edcd42081f0953e9868bbf57e9cd69449a/packages/preset-commonmark/src/mark/link.ts#L149-L158
> 
> ![toggle-link-auto](https://user-images.githubusercontent.com/2498173/201260592-bf9c8a89-099b-4ead-80ba-372eb61e736c.gif) [ ![toggle-link-auto](https://user-images.githubusercontent.com/2498173/201260592-bf9c8a89-099b-4ead-80ba-372eb61e736c.gif) ](https://user-images.githubusercontent.com/2498173/201260592-bf9c8a89-099b-4ead-80ba-372eb61e736c.gif) [ ](https://user-images.githubusercontent.com/2498173/201260592-bf9c8a89-099b-4ead-80ba-372eb61e736c.gif)

It has a problem, the input chip also appears when there is a link inside the selected text.

<img width="690" alt="image" src="https://user-images.githubusercontent.com/2498173/201260825-4cd76dcd-d74f-495e-87eb-76b61bb648fa.png">

**Comment by iHaPBoy** [comment]
Is there any solution?

**Comment by Saul-Mirone** [comment]
The internal logic for input chip of link is that when selection is **in a link mark and selection is empty**. So if you want to automatically displays the input chip, all you need to do is just move the cursor at the start of the mark.

**Comment by Saul-Mirone** [comment]
At first few versions, we show the input chip when user select the mark (even the selection is not empty). But the user experience is not good, so we switched to this behavior.

**Comment by iHaPBoy** [comment]
The current behavior is that you need to click on the text to enter a link after adding it, I think is not a good user experience.

Is it possible to add an option to turn on automatic display of the input chip?

Is there an earlier version of the code I can refer to?

**Comment by Saul-Mirone** [comment]
It's really long time ago, I think it must be a commit last year. The logic is not complicated, just compare the selection start and end with the marks range. I think it's okay to add an option for this.
