### ISSUE TITLE
[Bug] The `fold` state of Code Fence is in the document JSON

### ISSUE THREAD

**Issue by iHaPBoy** [Saul-Mirone/milkdown#830]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

6.5.2

### Steps to reproduce

The `fold` state of Code Fence is in the document JSON

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/2498173/202167758-1fe6743a-09bb-429a-9910-feb0c5181d1d.png">

### Expected behavior

The `fold` state should not be persisted in the document JSON

### Actual behavior

The `fold` state of Code Fence is in the document JSON

**Comment by Saul-Mirone** [comment]
Should has been resolved in V7.
