### ISSUE TITLE
[Bug] Menu button render issues, react integration

### ISSUE THREAD

**Issue by ddemoss222** [Saul-Mirone/milkdown#832]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

6.5.2

### Link to runnable example

https://milkdown.dev/react#online-demo

### Steps to reproduce

This is visible on the online demo. I noticed first on my local. 

It manifests when menus appear. I am viewing it within a code block on the online-demo page. Also, when I import the menu plugin in the react object. 
![milkdown bug](https://user-images.githubusercontent.com/25989271/202302330-0c57e7d7-3d57-4571-818c-4d2b49058559.png)
![milkdown bug2](https://user-images.githubusercontent.com/25989271/202302846-22577bd8-8f26-4e40-8403-625bdbc137a1.png)
![image](https://user-images.githubusercontent.com/25989271/202302397-a3985200-b223-47f2-96b9-4f35d874bd84.png)

### Expected behavior

Standard rendering of menu buttons

### Actual behavior

Floating render of button text.

### Runtime

Chrome, Firefox

### OS

Linux

### Build and bundle tools

Webpack

**Comment by Saul-Mirone** [comment]
https://milkdown.dev/faq#why-the-icons-wont-show-up-for-theme-nordtokyo

**Comment by ancheGT** [comment]
Is it possible to simplify the usage of icons?

**Comment by Saul-Mirone** [comment]
> Is it possible to simplify the usage of icons?

It will be very easy in v7
