### ISSUE TITLE
When using Dynamic loading of NextJS, getting error RangeError: Schema is missing its top node type ('doc')

### ISSUE THREAD

**Issue by bishwenduk029** [Saul-Mirone/milkdown#84]
**Describe the bug**
In order to avoid rendering Milkdown editor  on server in NextJs app, I am using [dynamic loading provided by NextJs](https://nextjs.org/docs/advanced-features/dynamic-import). With this the milkdown editor is loaded and rendered only in client.

But when I am passing valid markdown content to the component it is giving below error in console.
```RangeError: Schema is missing its top node type ('doc')```

Also the default content is not rendering.

For Milkdown editor I am referencing the code from below
[MilkdownEditor.tsx](https://github.com/Saul-Mirone/milkdown/blob/main/gh-pages/component/MilkdownEditor/MilkdownEditor.tsx)

I have removed all plugins except for following:
- Clipboard
- History
- listener

**To Reproduce**
1. Create a NEXTJs application using create-next-app
2. Simply render a page with MilkdownEditor as one of the component in the page hierarchy.
3. Referenced below code for MilkdownEditor
[MilkdownEditor.tsx](https://github.com/Saul-Mirone/milkdown/blob/main/gh-pages/component/MilkdownEditor/MilkdownEditor.tsx)
4. Use below code to dynamically load the above editor
```js
import dynamic from "next/dynamic";
const DynamicComponent = dynamic(() => import("./components/MarkdownEditor"), {
  ssr: false,
});
```
6. On server I convert the markdown to html and display in a custom component.
7. On client I use the markdown in state passed from server as input to MilkdownEditor.
8. Now do SSR rendering with getServerSideProps by passing any random markdown text.

**Expected behavior**
It should ideally render the content in the editor. But it is quite possible that I am doing something wrong with config or maybe this use case altogether is wrong.

**Screenshots**

**Desktop (please complete the following information):**
 - iOS
 - chrome

**Additional context**
I initially thought since props is set on server so may be content is not available when rendering on client. But console.logging the same shows the markdown content in browser console. Sorry if the details are too much or wrong use case. But some inputs on this can help me better understand Milkdown and use the same. My prosemirror knowledge is also not very good. But what I could understand that from schema the root node type of ```doc``` is missing. But not sure If milkdown is doing the schema initialization by default.

**Comment by Saul-Mirone** [comment]
Hi @bishwenduk029 , could you please provide a sample github repo for me to work on? Because I cannot setup it myself since I don't know how to transpile packages in node_modules in nextjs. I tried this https://github.com/kutlugsahin/next-transpile-modules but there still have some blocking issues.

**Comment by Saul-Mirone** [comment]
Also, I tried the dynamic loading features in my doc site through these steps:

1. Load the [MilkdownEditor.tsx](https://github.com/Saul-Mirone/milkdown/blob/main/gh-pages/component/MilkdownEditor/MilkdownEditor.tsx) through React.Lazy
2. Add React.Suspense in router with a loading fallback component

Transplied files:
![image](https://user-images.githubusercontent.com/10047788/128625410-0225cbc2-5a88-4820-b896-7347ab3a426b.png)

Gif:
![gDMpBx2uUz](https://user-images.githubusercontent.com/10047788/128625463-83888108-62cd-43f8-8be0-9755cfa0c121.gif)

So, The dynamic loading will be work for Milkdown Component. I think it should be some issues in NextJS part or some config problems.

**Comment by bishwenduk029** [comment]
@Saul-Mirone , Maybe difference is React.LazyLoad is to load the component in client. Whereas Dynamic from NextJs is actually bundling the component code for dynamic import and actually loading on client once the hydration is complete. 

I see your point could be a next config problem.

Also please find the config file with which I was finally able to get it to work in SSR mode
```js
const withTM = require("next-transpile-modules")([
  "@milkdown/core",
  "@milkdown/plugin-clipboard",
  "@milkdown/plugin-cursor",
  "@milkdown/plugin-emoji",
  "@milkdown/plugin-history",
  "@milkdown/plugin-listener",
  "@milkdown/plugin-math",
  "@milkdown/plugin-prism",
  "@milkdown/plugin-slash",
  "@milkdown/plugin-tooltip",
  "@milkdown/preset-gfm",
  "@milkdown/react",
  "@milkdown/exception",
]);

module.exports = withTM({
  reactStrictMode: true,
});
```

package.json

```json
"devDependencies": {
    "autoprefixer": "^10.3.1",
    "eslint": "7.32.0",
    "eslint-config-next": "11.0.1",
    "next-transpile-modules": "^8.0.0",
    "postcss": "^8.3.6",
    "tailwindcss": "^2.2.7"
  }
```

**Comment by bishwenduk029** [comment]
@Saul-Mirone , I am yet to push the git repo as I am working with other dependent packages which I am locally developing currently. Still please find a logical brief of the code below for Page component
```js
const DynamicComponent = dynamic(
  () => import("./components/ReMarkdownEditor"),
  {
    ssr: false,
  }
);

const Page = (props) => {
  const [isServer, setIsServer] = useState(true);
  const [markdown, setMarkdown] = useState(props.content);

  useEffect(() => {
    if (document) {
      setIsServer(false);
    }
  }, []);
<div>
  {isServer ? (
    <ReactMarkdown className="text-center text-gray-500 m-8 text-2xl">
      {markdown || props.content}
    </ReactMarkdown>
  ) : (
    <DynamicComponent
      className="text-center text-gray-500 m-8 text-2xl"
      content={markdown}
    />
  )}
</div>
```

**Comment by bishwenduk029** [comment]
@Saul-Mirone , thanks for looking into this. In case you still feel this is a configuration please feel free close the issue as per your comfort.

The current state of ESM vS CJS has left the nodeJS eco in a mess 😅.

BTW, awesome project 🎉. Very inspiring and cool.🙏

**Comment by Saul-Mirone** [comment]
You are very welcome. Finally I get milkdown works with Nextjs and there's nothing wrong on my side.

From your describe, I think the possible reason is that... maybe you removed the [preset-gfm](https://www.npmjs.com/package/@milkdown/preset-gfm) with other plugins 😅 .

You need at least use [preset-commonmark](https://www.npmjs.com/package/@milkdown/preset-commonmark) to get milkdown works because all the nodes are plugins....

**Comment by Saul-Mirone** [comment]
A working snapshot:
![image](https://user-images.githubusercontent.com/10047788/128631586-91980336-5a58-4185-b5ee-b6634e5344e9.png)

**Comment by bishwenduk029** [comment]
Awesome thanks, I will tried and it is working. Cool. Thanks you. 🎉

**Comment by bishwenduk029** [comment]
Sorry it was my bad.
