### ISSUE TITLE
[Bug] Custom link using renderReact goes into a re-rendering loop

### ISSUE THREAD

**Issue by rajatkulkarni95** [Saul-Mirone/milkdown#848]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

 "@milkdown/core": "^6.5.4",

### Steps to reproduce

https://codesandbox.io/s/intelligent-rosalind-gz7lu2?file=/src/App.js

### Expected behavior

Anchor links should not cause rendering issues, and be customisable

### Actual behavior

Goes into an infinite rendering loop

### Runtime

Chrome

### OS

Windows

**Comment by Saul-Mirone** [comment]
This will be fixed in v7. You can check the code in main branch to have a general feel about it.

**Comment by Saul-Mirone** [comment]
> Any way i can reference v7 since i can't really do much about Links right now!

There's no way for now. It's still under development. I can't think about a better workaround than using domm instead of react.

**Comment by rajatkulkarni95** [comment]
Cool, I don't want to be that guy, but is V7 relatively closer to being merged?

**Comment by Saul-Mirone** [comment]
I'll recommend you to wait for v7 if you need to use react to implement a lot of components. A lots of modules are rewrote for better react & vue support and the framework will be headless. Which is not possible in legacy architecture.

I think the RC for v7 will be released in January.

**Comment by rajatkulkarni95** [comment]
Thanks! I'd probably not wait for the app to go live though, if there are breaking changes, can always be incorporated! I'd probably just release it with less features. 

Thanks for making Milkdown btw
