### ISSUE TITLE
[Bug] Multiline headings, GFM-plugin, switches to CommonMark style

### ISSUE THREAD

**Issue by Ontopic** [Saul-Mirone/milkdown#855]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@milkdown/preset-gfm

### Steps to reproduce

Create a Milkdown setup, with an "H1" element, use shift+enter

### Expected behavior

Should add, to be aligned with other modules, add a `\` newline, not switch to "non-gfm" header style.

```# Milkdown 💗 React```

```# Milkdown 💗 Reactin\
what```

### Actual behavior

```# Milkdown 💗 React```

```Milkdown 💗 Reactin\
what
====```

### Runtime

_No response_

### OS

_No response_

### Build and bundle tools

_No response_

**Comment by Ontopic** [comment]
Okay, the mix of code fences is becoming a little much ^^
Very happy to see how you've progress Milkdown!

Just encountered this, which I believe to be a bug;
When the GFM plugin is activated, but you have a heading, with a newline, it switches the heading-style, to just make the last line, match "non-GFM" markdown (so add as many `=` as needed, for the character count in the last line, of the heading.

Not sure what the intended behaviour is, but turning GFM, into CommonMark, just taking the last line intro consideration, doesn't feel as intended?

**Comment by Saul-Mirone** [comment]
Milkdown won't handle how the markdown string generated. It's the job of [remark.js](https://www.npmjs.com/package/remark-stringify#use), and in my opinion, what you need is to add a remark config https://github.com/remarkjs/remark/blob/main/packages/remark-stringify/readme.md#optionssetext

**Comment by Saul-Mirone** [comment]
BTW, here's an QA for how to add remark config:
https://milkdown.dev/faq#how-to-configure-remark

**Comment by Ontopic** [comment]
Thanks for the quick reply!
In the end this is an edge-case anyway, I feel the the only "bug" in Milkdown is, it falls back to commonmark, just takig the last line into consideration. Perhaps better, to throw an error / warn to update plugins?

**Comment by Saul-Mirone** [comment]
# Milkdown 💗 React

```markdown
# Milkdown 💗 React
```

Milkdown 💗 Reactin\
what
===

```markdown
# Milkdown 💗 React\in
what
===
```

Is this you're talking about? If I understand correctly, you think it should be kept in first style if user type `Shift-Enter`.

**Comment by Ontopic** [comment]
And I say edge-case, but if you continue, to keep Milkdown as solidly progressing as it has been, it might throw-off some new devs in the future. So lowerst priority possible, but something that will, at some point, probably bite someone when content-editors, in production start pushing things ;).

**Comment by Ontopic** [comment]
I believe, for me at least, the most logical would be, to convert a multiline heading, with GFM active, to;
```
# First line of heading \
second line
```

**Comment by Saul-Mirone** [comment]
Is it possible to use `#` to represent headings if there're line breaks in heading? I tried a lot of ways here but they same won't work.

Code:

```markdown
# First line of heading \
second line
```

Rendered:

# First line of heading \
second line

**Comment by Ontopic** [comment]
The remark ecosystem probably has a plugin for it ;)
This was just my suggestion, as what I would consider the most "logical". You probably know better though! Right now, just using `=`, to underline the second line of the header, common-mark style... Probably not what anyone is looking for.
So again, low priority, but something to at some point, address.

**Comment by Ontopic** [comment]
Otherwise, the issue is more, that the editor, allows multiline headings (that work nicely), but are not really having a "working" markdown representation.

**Comment by Saul-Mirone** [comment]
get your point. I think we do can have such kind of plugins. But for GFM and commonmark, I think we should make sure the markdown we generated are align the standards. Which means, for example if a user use milkdown to edit README files, than they'll find something not right when viewing the files on Github or other platforms. I'll keep an eye on your suggestions. But currently I'm working on the next major version for Github and may not have bandwidth.

**Comment by Ontopic** [comment]
Completely agree, that is why I say; you know better than me, what the standards are. If there even is, in GFM or no, a way to define multi-line headings.
(Although I can predict, content writers, will start asking for that, sooner than expected ^^)

Mostly; just switching to common mark, on the last line of a multiline heading, doesn't seem to be helpful in any use-case.

I'll keep you posted, on what I find. Again, very impressive how far you brought the editor and how you have been keeping the progress up. Send Meo my regards!

**Comment by Ontopic** [comment]
In case there is no standard for multi line headings, in GFM or not, I would suggest, changing the "shift+enter" behaviour, in the editor to match as well (either creating a newline, that starts with `#`, or just "plain paragraph". Now the editor, and markdown, simply don't match. Which will cause confusion ^^

**Comment by Saul-Mirone** [comment]
I don't know much about typefox and codingame, but if they support vscode webview extensions, then the answer will be yes.

**Comment by Ontopic** [comment]
They support, wrapping regular vscode plugins / editors, so they can be served as a webworker / run a languageclient on a simple server, to supply a browser-based environment, with everything it needs, to pretend to be in a webview ;). I believe your "vscode-plugin", allows for that. Will give it a shot myself, and fire up Discord again, to further discuss the potential / issues I run into ;). Could be kinda cool I think.
If it turns out to be possible, to "live-update" the markdown view, or the Monaco based source (which should be the same as a VSCode source in the end), with two-way bindings.. Well, that for me would be the ultimate dream WYSIWYM with super powers.

Please ignore this, if you prefer to have this discussion — as to not pollute your issue-list any further — on Discord.
See [monaco-unified](https://github.com/remcohaszing/monaco-unified) as well.
