### ISSUE TITLE
[Bug] System Theme considered while rendering the Editor

### ISSUE THREAD

**Issue by AariefMohideen** [Saul-Mirone/milkdown#861]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

6.5.4

### Steps to reproduce

**Issue:** In Mac, Safari, the editor theme is working based on the system configuration.

- If System configured as Dark mode then the editor rendered with Dark Mode ![dark](https://user-images.githubusercontent.com/24786425/209914459-7c3dfe4e-5096-411e-989c-0fddcddb25fa.png)

- If System configured as Light mode then the editor rendered with Light Mode ![light](https://user-images.githubusercontent.com/24786425/209914507-c3957f24-a51e-4b68-adc3-ca55fc776342.png).

**Steps to Reproduce:** Landing with official website editor in Mac, Safari browser, itself can able to reproduce the issue, https://milkdown.dev/using-themes#switch-theme.

**System Configuration:**

- OS: Mac
- System: Macbook Pro (Apple M1 Max)
- Browser: Safari 16.1

**Editor Code:** (using `Nord` theme)
```
import React from 'react';
import { defaultValueCtx, Editor, rootCtx } from '@milkdown/core';
import { nord } from '@milkdown/theme-nord';
import { ReactEditor, useEditor } from '@milkdown/react';
import { commonmark } from '@milkdown/preset-commonmark';
import { menu } from '@milkdown/plugin-menu';
import { listener, listenerCtx } from "@milkdown/plugin-listener";

interface MilkdownEditorProps {
  isViewMode?: boolean;
  markdown?: string;
  onChange?: (value: string) => void;
};

const MilkdownEditor: React.FC<MilkdownEditorProps> = ({
  isViewMode = false,
  markdown,
  onChange
}) => {
  const { editor } = useEditor((root) =>
    Editor.make()
      .config((ctx) => {
        ctx.set(rootCtx, root);

        if (!isViewMode) {
          ctx.get(listenerCtx).markdownUpdated((_, markdown) => {
            onChange(markdown);
          });
        }

        if (isViewMode && markdown) {
          ctx.set(defaultValueCtx, markdown);
        }
      })
      .use(nord)
      .use(commonmark)
      .use(listener)
      .use(menu),
  );

  return <ReactEditor editor={editor} />;
};

export default MilkdownEditor;
```

### Expected behavior

The Milkdown Editor must be in a light mode based on the application theme configuration, not an system based configuration.
It cause the application theme consistency, everything is an light mode but the editor alone in Dark mode.

### Actual behavior

The Milkdown Editor theme must be render/apply based on the application theme.

**Note:** The issue only reproducable in Mac, checked with Window / Linux based system with Chrome browser, it's working as expected (rendered with light theme)

### Runtime

Safari

### OS

macOS

### Build and bundle tools

Webpack

**Comment by Saul-Mirone** [comment]
You can control which theme to render by using `nordLight/nordDark` instead of `nord.

**Comment by AariefMohideen** [comment]
@Saul-Mirone it could be great and helpful for other if you add the same in documentation (https://milkdown.dev/using-themes).

**Comment by wjy18666** [comment]
> `nordLight/nordDark`您可以使用而不是 来控制要呈现的主题`nord`。

你好，这个深浅主题切换如何实现？然后编辑器右侧的文档目录导航大纲是自己实现的吗？有没有现成的插件？
