### ISSUE TITLE
[Feature] Put style in a dom element other than head

### ISSUE THREAD

**Issue by jpradelle** [Saul-Mirone/milkdown#864]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

I would like to use milkdown in WebComponent, it seems it's almost working. I only miss CSS.
By default CSS is put in HTML head. Using WebComponent shadowDom style added in head is ignored, it would need to be inside shadowDom of WebComponent. 

### Solution

Giving a dom element for target where to put style from a configuration parameter would solve the issue. 

### Alternatives

I see no alternative solution

**Comment by Saul-Mirone** [comment]
Configure the emotion to insert styles into your element.
https://github.com/Saul-Mirone/milkdown/pull/279
