### ISSUE TITLE
[Bug]code block style exception

### ISSUE THREAD

**Issue by lang321** [Saul-Mirone/milkdown#866]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

v6.5.4

### Steps to reproduce

![image](https://user-images.githubusercontent.com/31792970/210734611-69c581a3-e64d-4fed-931f-896dde1b934a.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/31792970/210734611-69c581a3-e64d-4fed-931f-896dde1b934a.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/31792970/210734611-69c581a3-e64d-4fed-931f-896dde1b934a.png)

### Runtime

Chrome

### OS

macOS

### Build and bundle tools

Vite

**Comment by Saul-Mirone** [comment]
https://milkdown.dev/faq#why-the-icons-wont-show-up-for-theme-nordtokyo
