### ISSUE TITLE
[Bug] emoji not rendering

### ISSUE THREAD

**Issue by knownasilya** [Saul-Mirone/milkdown#876]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

emoji (all)

### Steps to reproduce

Use emoji plugin as normal, the dropdown will render broken images.
Looks like https://github.com/twitter/twemoji/issues/580 is the issue? Seems like you can set a custom cdn? How would we do that here, and can we set it as a default?

### Expected behavior

Emoji should work fine

### Actual behavior

They don't render images

**Comment by Saul-Mirone** [comment]
Yep, I think so. Will fix it today.

**Comment by knownasilya** [comment]
@Saul-Mirone when do you think a new release will go out?

**Comment by Saul-Mirone** [comment]
> @Saul-Mirone when do you think a new release will go out?
> 
> p.s. I'm using milkdown over here https://typelog.dev

Really cool app! I think the release will be together with v7. For now you can configure the emoji plugin to avoid the error:
```typescript
emoji.config(emojiNode, {
  twemojiOptions: {
    base: 'https://cdn.jsdelivr.net/gh/twitter/twemoji/assets/'
  }
});
```

**Comment by knownasilya** [comment]
Where does `emojiNode` come from?

**Comment by Saul-Mirone** [comment]
> Where does `emojiNode` come from?

It's exported from `@milkdown/plugin-emoji`.
