### ISSUE TITLE
[Feature] Preview panels on the math equations being edited

### ISSUE THREAD

**Issue by haowen-xu** [Saul-Mirone/milkdown#91]
It might be a deadly useful feature if there could be preview panels on the math equations being edited, just like Typora.

![image](https://user-images.githubusercontent.com/38396475/129294942-39a96e2d-76c2-4975-88bf-3935609009ec.png)

**Comment by Saul-Mirone** [comment]
Good news: I've already started working on this.

**Comment by Saul-Mirone** [comment]
- [x] Preview panel for math block
![image](https://user-images.githubusercontent.com/10047788/134635321-99ef207a-d795-412c-bf1f-a6968c2697ac.png)
- [ ] Preview panel for inline math
