### ISSUE TITLE
[Feature] Use tab key to switch cell in table

### ISSUE THREAD

**Issue by marcosteam** [Saul-Mirone/milkdown#97]
**Is your feature request related to a problem? Please describe.**
So I try this awesome project, but still have some problem, when I try to insert a table in the document, I can't use tab key jump to another cell, it's always jump to the top of the document. 

**Describe the solution you'd like**
use tab key to switch cell, just like typora.

**Comment by Saul-Mirone** [comment]
You can configure all shortcuts.

https://github.com/Saul-Mirone/milkdown/blob/main/packages/plugin-table/README.md

**Comment by marcosteam** [comment]
ok, thanks to this awesome project.
