### ISSUE TITLE
[Feature] Add backtick symbol support

### ISSUE THREAD

**Issue by marcosteam** [Saul-Mirone/milkdown#98]
**Is your feature request related to a problem? Please describe.**
I can't use backtick symbol in editor, must edit original markdown code or use tooltip button to add block.

![image](https://user-images.githubusercontent.com/25745812/129481184-3d2ae47a-78d3-46ad-baa5-4d0a676994c6.png)

**Comment by Saul-Mirone** [comment]
Cannot reproduce this, did you enter double `` first?

**Comment by marcosteam** [comment]
OK, may the browser's problem, I refreshed browser and clean the cache, work perfect.
